### ISSUE TITLE
Suggestion - Default Color change - Gaming industry "standard" colors

### ISSUE THREAD

**Issue by araxz** [RandyKnapp/ValheimMods#102]
Default Games color goes as follow
- Introduced in WoW and respected by most other games afterwards.
- Therefore gamer used to this color scheme to identify magic item rarity.

Basically would only need to change default values in config file to these:

Magic Rarity Color (or Uncommon)
**Green**

Magic Crafting Material Icon Index
**3**

Rare Rarity Color
**Blue**

Rare Crafting Material Icon Index
**5**

Epic Rarity Color
Purple (Already good)

Epic Crafting Material Icon Index
7 (Already good)

Legendary Rarity Color
Yellow (Already good)

Legendary Crafting Material Icon Index
2 (Already good)

Magic Rarity Display Name
**Uncommon**

**Comment by RandyKnapp** [comment]
I like the colors I have, and you can set the ones you want for your own game. But that's for the suggestion.
