### ISSUE TITLE
[REQUEST] - Jams - How are you assigning the foods health value and stamina value?

### ISSUE THREAD

**Issue by sbtoonz** [RandyKnapp/ValheimMods#104]
Trying to look at the code and it looks like you just look for the Jams section and start putting your foods into that section? I am trying to figure out how to add a health and stamina declaration into the json file in order to kind of make this a bigger food menu engine as the one I am using now based on Jotunnlib is kind of buggy

**Comment by RandyKnapp** [comment]
It's on the item prefab itself. If you want it configurable from json you'll need to wait until the prefab asset gets loaded, then modify the values

**Comment by sbtoonz** [comment]
I see how it feeds the actual sources needed to craft XYZ food item from recipes.json I am just trying to grasp how you accounted for the HP/Stamina of the Jam food items you used other than just using the prefab Jam class

If I am understanding the code correctly just using the prefab Jam class results in the health gain of 50 from the jam and then ingredients are based on recipes.json 

images are bundled into the assets file (i think still trying to grasp this i usually code stuff for MCU's so this many resources is new)

**Comment by sbtoonz** [comment]
or ... can I just fill recipes.json with the extra line items that are getting patched when TryRegisterItems() and TryRegisterRecipes() gets called as long as I am filling the recipes.json with what valheim would be expecting normally in those fields for health and stamina etc

**Comment by RandyKnapp** [comment]
It's not how I would do it, but you do you :)

**Comment by sbtoonz** [comment]
I haven't ever modded a game before so I am just kind of fumbling around with my C knowledge

I was hoping to elaborate on the recipes you already offer and not have to rely on something like Jotunnlib etc

**Comment by RandyKnapp** [comment]
Personally, I like recipes to just be recipes. You load them in, their references get fixed up, they get added to the recipe list, done. If I wanted to modify food item values I would make a separate file for that. Something like: `itemconfig.json`:
```json
  "Items": [
    {
      "PrefabName": "QueensJam",
      "Food": 45,
      "FoodStamina": 60
    }
  ]
```

**Comment by sbtoonz** [comment]
I think I coded myself into  a corner here because I am thinking about this the wrong way 

how would you pass the m_foodStamina value to the game unless you're doing at item drop since Recipes doesn't have any kind of declaration for m_foodStamina 

I was able to structure how you explain the json file parsing in now I am looking at the prefab creator and trying to figure that part out 

I am wanting to try to figure it out but it would help me if I am on the right mindset with passing m_foodStamina modifier in ItemDrop SharedData 

Or does the Recipe do this for you? That is the part I am confused about

**Comment by RandyKnapp** [comment]
So recipes are completely distinct from items. What you want to do is sometime after ObjectDB initializes, get the item prefab from its list, and modify the prefab's ItemDrop m_itemData m_shared values with the values from your file.

**Comment by sbtoonz** [comment]
Definitely appreciate it Json is the bane of my existance and understanding how this all parses together is intense, I have a goal in mind though now just have to work away at it closing issue as it isnt an issue was really just a 

"hey can I add custom food val and stamina vals to my new custom jams and other foods I am adding via this framework? Without touching Valheims existing food"

**Comment by sbtoonz** [comment]
Also can i ask how you packed up the assets for this ? It doesnt seem to be included in the Visual studio project unless I am missing something  I believe you packed them in unity

**Comment by RandyKnapp** [comment]
First, install Unity using Unity Hub. Install version 2019.4.20f1

Then install Thunderkit using the package install from git instructions here: https://github.com/PassivePicasso/ThunderKit

Then, follow these instructions to make a build asset bundles button: https://docs.unity3d.com/Manual/AssetBundles-Workflow.html

Then, make your assets, add them to an asset bundle, and build bundles.

**Comment by sbtoonz** [comment]
I had made it into unity and the world started looking like it was making sense :D 

You put all the framework into this already to do exactly what I am after :D this is amazing thank you so much for open sourcing your stuff

**Comment by sbtoonz** [comment]
```
[Info   : Unity Log] [PrefabCreator] Added recipe: Recipe_KingsJam
[Info   : Unity Log] [PrefabCreator] Added recipe: Recipe_Pancake
[Info   : Unity Log] [PrefabCreator] Added recipe: Recipe_NordicJam
```

it was at this exact moment i felt the epic win

**Comment by sbtoonz** [comment]
OK OK so the final thing I cant wrap my head around  (this is by far trivial and probably due to my model setup) 
I setup my food item in the identical manner as your food items in unity as far as the Item Drop (script) settings [minus the item name and icon obviously] 

When I try to attach it to an item stand to set my table with it denies me 

I validated all the other line entries match Raspberry jam for instance 
specifically referring to like the Item type = consumable with attach override = none just like the others etc

**Comment by sbtoonz** [comment]
![image](https://user-images.githubusercontent.com/67915879/113466557-780e9880-9402-11eb-8bb0-5b5a037c1421.png)

**Comment by sbtoonz** [comment]
am I allowed to share my project built off your jam engine? (credits for the jam backend to you obviously all i did was add assets and make them workable)  thanks in advance for your help and for posting this stuff its been super cool to play with

**Comment by RandyKnapp** [comment]
Yes, but only if you credit me and link to the Jam mod in your mod
description. Thanks
