### ISSUE TITLE
Build 0.7.1

### ISSUE THREAD

**Issue by HeberPcL** [RandyKnapp/ValheimMods#108]
In my compilation this error appears, without having made any changes. What could it be?

`[Error  : Unity Log] MethodAccessException: Method `Inventory.AddItem(ItemDrop/ItemData,int,int,int)' is inaccessible from method `ExtendedItemDataFramework.Inventory_AddItemFromLoad_Patch.Prefix(Inventory,bool&,string,int,single,Vector2i,bool,int,int,long,string)'
Stack trace:
ExtendedItemDataFramework.Inventory_AddItemFromLoad_Patch.Prefix (Inventory __instance, System.Boolean& __result, System.String name, System.Int32 stack, System.Single durability, Vector2i pos, System.Boolean equiped, System.Int32 quality, System.Int32 variant, System.Int64 crafterID, System.String crafterName) (at <2331d16138bc4aa7a28dc9ed5d846732>:0)
(wrapper dynamic-method) Inventory.DMD<Inventory::AddItem>(Inventory,string,int,single,Vector2i,bool,int,int,long,string)
(wrapper dynamic-method) Inventory.DMD<Inventory::Load>(Inventory,ZPackage)
Player.Load (ZPackage pkg) (at <6fd2223d69c147d18c77057ce0dedd7b>:0)
PlayerProfile.LoadPlayerData (Player player) (at <6fd2223d69c147d18c77057ce0dedd7b>:0)
FejdStartup.SetupCharacterPreview (PlayerProfile profile) (at <6fd2223d69c147d18c77057ce0dedd7b>:0)
FejdStartup.UpdateCharacterList () (at <6fd2223d69c147d18c77057ce0dedd7b>:0)
FejdStartup.SetSelectedProfile (System.String filename) (at <6fd2223d69c147d18c77057ce0dedd7b>:0)
FejdStartup.Start () (at <6fd2223d69c147d18c77057ce0dedd7b>:0)`

**Comment by RandyKnapp** [comment]
Use publicized dlls. Check the closed issues
