### ISSUE TITLE
[BUG] - Craft from chest does not function with the plugin anymore | EpicLoot 0.7.1 Dedicated Install

### ISSUE THREAD

**Issue by sbtoonz** [RandyKnapp/ValheimMods#109]
Neither Valheim+'s built in craft from chest nor the stand alone plugin work with any of the tabs offered by your plugin now

I have to actually be holding the items to enchant and mats to enchant with is this intended behavior?

**Comment by sbtoonz** [comment]
Running Client side and server side

**Comment by sbtoonz** [comment]
Hmm... it seems intermittent  let me try to get logs

**Comment by DarkSir23** [comment]
It seems to affect Forge and Workbench when I use CraftingWithContainers by abearcodes, It seems to affect everything (crafting, building at least) with CraftingFromContaners by adenethorn.

**Comment by ramonsantana** [comment]
Crafting and building with CraftingWithContainers work but enchanting is not picking up the items from chest
