### ISSUE TITLE
Can't compile the code

### ISSUE THREAD

**Issue by Celludriel** [RandyKnapp/ValheimMods#11]
Hey,

I tried forking and cloning your repository into visual studio 2019.  However I can't get it compiled.  Can it be you altered the assembly_valheim and assembly_utils dll's ?

I was trying to learn how to make new items for valheim.

**Comment by RandyKnapp** [comment]
You need to use the publicized dlls. Tool here: https://github.com/MrPurple6411/Bepinex-Tools/tree/main/Bepinex-Publicizer

**Comment by Celludriel** [comment]
I got it compiled thanks and good job figuring out how to add items to that objectDB !
