### ISSUE TITLE
[BUG] - when invoking quest it does not start..?

### ISSUE THREAD

**Issue by sbtoonz** [RandyKnapp/ValheimMods#110]
```
[Error  : Unity Log] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack trace:
System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Trader.Say (System.Collections.Generic.List`1[T] texts, System.String trigger) (at <6fd2223d69c147d18c77057ce0dedd7b>:0)
Trader.OnBought (Trader+TradeItem item) (at <6fd2223d69c147d18c77057ce0dedd7b>:0)
EpicLoot.Adventure.Feature.TreasureMapListPanel+<>c__DisplayClass4_0.<OnMainButtonClicked>b__0 (System.Boolean success, UnityEngine.Vector3 position) (at <d7a007493fd5431a8b3f420af2588584>:0)
EpicLoot.Adventure.Feature.TreasureMapsAdventureFeature.CreateTreasureChest (Heightmap+Biome biome, Player player, UnityEngine.Vector3 spawnPoint, UnityEngine.Vector3 normal, EpicLoot.Adventure.AdventureSaveData saveData, System.Action`2[T1,T2] callback) (at <d7a007493fd5431a8b3f420af2588584>:0)
EpicLoot.Adventure.Feature.TreasureMapsAdventureFeature+<>c__DisplayClass5_0.<SpawnTreasureChest>b__0 (System.Boolean success, UnityEngine.Vector3 spawnPoint, UnityEngine.Vector3 normal) (at <d7a007493fd5431a8b3f420af2588584>:0)
EpicLoot.Adventure.Feature.AdventureFeature+<GetRandomPointInBiome>d__17.MoveNext () (at <d7a007493fd5431a8b3f420af2588584>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <51725b129ecd4967a9a213c1ae65b295>:0)****
```

**Comment by sbtoonz** [comment]
out of 3 tries the 3rd chest spawned but all start this out of range error

**Comment by sbtoonz** [comment]
[Error  : Unity Log] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack trace:
System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Trader.Say (System.Collections.Generic.List`1[T] texts, System.String trigger) (at <6fd2223d69c147d18c77057ce0dedd7b>:0)
Trader.OnBought (Trader+TradeItem item) (at <6fd2223d69c147d18c77057ce0dedd7b>:0)
EpicLoot.Adventure.Feature.ClaimableBountiesListPanel.OnMainButtonClicked () (at <d7a007493fd5431a8b3f420af2588584>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <51725b129ecd4967a9a213c1ae65b295>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <51725b129ecd4967a9a213c1ae65b295>:0)
UnityEngine.UI.Button.Press () (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.EventSystems.EventSystem:Update()


when turning in a bounty as well

**Comment by sbtoonz** [comment]
Accepted bounty: Hunt the Druid 

Had to go kill a Deathsquito?

**Comment by RandyKnapp** [comment]
The deathsquitos name is "hunt the druid"

**Comment by sbtoonz** [comment]
Ah disregard subsequent comment... I guess the quest worked as expected then not sure why the stuff in the console when taking it
