### ISSUE TITLE
Tombstone looting deletes slotted items

### ISSUE THREAD

**Issue by Dirtydeedz** [RandyKnapp/ValheimMods#113]
Co Op server. I died, another gamer who also uses this mod, looted my tombstone for items to build a teleporter. After I teleported through the gate and looted my tombstone, all quick slot items were gone.

**Comment by RandyKnapp** [comment]
Does the server have the mod installed?

**Comment by Dirtydeedz** [comment]
No sir! Rented server.

**Comment by RandyKnapp** [comment]
I think the problem might be that the server doesn't have it installed. See the standard tombstone isn't big enough to hold all the items if you have my mod installed. And my mod does make the tombstone bigger. But if you leave the zone where the tombstone spawned, the server has to save that data, and won't run the right code to save it at the bigger size because my mod isn't installed on the server.

**Comment by Dirtydeedz** [comment]
Just FYI, I have had this recently to happen in my single player game. I found an old tombstone from when I was using ver 1.50 and my slotted items were missing. Probably b/c of the newer version.

**Comment by Denthamos** [comment]
My friend and me had the same issue but discovered something. The items are still in your inventory per say, you just cannot access them. When we used the sacrifice/recycle tab from another mod on the crafting stations, we could see the items there. Just not access them in any way.

**Comment by virtualbjorn** [comment]
Me and my friends playing on the server have this issue often

**Comment by virtualbjorn** [comment]
Me and my friends playing on the server have this issue often

**Comment by virtualbjorn** [comment]
Equipment and also Quickslots items all went poof when trying to recover items from a tombstone, It just says Items recovered when you first interact with it and the tombstone go poof

**Comment by guythnick** [comment]
Also wanted to point out that after having the same issue with the slot items disappearing on death with full inventory, I installed the mod server-side on our dedicated server and ran a test.  It is still losing all the slotted items when recovering from the tombstone.  I have the mod installed on the server and client as well. Only thing in the log is:

`[Info   : Unity Log] 04/16/2021 14:13:04: Grave should fit in inventory, loot all

[Info   : Unity Log] 04/16/2021 14:13:04: Player 706618887 wants to takeall from Player_tombstone(Clone)   im: 706618887
`
