### ISSUE TITLE
Jam - Hard coded path - Installation issue when using r2modman

### ISSUE THREAD

**Issue by Chromos-Def** [RandyKnapp/ValheimMods#12]
The issue is with Jam.

![jam_path_error](https://user-images.githubusercontent.com/47635128/109433699-bc5fe080-79df-11eb-8759-f520a8586fef.png)

Its looking for
`BepInEx\plugins\Jam\recipes.json`

But the way r2modman installs plugins the path is actually
`BepInEx\plugins\RandyKnapp-Jam\recipes.json`

**Comment by RandyKnapp** [comment]
It's not compatible with r2modman, just BepInEx.

**Comment by Chromos-Def** [comment]
Can you disable the option to Install with Mod Manager on the Thunderstor.io website? It could lead some people astray not knowing this information.

**Comment by RandyKnapp** [comment]
I'm gonna try to fix it. Sorry for being defensive.

**Comment by Chromos-Def** [comment]
No worries at all. Hopefully everyone will be able to _jam_ out without a hitch. :P

**Comment by RandyKnapp** [comment]
Bahaha

**Comment by RandyKnapp** [comment]
This should be fixed now.
