### ISSUE TITLE
[EpicLoot 0.7.2] Treasure and Bounty crashes client on dedicated server when attempting to generate spawns on map

### ISSUE THREAD

**Issue by elfredycadapan** [RandyKnapp/ValheimMods#120]
Accepting a bounty or treasure map will normally open the map and show you the location. This works correctly on single-player. However on dedicated server, the game will freeze and the map will not open ("Locating Bounty" messsage), and then 30 seconds later the game client will time out and disconnect (note this isn't a crash to desktop, just a disconnect from game server). 

Dedicated server (LGSM vhserver on Ubuntu Linux), Valheim Steam client on Windows 10.

---------------------
server-side log (vhserver-console.log):
--------------------
04/06/2021 20:19:52: ZRpc timeout detected

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 20:19:52: Closing socket 76561198044600716

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 20:19:52:   send queue size:0

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 20:19:52: Got status changed msg k_ESteamNetworkingConnectionState_None

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 20:19:52: Destroying abandoned non persistent zdo 1050676925:1 owner 1050676925

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 20:19:52: Destroying abandoned non persistent zdo 1050676925:97 owner 1050676925

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 20:19:52: Destroying abandoned non persistent zdo 1050676925:111 owner 1050676925

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 20:19:52: Destroying abandoned non persistent zdo 1050676925:101 owner 1050676925

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 20:19:52: Destroying abandoned non persistent zdo 1050676925:106 owner 1050676925

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 20:19:52: Disposing socket

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 20:19:52: Disposing socket

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

------------------
player.log on client side:
-------------------
04/06/2021 13:19:28: Generating locations
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:19:28: Checking for location duplicates
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:19:32: Failed to place all SwampRuin2, placed 49 out of 50
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:19:34: Failed to place all FireHole, placed 81 out of 200
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01:  Done generating locations, duration:32900.1517 ms
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Got status changed msg k_ESteamNetworkingConnectionState_ClosedByPeer
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Socket closed by peer Steamworks.SteamNetConnectionStatusChangedCallback_t
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01:   Closing socket 90144989146384390
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Closing socket 90144989146384390
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Failed to send data k_EResultNoConnection
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01:   send queue size:31
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Got status changed msg k_ESteamNetworkingConnectionState_None
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Disposing socket
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Last socket, unregistering callback
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: ZSteamSocket  UnregisterGlobalCallbacks, existing sockets:0
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Disposing socket
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Last socket, unregistering callback
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: ZSteamSocket  UnregisterGlobalCallbacks, existing sockets:0
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

04/06/2021 13:20:01: Lost connection to server:ErrorDisconnected

**Comment by elfredycadapan** [comment]
wild guess is this is the culprit:
> 04/06/2021 13:20:01: Done generating locations, duration:32900.1517 ms

32 seconds is too long for the server to wait for the client to respond and it times out (I notice the timeout is almost always 30 seconds). it's possible all the "Failed to Place" errors are related. 

is there a keepalive signal the client can do during the location generation routine that tells the server client is still alive?

**Comment by RandyKnapp** [comment]
Thanks for the detailed report, I accidentally submitted code I was testing. It was just fixed in 0.7.3

**Comment by elfredycadapan** [comment]
thanks RandyKnapp, just tested on 0.7.4 and can confirm disconnect issue is fixed for both bounties and treasure maps.

**Comment by RandyKnapp** [comment]
Great, thanks!
