### ISSUE TITLE
Fighting Greydwarf Shaman Bounty causes game crash

### ISSUE THREAD

**Issue by Larkenx** [RandyKnapp/ValheimMods#122]
When fighting a bounty in the Black Forest, I've got a reoccurring game crash that happens when dealing damage to the bounty.

See https://streamable.com/9j2ar4

**Comment by RandyKnapp** [comment]
Can you please send me the player log from this? (find it here: `C:\Users\user\AppData\LocalLow\IronGate\Valheim\Player.log`) Also, what version of EpicLoot?

**Comment by Larkenx** [comment]
EpicLoot 0.7.4
CreatureLevelAndLootControl 3.5.1


Here's the player log, but I don't see anything in the logs that shows the crash

[Player.log](https://github.com/RandyKnapp/ValheimMods/files/6274730/Player.log)

**Comment by RandyKnapp** [comment]
I have no idea what would cause this. Can you try removing ALL mods except
EpicLoot and its dependencies and trying this again?

**Comment by Larkenx** [comment]
Root cause appears to be CreatureAndLevelLootControl by Smoothbrain. Disabling that mod fixed the crash
