### ISSUE TITLE
[EpicLoot] Recent updates (7.0+) breaks item names/tooltips for other mods

### ISSUE THREAD

**Issue by greenskye** [RandyKnapp/ValheimMods#123]
Items show their internal name rather than the friendly english name. Issue is resolved if I remove EpicLoot or rollback to previous version:

![image](https://user-images.githubusercontent.com/12568635/114057312-131ace80-9858-11eb-8b84-2cbc5508ac2f.png)

**Comment by RandyKnapp** [comment]
I don't see this locally, it must be some kind of mod conflict. As always, please send me your:
Player.Log
List of all your currently installed mods

**Comment by greenskye** [comment]
[Player.log](https://github.com/RandyKnapp/ValheimMods/files/6281168/Player.log)

Attached Player.log. Can confirm it is a conflict with the mod ZombMoreArrows. Additionally there is a report of a similar issue on the Nexus bug tracker:
![image](https://user-images.githubusercontent.com/12568635/114089852-466f5480-987c-11eb-9a34-f47e5ee52383.png)
[ZombMoreArrows.zip](https://github.com/RandyKnapp/ValheimMods/files/6281179/ZombMoreArrows.zip)

ZombMoreArrows seems to be hidden at the moment on Nexus, so I've attached a copy of the mod here as well.
