### ISSUE TITLE
[EpicLoot 0.7.5] Treasure chests can spawn inside rocks

### ISSUE THREAD

**Issue by Larkenx** [RandyKnapp/ValheimMods#124]
This one was extremely satisfying to find but wasn't sure if this was intended :) 

![image](https://user-images.githubusercontent.com/12945799/114247130-637e5300-9962-11eb-89ca-ce3f33525350.png)

**Comment by Digitalroot** [comment]
I've had them spawn underground and had to dig them up. Now that I know that it can happen I will now dig around for them. I enjoy it as a feature.
