### ISSUE TITLE
[EpicLoot 0.7.5 & 0.7.6] Unity Error for null references

### ISSUE THREAD

**Issue by Thorton101** [RandyKnapp/ValheimMods#125]
Hello Randy,

starting Valheim with one of the new versions of EpicLoot,
the console shows some errors.

[https://drive.google.com/file/d/1emAuyvCm0azTln1Ol-RXrTbow_BzpmCg/view?usp=sharing](url)

![EpicLoot_Error_076](https://user-images.githubusercontent.com/9900627/114258279-dbca3000-99c5-11eb-92b2-9c7140e411f7.jpg)

Game & plugin is playable, don't know how import that error is.

best regards & keep up the good work
Thorton

**Comment by RandyKnapp** [comment]
Looks like a mod compatibility issue with Planting Plus. But I will make my code more defensive.

**Comment by Thorton101** [comment]
I don't get these errors, if I install version 0.7.4 with plantingplus installed.
Didn't mentioned that above but in the bug section of your mod @nexus.

best regards
Thorton

**Comment by RandyKnapp** [comment]
Yes I know, this particular code path was added in 0.7.6. but it didn't account for whatever planting plus is doing (probably instantiating some prefab)
