### ISSUE TITLE
No Status for Available Bounties

### ISSUE THREAD

**Issue by MrTrumpoi** [RandyKnapp/ValheimMods#126]
This is running on a dedicated server, the same mods are running on the client/server. This bug has only occurred since updating to the latest version, however, the status correctly appears when the bounty is active.
![image](https://user-images.githubusercontent.com/7492720/114272840-a5b19e00-9a0f-11eb-808a-901c9d81daff.png)
![image](https://user-images.githubusercontent.com/7492720/114272850-ac401580-9a0f-11eb-8c87-228a8b5d15d9.png)
[Player.log](https://github.com/RandyKnapp/ValheimMods/files/6289988/Player.log)

**Comment by RandyKnapp** [comment]
Is the dedicated server you're running on a Linus or Mac server, by chance?

**Comment by MrTrumpoi** [comment]
It is being hosted on a Windows 64Bit machine.

**Comment by Digitalroot** [comment]
I looked into this and tried to fix it. I run into it playing local/solo. I ended up hard coding the name for my local build. From what I saw it looks like the code is correct. I was unable to find the cause and a fix for it.
