### ISSUE TITLE
The Boss's trophies is dropped on the same amount of online players.

### ISSUE THREAD

**Issue by J-Pster** [RandyKnapp/ValheimMods#127]
Hello, I am the owner of the biggest Valheim server in Brazil, I have about 40-60 simultaneous players and I am having a huge problem with the Boss Drop.

They drop 35 trophies if there are 35 players online, always following the amount of players online.

This is breaking the server economy, is this a bug or can it be change it?

**Comment by RandyKnapp** [comment]
You can turn it off in the config. I might change it to be the number of players close by.
