### ISSUE TITLE
All magic materials gone

### ISSUE THREAD

**Issue by MrDecepticon** [RandyKnapp/ValheimMods#132]
After updating Epic Loot to 0.7.6 today, all my magic materials gained from sacrificing magic loot is gone.  Also materials cannot be generated by sacrificing magic loot.  I made sure all other mods by RandyKnapp are up to date as well.

**Comment by MrDecepticon** [comment]
Also, all RPG elements are gone from the trader.  No bounties or anything.  Place holders such as the UI is still there.

**Comment by RandyKnapp** [comment]
Please attach your player log

**Comment by MrDecepticon** [comment]
[Player-prev.log](https://github.com/RandyKnapp/ValheimMods/files/6303903/Player-prev.log)
My log from yesterday.

**Comment by MrDecepticon** [comment]
Maybe it was BetterUI mod?  It updated this morning and now I can see the  magic resources when I go into Sacrifice but all my previously acquired resources from item sacrifices are still gone.

**Comment by anye77** [comment]
@RandyKnapp   I've used it recently Planting Plus，With our epic booty, there will be killing monsters and logging in the game, with no damage feedback
