### ISSUE TITLE
[Epic Loot 0.7.6] Bounty spawn/pin errors on multiplayer server

### ISSUE THREAD

**Issue by sbtoonz** [RandyKnapp/ValheimMods#134]
Issue encountered:
Bounty spawned but did not reward after kill
Did not remove pin from map 

logs for issue:

`[Info   : Unity Log] 04/14/2021 13:56:51: Spawned Deathsquito x 1

[Info   : Epic Loot] lifesteal 1.273994
[Info   : Unity Log] skill level: 72.30391
[Info   : Unity Log] [BetterDiscordPresence] Updating Presence!
[Warning: Epic Loot] BountyTarget.OnDeath
[Warning: Epic Loot] SENDING -> RPC_SlayBountyTarget: Deathsquito (target)
[Info   : Epic Loot] Rolling on loot table: Deathsquito (lvl 2), spawned 0 items at drop point((3254.5, 62.6, -1424.6)).
[Info   : Unity Log] skill level: 72.30391
[Info   : Unity Log] skill level: 72.30391
[Info   : Unity Log] removing pin for CS1534903504:16286
[Info   : Epic Loot] lifesteal 7.221592
[Info   : Unity Log] skill level: 72.30391
[Info   : Unity Log] removing pin for CS131234513:14331
[Info   : Epic Loot] lifesteal 26.51668
[Info   : Epic Loot] lifesteal 29.80866
[Info   : Unity Log] skill level: 72.30391
[Info   : Unity Log] removing pin for CS131234513:14371
[Info   : Epic Loot] lifesteal 13.3277
[Info   : Epic Loot] lifesteal 17.14796
[Info   : Epic Loot] lifesteal 4.514184
[Info   : Unity Log] skill level: 72.30391
[Info   : Unity Log] removing pin for CS131234513:14392
[Info   : Unity Log] removing pin for CS__131234513:14391
[Info   : Epic Loot] RollEffect: ReduceWeight Magic value=90 (min=70 max=90)
[Info   : Epic Loot] RollEffect: ModifyStaminaRegen Magic value=13 (min=10 max=20)`

How to replicate:
Take bounty from Trader for deathsquito
Go to location and kill all available deathsquitos 
Bounty reward never shows nor does map pin go away 

Verified location coordinates that reflect in spawn log but still cant find the lil guy

**Comment by sbtoonz** [comment]
seems to be happening often in this game session 
target blob -> swamps 
Same experience 

[Info   : Unity Log] skill level: 21.60281
[Info   : Unity Log] skill level: 21.60281
[Info   : Unity Log] skill level: 21.60281
[Info   : Epic Loot] lifesteal 2.729818
[Info   : Unity Log] skill level: 69.83373
[Info   : Unity Log] 04/14/2021 14:17:47: Poison damage: 41.43283 ttl:15.3932 hits:15 dmg perhit:2.762189

[Info   : Epic Loot] lifesteal 3.291174
[Info   : Unity Log] skill level: 69.83373
[Info   : Epic Loot] lifesteal 1.949802
[Info   : Unity Log] skill level: 69.83373
[Info   : Unity Log] [BetterDiscordPresence] Updating Presence!
[Warning: Epic Loot] BountyTarget.OnDeath
[Warning: Epic Loot] SENDING -> RPC_SlayBountyTarget: Blob (target)
[Info   : Epic Loot] Rolling on loot table: Blob (lvl 3), spawned 0 items at drop point((4629.9, 31.0, -997.3)).
[Info   : Unity Log] removing pin for CS__1534903504:16453

**Comment by PatrykJankowski** [comment]
I have a similar issue on the server -> pin doesn't disappear and I can't complete the bounty and can't get a reward.

**Comment by RandyKnapp** [comment]
Just so where clear, everyone here is playing on a server that has EpicLoot installed right? With the latest version?

**Comment by sbtoonz** [comment]
Yes latest avail on nexus since I didn’t know how the zips in git were done
since not on release page

**Comment by sbtoonz** [comment]
I can re validate version on server in a bit but server is running epic
loot along with MCE and the epic loot MCE plug-in

**Comment by nicola-de-smet** [comment]
I can confirm I got this bug on my server too. Everyone got the last update 0.7.6 + MCE + Epic Loot Addon MCE

**Comment by sbtoonz** [comment]
This is resolved in commit b19ef53f304308d57d0c1c41de22e1944511ebfc
