### ISSUE TITLE
[Epic Loot] Localization for a specific language

### ISSUE THREAD

**Issue by 1fr4m3** [RandyKnapp/ValheimMods#136]
**Greetings.**

I am a member of the _Valheim server team_. Your mod is installed on the _server_. The team decided to _translate_ all the names, headings and different meanings into _Russian._ Only managed to rename `translations.json` and `magiceffects.json`. 

I would like to _know if there is a possibility, if so, how?_ Translate the rest of the text into _Russian_ (description of items, craft table, etc.)

**Comment by RandyKnapp** [comment]
Unfortunately I'm just not done with all the translation. It will come soon. Maybe in two weeks.

**Comment by anye77** [comment]
> 不幸的是，我还没有完成所有翻译。它将很快到来。也许两周后。

@RandyKnapp 
Thank you for developing such a good work, but the good thing is to pull your source code to recompile into Chinese, Chinese players like your work very much.

**Comment by anye77** [comment]
@RandyKnapp Thank you for developing such a good work, but the good thing is to pull your source code to recompile into Chinese, Chinese players like your work very much.

**Comment by anye77** [comment]
@RandyKnapp Where can I modify and compile the (Magic) (rare) (EPIC) (legendary) text in the enchant option box? A great writer

**Comment by Ou1Law** [comment]
Pls add also crafting items and Hammer recipe with desc
piece_enchanter
piece_augmenter

ForestToken                            ReagentMagic
IronBountyToken                    ReagentRare
GoldBountyToken                   ReagentRare
RunestoneMagic                     ReagentEpic
RunestoneRare                        ReagentLegendary
RunestoneEpic                        EssenceMagic
RunestoneLegendary              EssenceRare
ShardMagic                             EssenceEpic
ShardRare                               EssenceLegendary
ShardEpic                                LeatherBelt
ShardLegendary                      GoldRubyRing
DustMagic                              SilverRing
DustRare
DustEpic
DustLegendary

Thx for u work its really most interesting mod on this game

PS

1fr4m3 - ребят, а как вы справляетесь с окончаниями?) ну к примеру префикс - Acid(Кислотный)
Кислотный топор - тут все нормально, но как быть с Кислотный копье?) или Кислотный кирка

**Comment by mochen91** [comment]
@anye77  有最新版本的翻译吗？现在 @RandyKnapp 把附魔描述统一在一个translations.json文件里了，但是交互界面和附魔材料的说明没找到在哪儿翻译。因为技术水平太差，对dll文件着实无能为力。😂
