### ISSUE TITLE
[Epic Loot] Fails to decompress assets on *nix servers and causes NRE 

### ISSUE THREAD

**Issue by sbtoonz** [RandyKnapp/ValheimMods#142]
```
[Info : Epic Loot] Added MagicItemEffect: Throwable
[Info : Epic Loot] Added MagicItemEffect: Waterproof
[Info : Epic Loot] Added MagicItemEffect: Paralyze
Failed to decompress data for the AssetBundle 'epicloot'.
(Filename: Line: 450)

NullReferenceException: Object reference not set to an instance of an object
at EpicLoot.EpicLoot.LoadAssets () [0x0000c] in <a3c6f12bd0b24e39bb5fa5b4701c970a>:0
at EpicLoot.EpicLoot.Awake () [0x002de] in <a3c6f12bd0b24e39bb5fa5b4701c970a>:0
UnityEngine.GameObject:Internal_AddComponentWithType(Type)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()

(Filename: <a3c6f12bd0b24e39bb5fa5b4701c970a> Line: 0)
```

**Comment by sbtoonz** [comment]
can you add a valheim.exe run req for the asset injection portion?

**Comment by sbtoonz** [comment]
That was from a zap server

**Comment by sbtoonz** [comment]
```
] INFO [Info   :   BepInEx] Loading [Odinflight 1.1.2]
19.04 14:15:12 [Server] INFO Fallback handler could not load library /valheim_server_Data/Mono//mono/aot-cache/amd64/Odinflight.dll.so
19.04 14:15:12 [Server] INFO [Info   :   BepInEx] Loading [Extended Item Data Framework 1.0.0]
19.04 14:15:12 [Server] INFO Fallback handler could not load library /valheim_server_Data/Mono//mono/aot-cache/amd64/ExtendedItemDataFramework.dll.so
19.04 14:15:12 [Server] INFO Fallback handler could not load library /valheim_server_Data/Mono//mono/aot-cache/amd64/0Harmony20.dll.so
19.04 14:15:12 [Server] INFO [Info   :   BepInEx] Loading [Epic Loot 0.7.6]
19.04 14:15:12 [Server] INFO Fallback handler could not load library /valheim_server_Data/Mono//mono/aot-cache/amd64/EpicLoot.dll.so
19.04 14:15:12 [Server] INFO Fallback handler could not load library /valheim_server_Data/Mono//mono/aot-cache/amd64/fastJSON.dll.so
19.04 14:15:12 [Server] INFO Failed to decompress data for the AssetBundle 'epicloot'. 
19.04 14:15:12 [Server] INFO (Filename:  Line: 450)
19.04 14:15:12 [Server] INFO NullReferenceException: Object reference not set to an instance of an object
19.04 14:15:12 [Server] INFO at EpicLoot.EpicLoot.LoadAssets () [0x0000c] in <a3c6f12bd0b24e39bb5fa5b4701c970a>:0 
19.04 14:15:12 [Server] INFO at EpicLoot.EpicLoot.Awake () [0x002de] in <a3c6f12bd0b24e39bb5fa5b4701c970a>:0 
19.04 14:15:12 [Server] INFO UnityEngine.GameObject:Internal_AddComponentWithType(Type)
19.04 14:15:12 [Server] INFO UnityEngine.GameObject:AddComponent(Type)
19.04 14:15:12 [Server] INFO BepInEx.Bootstrap.Chainloader:Start()
19.04 14:15:12 [Server] INFO UnityEngine.Application:.cctor()
19.04 14:15:12 [Server] INFO (Filename: <a3c6f12bd0b24e39bb5fa5b4701c970a> Line: 0)
19.04 14:15:12 [Server] INFO [Info   :   BepInEx] Loading [Epic Loot Addon - MCE 1.0.2]
19.04 14:15:12 [Server] INFO Fallback handler could not load library /valheim_server_Data/Mono//mono/aot-cache/amd64/EpicLoot-Addon-MCE.dll.so
19.04 14:15:13 [Server] INFO [Info   :   BepInEx] Loading [Equipment and Quic
```

From a shockbyte server

**Comment by j005e** [comment]
`[Info   :   BepInEx] Loading [Epic Loot 0.7.6]
[Error  : Unity Log] Failed to decompress data for the AssetBundle 'epicloot'.
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
EpicLoot.EpicLoot.LoadAssets () (at <a3c6f12bd0b24e39bb5fa5b4701c970a>:0)
EpicLoot.EpicLoot.Awake () (at <a3c6f12bd0b24e39bb5fa5b4701c970a>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()`

Also from a shockbyte server

**Comment by RandyKnapp** [comment]
@sbtoonz @j005e Hey folks, can you try this with your servers? Basically just ftp upload with binary mode on.

https://answers.unity.com/questions/1434541/asset-bundle-failed-to-decompress-data-unity-56-wi.html

**Comment by sbtoonz** [comment]
this does not resolve the issue

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

[VChat] Initialised VChat (2.0.0)
[VChat] VChat (2.0.0) is up to date.
Failed to decompress data for the AssetBundle 'epicloot'.
(Filename: Line: 450)

NullReferenceException: Object reference not set to an instance of an object
at EpicLoot.EpicLoot.LoadAssets () [0x0000c] in <3e5a9b8e14fa49daaff157d511a28377>:0
at EpicLoot.EpicLoot.Awake () [0x002de] in <3e5a9b8e14fa49daaff157d511a28377>:0
UnityEngine.GameObject:Internal_AddComponentWithType(Type)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()

(Filename: <3e5a9b8e14fa49daaff157d511a28377> Line: 0)

**Comment by sbtoonz** [comment]
even doing something like internalizing the asset bundle and streaming the resource doesn't solve the issue

*nix seems to run diff unity than windows

**Comment by sbtoonz** [comment]
https://github.com/sbtoonz/ValheimMods-1/commit/323ffad84bbead3551aa00c4f6ade00b036b4f13

still fails to load prefabs just so you know uploaded as binary

**Comment by sbtoonz** [comment]
https://github.com/RandyKnapp/ValheimMods/pull/144

this seems to resolve the issue @RandyKnapp

**Comment by RandyKnapp** [comment]
I committed a similar change in: b19ef53

**Comment by RandyKnapp** [comment]
Can you confirm that this works?

**Comment by sbtoonz** [comment]
let me pull down changes compile and test

**Comment by sbtoonz** [comment]
b19ef53 resolves 142
