### ISSUE TITLE
https://github.com/RandyKnapp/ValheimMods/blob/main/EpicLoot/EpicLoot.cs#L414

### ISSUE THREAD

**Issue by sbtoonz** [RandyKnapp/ValheimMods#145]
https://github.com/RandyKnapp/ValheimMods/blob/main/EpicLoot/EpicLoot.cs#L414

Why is this unpatchall 

why not unpatchself();

seems scary to be unpatching all on unload

**Comment by RandyKnapp** [comment]
It's unpatchall(pluginid) which is the same as unpatchself

**Comment by sbtoonz** [comment]
Forgive my unity n00bself just saw unpatchall and kind of got scared :-X
