### ISSUE TITLE
[EpicLoot - latest commit] - Not sure if intentional but treasure chests are either impossible to find or far out of radius

### ISSUE THREAD

**Issue by sbtoonz** [RandyKnapp/ValheimMods#146]
attaching server side log and gameplay log 

I found first chest it was quite outside the spawn radius on my map 

second and third chests ... i couldnt find at all 

this is server side log 
[LogOutput.log](https://github.com/RandyKnapp/ValheimMods/files/6388277/LogOutput.log)

this is client side log

[LogOutput.log](https://github.com/RandyKnapp/ValheimMods/files/6388278/LogOutput.log)

**Comment by sbtoonz** [comment]
to be clear I found first chest and had log proof of location of second and third chest spawn but couldnt seem to find it on the map

**Comment by RandyKnapp** [comment]
Please repro the following:
1. In the main menu, open the console and type "debugtm" (with dev commands on, obviously)
2. Start your game
3. View the map, there should be an extra dot on the map by each treasure map location with the exact position including the coordinates
4. Use "goto X Y" with those coordinates to make sure it's really not there
5. Please send me screenshots if the dot is outside the red area, or if there is no dot
6. Also, please send me the resolution at which you are playing the game
