### ISSUE TITLE
Bounties not registering as complete

### ISSUE THREAD

**Issue by WillowMist** [RandyKnapp/ValheimMods#148]
Hello, in the beginning, bounties worked for me, but I think since the very first patch after they were added, I've not been able to complete any.

I'm running Linux, and I have a number of other mods that may be causing an issue.

**Comment by RandyKnapp** [comment]
Did you get the update from today?

**Comment by DarkSir23** [comment]
I did.  I just cleared my existing bounties, took 3 new ones, and had the same problem on each.  The miniboss dies, but it doesn't tell me tat it's complete, and I can't claim the reward.  I also haven't seen any minions since the very first bounty I took

**Comment by trulyzonked** [comment]
I am also experiencing this issue, playing single player. Ran the mod a couple weeks before trying any bounties, enchanted some nice items, then decided to start some bounties. Accepted 6 & completed them all, all worked fine. Scooped up the next batch, & none of these has completed for me after defeating mini-boss. Can't find any minions spawned inside rocks or anything. Tried uninstalling & reinstalling EpicLoot, no change. Running version 0.8.2 of EpicLoot, BepInExPack 5.4.1100, ExtendedItemDataFramework 1.0.2, & r2ModMan 3.1.16. Any assistance would be greatly appreciated!

**Comment by DJShamrock** [comment]
Same issue for me here as well. Issue still persisting where bounty target and minions die but there is no completion/Haldor still shows in progress. Any updates to this? Havent experienced any working bounties yet

**Comment by RandyKnapp** [comment]
Something must be wrong with your install on the server. You have EIDF
installed on the server too? EL latest version on the server? Can you post
your server logs?

You should also try abandoning all your current bounties, bounty targets
have state stored on them and might be bad. For new bounties, this should
work.
