### ISSUE TITLE
[EpicLoot] Conflict with ServersideSimulations - MustHaveCrafted and MustKnowRecipe

### ISSUE THREAD

**Issue by jsza** [RandyKnapp/ValheimMods#150]
ServersideSimulations (of which I'm an author) allows dedicated servers to create and own objects. As EpicLoot [disables item gating](https://github.com/RandyKnapp/ValheimMods/blob/main/EpicLoot/GatedItemType/GatedItemTypeHelper.cs#L51) when `Player.m_localPlayer == null`, `MustHaveCrafted` and `MustKnowRecipe` configuration ceases to function on the dedicated server.

I wrote a patch to facilitate syncing all players' known materials and recipes to the server [here](https://github.com/jsza/ServersideSimulations_EpicLootPatch). Basically it modifies gated item drops to be aware of all players' progress.

Would this make sense to add to EpicLoot itself? I'd be happy to repurpose this as a PR; maybe you have some thoughts?

(and thanks for the mod! it's been lots of fun)

**Comment by RandyKnapp** [comment]
Ah thanks for reaching out. Yeah a PR would be great, then it can just work the right way.
