### ISSUE TITLE
[EquipmentAndQuickSlots] Autopickup over the weight limit

### ISSUE THREAD

**Issue by miamistarz** [RandyKnapp/ValheimMods#153]
**Mod:** Equipment And Quick Slots
**Version:** 2.0.4 / 2.0.5

**Actual result:**
If character is naked you can autopickup till the 300/300 limit, but if you get some gear you o'over' limit is being added for each piece of gear you wear. For example if you wear the helmet with weight=10 you can pickup up to 310/300 so it makes you instantly overweight with debuff. It is really annoying when you're just around the limits, running out from monster and autpickup some trash from the ground getting overweight.

**Expected result:**
Can't autopickup over the weight limit.

**Video with details:** http://somup.com/crfuQqFtwW

**Comment by SuntooX** [comment]
What mod-combination are you running or was this a fresh install?

**Comment by Lime18** [comment]
The conflict is with World of Valheim - Zones, can I fix it?

**Comment by RandyKnapp** [comment]
Fixed in d6ce64a

**Comment by virtualbjorn** [comment]
Looking forward for the release.
