### ISSUE TITLE
[EpicLoot] Requests/Tweaks

### ISSUE THREAD

**Issue by virtualbjorn** [RandyKnapp/ValheimMods#157]
I love the mod and it gave the game a new experience for me. The server I support and partially manage is having issues with people getting padded gear even before Moder is killed.

So my request are the following:
- Trader to only sell treasure maps after a certain tier boss is killed. E.g Black Forest Treasure Maps only available once Eikthyr is killed and so on.
- Treasure Chests in dungeons to only show unlocked items once a boss before that biome is killed, kinda the same with the first request. E.g Burial Chamber chests having antler pickaxes shouldn't be available until Eikthyr is killed.
- Additional config for mob loot, mobs will only drop loot for the current world tier level, after Eikthyr is killed, higher tier mobs will only drop Black Forest tier gear.
- Ability to upgrade or reroll enchanted item with new set of enchants.
- Ability to reskin shields, maybe on the workbench since the Forge is already full of tabs.

**Comment by Felger** [comment]
Suggestion on the final bullet - Randomize the shield skin when dropped, I think this would be a viable alternative to being able to reskin (and maybe easier to implement).
