### ISSUE TITLE
No Boss Trophies in Single Player mode

### ISSUE THREAD

**Issue by rchardb** [RandyKnapp/ValheimMods#158]
Boss trophies are not dropping in single player mode on local server in version 7.7
Reverting to 7.6 resolves issue

**Comment by RandyKnapp** [comment]
Hey there, I need some more information. What setting do you have set in the config for "Boss Trophy Drop Mode" and "Boss Trophy Drop Player Range"?

**Comment by RandyKnapp** [comment]
Fixed in 0.7.8
