### ISSUE TITLE
Feature request: Don't show estimated count for stuff that has no requirements

### ISSUE THREAD

**Issue by ignamiranda** [RandyKnapp/ValheimMods#16]
Using the hoe set to Level Ground or Pathen shows (2147483647) next to it since both actions have no resource cost. It'd be cool if it didn't show anything or instead showed (∞).

**Comment by RandyKnapp** [comment]
This is fixed in ImprovedBuildHud version 1.0.3

**Comment by ignamiranda** [comment]
I'm using the latest version and I still have it
![image](https://user-images.githubusercontent.com/34501347/111000371-ee623280-834f-11eb-8401-b765b518ff17.png)
