### ISSUE TITLE
ValheimPlus Compatibility

### ISSUE THREAD

**Issue by Fundryi** [RandyKnapp/ValheimMods#17]
Hi it seems that it's not compatible with the new ValheimPlus 0.9.2 release.
They added an option to increase the "Rows" in the inventory and now the button is kinda in them middle of the inventory.

Can this be fixed?

Image: https://i.imgur.com/ijCqOUj.png

Regards

**Comment by RandyKnapp** [comment]
I can look into it. I'm planning an overhaul of how that mod works under
the hood.
