### ISSUE TITLE
[Epic Loot] Localization bugs and offers

### ISSUE THREAD

**Issue by Ou1Law** [RandyKnapp/ValheimMods#187]
Pls add craftable items and Hammer recipe with desc in translation.json

list:
recipe for craft augmenter and enchanter
ForestToken
IronBountyToken
GoldBountyToken
Runestone
Reagent
Essence
Shard 
Dust
LeatherBelt
SilverRing
GoldRubyRing

**Comment by Ou1Law** [comment]
translation problem with Andvaranaut https://imgur.com/fCEVYps
  "mod_epicloot_item_andvaranaut": "any_text",                         doesn't work
  "mod_epicloot_item_andvaranaut_tooltip": "any_text",             doesn't work
  "mod_epicloot_item_andvaranaut_startmsg": "any_text",         doesn't work
  "mod_epicloot_item_andvaranaut_type":  "any_text"                only that works

**Comment by Ou1Law** [comment]
translation problem with bounties status
https://imgur.com/s1c5jZ8 in quest description all ok, but on the quest board...

**Comment by Ou1Law** [comment]
magiceffects.json typo must be       "DisplayText": "mod_epicloot_me_andvaranaut_display",

32       "DisplayText": "Finds Haldor's treasure chests",

**Comment by RandyKnapp** [comment]
Hey, thanks for the feedback. I will get to this when I can, but I'm simply not done with translations yet.

**Comment by Ou1Law** [comment]
Thx for answer, and u can use my translation on the nexus page
https://github.com/Ou1Law/Translation-into-Russian-mod-EpicLoot-for-Valheim
