### ISSUE TITLE
[???] Feature Request: Reverse container item removal

### ISSUE THREAD

**Issue by Qrylor** [RandyKnapp/ValheimMods#19]
If easy to implement, add an option to remove items from chests in revers automatic input order.  
Every-time I open a sorted chest (left to right), the partial or lack of stacks in the first positions (using default stack insertion into the chest) keeps causing OCD issues.

Appreciation of the continued mod support.

**Comment by RandyKnapp** [comment]
What mod are you specifically requesting this feature for?

**Comment by Qrylor** [comment]
The requested change was for the mod: CraftingWithContainers [#17](https://github.com/abearcodes/Valheim/issues/17).  I had multiple GitHub tabs open and accidentally created it under your mods.  Upon realizing my mistake, I went to delete this thread but you had already accepted / commented.  Since I was unsure if you were thinking of something else decided to leave alone.

Sorry for the delay to your request for additional information.
