### ISSUE TITLE
[EpicLoot - Suggestion] Weightless Enchant

### ISSUE THREAD

**Issue by virtualbjorn** [RandyKnapp/ValheimMods#191]
Weightless items doesn't necessarily mean no movement speed penalty. e.g a weightless tall shield instead of 20% MSP maybe about 10-15% MSP.

Is it possible to add an effect for the weightless enchant maybe a minor movement speed penalty reduction?

**Comment by DiskImage** [comment]
Given the fact that your movement speed remains static form 0 to equal to your max carry, I'm guessing that the movement speed reduction is meant to model the bulkiness and awkwardness of moving with that item in use, possibly?

**Comment by Digitalroot** [comment]
If you are not already aware "Weightless" means you can carry more before becoming encumbered. Also if you are not already aware there are also +%MSP Affixes. To me these are two different affixes providing two different enhancements. If I want both on a single item, it is going to cost me two affixes slots, so I have to give up a affix that could provide another enhancement.  

Assuming that I only care about getting these two enhancements and do not care about any others. There is a nice crafting game play loop in trying to craft both onto a single item.
