### ISSUE TITLE
EpicLoot error with Jotunn/WoVSSC 

### ISSUE THREAD

**Issue by waren27** [RandyKnapp/ValheimMods#193]
Getting this error when attempting to run with Jotunn/WoVSSC: got stucked at loading screen. any solution for this one? TIA

﻿[Info   :   Console] WoV - SSC: Attempting to load character...
[Info   :Jotunn.Managers.SkillManager] ---- Registering custom skills ----
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
EpicLoot.PlayerExtensions.GetEquipment (Player player) (at <47903a7734814c9cac3d90c70942e46c>:0)
EpicLoot.PlayerExtensions.GetMagicEquipmentWithEffect (Player player, System.String effectType) (at <47903a7734814c9cac3d90c70942e46c>:0)
EpicLoot.PlayerExtensions.HasMagicEquipmentWithEffect (Player player, System.String effectType) (at <47903a7734814c9cac3d90c70942e46c>:0)
EpicLoot.MagicItemEffects.FreeBuildGuiDisplay_Recipe_GetRequiredStation_Patch.Prefix (CraftingStation& __state, Piece piece) (at <47903a7734814c9cac3d90c70942e46c>:0)
(wrapper dynamic-method) Player.DMD<Player::HaveRequirements>(Player,Piece,Player/RequirementMode)
Player.UpdateKnownRecipesList () (at <64e3050735a54dbb8762d6e3432a1162>:0)
Jotunn.Managers.ItemManager.ReloadKnownRecipes (On.Player+orig_Load orig, Player self, ZPackage pkg) (at <7e57548adeb74455abd73263b16b16bf>:0)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<Player::Load>?743001216(Player,ZPackage)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<Player::Load>?-919955456(Player,ZPackage)
Jotunn.Managers.PieceManager.ReloadKnownRecipes (On.Player+orig_Load orig, Player self, ZPackage pkg) (at <7e57548adeb74455abd73263b16b16bf>:0)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<Player::Load>?1716632832(Player,ZPackage)
(wrapper dynamic-method) PlayerProfile.DMD<PlayerProfile::LoadPlayerData>(PlayerProfile,Player)
WorldofValheimServerSideCharacters.LoadCharacter.Game__UpdateRespawn (Game __instance) (at <37f4d19c90c843bb81fbf97bf5ab7f92>:0)
(wrapper dynamic-method) Game.DMD<Game::UpdateRespawn>(Game,single)
Game.FixedUpdate () (at <64e3050735a54dbb8762d6e3432a1162>:0)

**Comment by DiskImage** [comment]
This may just be related to the patch update today? I don't use WoVSSC, but I do have mods depending on Jotunn, and I'm experiencing almost an identical issue. Loading either my survival or creative characters produces the following, in loop:

```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Player.UpdateKnownRecipesList () (at <fda64833b4b74020987bc5f624178286>:0)
Jotunn.Managers.ItemManager.ReloadKnownRecipes (On.Player+orig_Load orig, Player self, ZPackage pkg) (at <19195d8f8fb94345934f4d86dbeaab94>:0)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<Player::Load>?-1012315008(Player,ZPackage)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<Player::Load>?1462506496(Player,ZPackage)
Jotunn.Managers.PieceManager.ReloadKnownRecipes (On.Player+orig_Load orig, Player self, ZPackage pkg) (at <19195d8f8fb94345934f4d86dbeaab94>:0)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<Player::Load>?855617024(Player,ZPackage)
PlayerProfile.LoadPlayerData (Player player) (at <fda64833b4b74020987bc5f624178286>:0)
(wrapper dynamic-method) Game.DMD<Game::SpawnPlayer>(Game,UnityEngine.Vector3)
(wrapper dynamic-method) Game.DMD<Game::UpdateRespawn>(Game,single)
Game.FixedUpdate () (at <fda64833b4b74020987bc5f624178286>:0)
```

If I log out of my character instead of quitting Valheim, it takes me to a charactyer selection screen for "RAGNAR", but no character is shown. (I used names from Irish legends, like "Cú Chulainn", not "RAGNAR")
Clicking character right yields this error while left takes me back to the real list of characters, minus RAGNAR:
```

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
FejdStartup.OnCharacterRight () (at <fda64833b4b74020987bc5f624178286>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <30e538f3cf5548cfa6abc9730778bcef>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <30e538f3cf5548cfa6abc9730778bcef>:0)
UnityEngine.UI.Button.Press () (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.EventSystems.EventSystem:Update()
```

From here, if I try to log back into that character/world:
```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
EpicLoot.EpicLoot+<>c.<TryRegisterItems>b__62_0 (UnityEngine.GameObject x) (at <47903a7734814c9cac3d90c70942e46c>:0)
System.Linq.Enumerable+WhereSelectListIterator`2[TSource,TResult].MoveNext () (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Collections.Generic.List`1[T].InsertRange (System.Int32 index, System.Collections.Generic.IEnumerable`1[T] collection) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Collections.Generic.List`1[T].AddRange (System.Collections.Generic.IEnumerable`1[T] collection) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
EpicLoot.EpicLoot.TryRegisterItems () (at <47903a7734814c9cac3d90c70942e46c>:0)
EpicLoot.ObjectDB_Awake_Patch.Postfix () (at <47903a7734814c9cac3d90c70942e46c>:0)
(wrapper dynamic-method) ObjectDB.DMD<ObjectDB::Awake>(ObjectDB)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<ObjectDB::Awake>?1693347840(ObjectDB)
Jotunn.Managers.ItemManager.RegisterCustomData (On.ObjectDB+orig_Awake orig, ObjectDB self) (at <19195d8f8fb94345934f4d86dbeaab94>:0)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<ObjectDB::Awake>?1557533696(ObjectDB)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<ObjectDB::Awake>?984950784(ObjectDB)
Jotunn.Managers.PieceManager.RegisterCustomData (On.ObjectDB+orig_Awake orig, ObjectDB self) (at <19195d8f8fb94345934f4d86dbeaab94>:0)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<ObjectDB::Awake>?596619904(ObjectDB)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<ObjectDB::Awake>?-1943407616(ObjectDB)
Jotunn.Managers.MockManager.RemoveMockPrefabs (On.ObjectDB+orig_Awake orig, ObjectDB self) (at <19195d8f8fb94345934f4d86dbeaab94>:0)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<ObjectDB::Awake>?-181635712(ObjectDB)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<ObjectDB::Awake>?-570470400(ObjectDB)
Jotunn.Managers.ItemManager.InvokeOnItemsRegistered (On.ObjectDB+orig_Awake orig, ObjectDB self) (at <19195d8f8fb94345934f4d86dbeaab94>:0)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<ObjectDB::Awake>?865856256(ObjectDB)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<ObjectDB::Awake>?-74996736(ObjectDB)
Jotunn.Managers.PieceManager.InvokeOnPiecesRegistered (On.ObjectDB+orig_Awake orig, ObjectDB self) (at <19195d8f8fb94345934f4d86dbeaab94>:0)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<ObjectDB::Awake>?-526476928(ObjectDB)
```



My Creative mode char has all legendary items, I think? The green default rarity. My survival has some Rare (? the yellow default).
