### ISSUE TITLE
Pressing 8 unequips utility

### ISSUE THREAD

**Issue by Coffee4cr** [RandyKnapp/ValheimMods#20]
Each time I press 8,it unequips my utility slots instead of what ever is in my 8 slot

**Comment by sergeayotte** [comment]
Although I did not have any utility, the button 8 does not do anything.
When trying to find which mod was the culprit and I renamed your DLL to OLD, I lost all the armor I had and the food I had in the CVB keys :( 
I renamed your mod to get it working again, and same result, i.e. nothing happens with 8 and lost armors and food.

**Comment by RandyKnapp** [comment]
Ah yeah, got a fix incoming.

**Comment by RandyKnapp** [comment]
Fixed in 1.0.5

**Comment by sergeayotte** [comment]
Good Saturday Randy!

 

Thank you very much for your fast update and great add-on!!

 

Serge Ayotte
