### ISSUE TITLE
[EpicLoot] Translation 0.7.10

### ISSUE THREAD

**Issue by Ou1Law** [RandyKnapp/ValheimMods#208]
Duplicates the Active magic effects tab due to lack of translation
Doesn't display the numeric value of the magician effect on the active tab
Still adds "of" before rare item suffix.

https://imgur.com/pOrdqjv           eng version EpicLoot with standard localization
https://imgur.com/a/0KXinye        rus version  EpicLoot with standard localization

**Comment by KillFacePT** [comment]
It's possible to make a portuguese translation I'll be willing to help with it
