### ISSUE TITLE
[EpicLoot] Can't disable certain effect types in magiceffects.json

### ISSUE THREAD

**Issue by mparsakia** [RandyKnapp/ValheimMods#219]
Hey,

I am trying to disable certain effect types and change their values in magiceffects.json for my own playthrough. I read the documentation and it stated if AllowedItemTypes array is empty the item is not allowed to roll, and also items in the ExcludedItemTypes list would not be allowed to roll. So I set that up, but in-game the items are still rolling these effects.

Code / picture: https://i.imgur.com/4yj6Xxd.png

`    {
      "Type": "AddCarryWeight",
      "DisplayText": "$mod_epicloot_me_addcarryweight_display",
      "Requirements": {
        "AllowedItemTypes": [],
        "ExcludedItemTypes": [
          "Helmet",
          "Chest",
          "Legs",
          "Shoulder",
          "Utility",
          "Bow",
          "OneHandedWeapon",
          "TwoHandedWeapon",
          "Shield",
          "Torch",
          "Tool"
        ]
      },
      "ValuesPerRarity": {
        "Magic": { "MinValue": 200, "MaxValue": 200, "Increment": 1 },
        "Rare": { "MinValue": 200, "MaxValue": 200, "Increment": 1 },
        "Epic": { "MinValue": 200, "MaxValue": 200, "Increment": 1 },
        "Legendary": { "MinValue": 200, "MaxValue": 200, "Increment": 1 }
      },
      "SelectionWeight": 1,
      "Prefixes": ["$mod_epicloot_me_addcarryweight_prefix1"],
      "Suffixes": ["$mod_epicloot_me_addcarryweight_suffix1"]
    },`

Still is rolling on bows, and probably other items but I only checked on bows.

This maybe a potential bug, or I am doing something incorrect?

Thanks, Mike

**Comment by RandyKnapp** [comment]
The best way to make it not roll is add this to the Requirements:
`"NoRoll" : true`

**Comment by mparsakia** [comment]
@RandyKnapp  Ah! Thank you. I did try to find what that meant in the info.md file, I misinterpreted "NoRoll" as in "It's like a boolean, like poison resist item".
