### ISSUE TITLE
EpicLoot? EAQS?

### ISSUE THREAD

**Issue by Ou1Law** [RandyKnapp/ValheimMods#224]
Fixing bugs the EAQS tombstone takes a lot of time))) And constant updates of BetterArchery and V+ don't help this. Although in fact this mod simply adds 8 slots... and there are many such mods.
And Epic Loot is unique... You haven't abandoned it?)

**Comment by RandyKnapp** [comment]
What are you talking about? This is a bug report place. Not a discussion forum.
