### ISSUE TITLE
[Jam] Question - how could I change the health/stamina/etc values?

### ISSUE THREAD

**Issue by mparsakia** [RandyKnapp/ValheimMods#225]
Hey! I was just wondering how I could do this, or if someone could point me in the right direction. I know it's not possible in the JSON file, but I don't mind doing some coding to get the values I would like. Thanks

**Comment by ZekeDP** [comment]
You will need Unity for that and edit the one on the picture.
![image](https://user-images.githubusercontent.com/59428430/119202270-00d0b900-bac3-11eb-9c15-fd303a0c6e8c.png)

1.) Fork this repo
2.) Clone
3.) Open Unity
4.) Add project "ValheimMods\ValheimUnity"
5.) Assets\Jam\Prefabs\{Jams to Edit}
6.) Mod -> Build Asset Bundle
7.) Compile the Jam from Visual Studio Code
8.) Put the newly created .dll file and enjoy

**Comment by RandyKnapp** [comment]
Thanks for pointing them in the right direction, @ZekeDP !

**Comment by mparsakia** [comment]
Ah, so I tried to build after changing in Unity, got some errors about references. Resolved a bunch of them, but I'm still missing "assembly_utils_publicized" & "assembly_valheim_publicized", how could I get these?

**Comment by RandyKnapp** [comment]
This plugin: https://github.com/MrPurple6411/Bepinex-Tools/tree/main/Bepinex-Publicizer
Install, run the game once, and it will generate the publicized dlls
