### ISSUE TITLE
Configurate Magic Effects, remove Waterwalk

### ISSUE THREAD

**Issue by jaahnie** [RandyKnapp/ValheimMods#227]
Hello there!
First of all, i really do enjoy the epic loot mod! Thanks a lot for this. But, at least in my opinion, i feel like the magic effect of "waterwalking" on armor is op and i would simply like to remove it from the list of possible enchantments. On thunderstore (or nexusmods) is a TODO list, which says "[X] Configurable magic effects". Can you or somebody help me with the configuration please?
Thank you guys a lot! Greetings

**Comment by RandyKnapp** [comment]
In `magiceffects.json` line 1611 ([here](https://github.com/RandyKnapp/ValheimMods/blob/e2ae49f5d7c3c20b1187046e74d276f1cc79a275/EpicLoot/magiceffects.json#L1611)), add a line inside the "Requirements" block that looks like:
```json
"NoRoll": true,
```
