### ISSUE TITLE
Water Walking Vector Issue

### ISSUE THREAD

**Issue by C4RP3N0CT3M** [RandyKnapp/ValheimMods#233]
I'm not sure what causes it, but occasionally when walking on water I lose the ability to walk forward. I can move side to side awkwardly, and walking on land fixes the issue for the next water walk.

**Comment by RandyKnapp** [comment]
Thanks for the feedback, waterwalking is a huge hack that I'm surprised works at all, sometimes. But I'll keep investigating.

**Comment by C4RP3N0CT3M** [comment]
No worries, I'm digging your mod SOOO much.

**Comment by sbtoonz** [comment]
protip just jump when this happens 
it happens to me when waves go over X height on player if the water is semi calm this works fine

**Comment by 4Magma** [comment]
its mostly occurs when i jump from above on the water, 
like rocks, boats

**Comment by gsxryan** [comment]
Water walking seem to completely kill FPS in game as well - from 70fps to about 3fps when wearing them.
