### ISSUE TITLE
[EpicLoot] NullRefrenceException when creature level is non-linear in loottables

### ISSUE THREAD

**Issue by AllTheNamesWereTaken-EvenThisOne** [RandyKnapp/ValheimMods#236]
So i use up to lv 100 creatures. Prior the latest update, i was able to define level "groups" in the config by leaving gaps in the levels. For example i would have level 1, 6, 20, 30, 40, 50, 60, 70, 80, 90, 100 defined without the numbers in between. This would cause epic loot to assign loot based on the lowest closest number. For example, i had level 20 then 30 defined. A level 27 mob would drop whatever was in the level 20 config. A lv59 would drop what is set in lv50 and so on.

With the latest update, i am no longer to do this as it throws a NullRefrenceException. I have to define every single level , so that's 100 entries per creature. I went ahead and did this for all vanilla, DoOrDie and Monsternomicon creatures. The result is a file that is too large to send and causes disconnection when connecting to the server ( Assertion Failed: Message size 2069096 is too big.  Max is 524288)

Is it possible to have the loot table behavior reverted to how it functioned in 7.9?

You can recreate this bug by simply leaving a level gap (eg lv3->lv5) or if you only define lv1 (testing shows you need at least levels 1-2-3 defined)

**Comment by RandyKnapp** [comment]
Was this on startup it would throw this error? Do you have the error printout?

**Comment by RandyKnapp** [comment]
Fixed in 740803b
