### ISSUE TITLE
Info.MD needs explanations of some effects

### ISSUE THREAD

**Issue by patrick-visniewski** [RandyKnapp/ValheimMods#238]
Just 2 examples.
Duelist and Opportunist.
What do these effects do?

Though really most of the effects are pretty self explanatory to an English speaker so it probably explains this.

The info.md lists them and just that their prefix or suffix is basically the name of the effect and nothing.
Can we please get explanations of each effect added to the info.md

looking at info.md it looks like it is actually generated from the corresponding JSON file. So it would basically just need an extra optional field for each effect that includes a description.
And ideally if possible when you hover over an effect on an item it would have some hover text displaying that explanation if it is present.

so duelist... I have no idea what it might do? better parry?
opportunist I want to say has something to do with being able to backstab from the "front" maybe?

**Comment by RandyKnapp** [comment]
info.md is a little out of date. However, in-game in the compendium there is an explanation of what every magic effect does in more detail.

**Comment by patrick-visniewski** [comment]
good point I forgot there was even an ingame compendium. thanks
