### ISSUE TITLE
Mod doesn't work.

### ISSUE THREAD

**Issue by Tyguy7** [RandyKnapp/ValheimMods#239]
I have BepInEx 5.4.11 installed, and the only installed mod is Epic Loot.  Valheim launches successfully and the BepInEx overlay reports that 1 plugin is enabled.  I open the console and enable cheats by typing "devcommands" (imacheater has been deprecated).  After cheats are enabled I try commands such as `magicitem`, `magicitem epic random 1`, and other combinations, as well as `magicmats`, and nothing happens.  I've also tried spawning many elite enemies and killing them multiple times to see if any magic items appear and none do.

**Comment by Digitalroot** [comment]
Any clues in "Valheim\BepInEx\LogOutput.log"?

**Comment by Tyguy7** [comment]
[Error  :   BepInEx] Could not load [Epic Loot 0.7.10] because it has missing dependencies: randyknapp.mods.extendeditemdataframework
