### ISSUE TITLE
Bounties not completing on dedicated server

### ISSUE THREAD

**Issue by LukeAremac** [RandyKnapp/ValheimMods#240]
I play with my kids and first off, mod is fantastic. Everything works except one thing on the dedicated server. We can get bounties, go and kill the named mob, but it doesn't complete. In single player it works correctly.

Notes:
- Dedicated server is set up on one of the player's computers using Steam's Dedicated server
- That same player also plays on the server and can't complete either (obviously)
- I have tried other fixes I have seen and none have worked.
- We are using the latest version on server and clients

Any suggestions or potential fixes would be welcome.

**Comment by RandyKnapp** [comment]
Does the dedicated server have both the latest EpicLoot AND Extended Item Data Framework installed?

**Comment by LukeAremac** [comment]
Yes, all computers have identical mods installed:
- Epic Loot
- Item Data Framework
- Creature Level Control
- Plant Everything
- Configuration Manager
- Cooking Skill
- Equipement And Quick Slots
- Fitness Skill
- More Slots
- Skill Injector
- Skills give more carry weight

I didn't think any of the skill mods would be affecting it, as it does work in SP (on the server computer and others), just not when on the dedicated server.

**Comment by sramji** [comment]
This mod is amazing, and a huge improvement to the replay value for Valheim. Thank you!

I can confirm @LukeAremac 's report for dedicated servers (hosted at PingPerfect).  Every other element of the mod works perfectly, but bounty kills never register.  

The issue is 100% reproducible, and it doesn't seem to matter whether the player holding the bounty kills the target or if another player does - there is no completion.

I've looked through the code and I think I understand it.  At a cursory level it seems the OnDeath() or RPC_SlayBountyTarget() is not firing, so BountiesAdventureFeature.OnBountyTargetSlain() is not called. The server doesn't write logs; if there is a setting for this I'm happy to follow instructions and provide them.

Thanks for the mod, and let me know if I can be helpful with debugging.

**Comment by jasondenney** [comment]
I was running into the same issue.

I finally got the Bounty Vanquished message and was able to turn it in by doing this on the dedicated server:

randyknapp.mods.epicloog.cfg
`[Config Sync]

## [Server Only] The configuration is locked and may not be changed by clients once it has been synced from the server. Only valid for server config, will have no effect on clients.
# Setting type: Boolean
# Default value: false
Lock Config = true

[Logging]

## Enable logging
# Setting type: Boolean
# Default value: false
Logging Enabled = true
`

randyknapp.mods.extendeditemdataframework.cfg
`## Enables log output from the mod.
# Setting type: Boolean
# Default value: false
Logging Enabled = true
`

I then attempted with Logging back to false and wasn't getting the Bounty spawns.  Reenabled logging, restarted my server, then reconnected and 2nd bounty completed.

@RandyKnapp does this settings need to be on for the clients to be registered to receive the bounty events?
If so, sounds like just an update to the README.md would solve a lot of peoples issue for dedicated servers.

**Comment by Digitalroot** [comment]
See #284

**Comment by darksinthe** [comment]
> I was running into the same issue.
> 
> I finally got the Bounty Vanquished message and was able to turn it in by doing this on the dedicated server:
> 
> randyknapp.mods.epicloog.cfg [Config Sync]
> 
> ## [Server Only] The configuration is locked and may not be changed by clients once it has been synced from the server. Only valid for server config, will have no effect on clients.
> # Setting type: Boolean
> # Default value: false
> Lock Config = true
> 
> [Logging]
> 
> ## Enable logging
> # Setting type: Boolean
> # Default value: false
> Logging Enabled = true
> 
> randyknapp.mods.extendeditemdataframework.cfg
> 
> ## Enables log output from the mod.
> # Setting type: Boolean
> # Default value: false
> Logging Enabled = true
> 
> I then attempted with Logging back to false and wasn't getting the Bounty spawns. Reenabled logging, restarted my server, then reconnected and 2nd bounty completed.
> 
> @RandyKnapp does this settings need to be on for the clients to be registered to receive the bounty events? If so, sounds like just an update to the README.md would solve a lot of peoples issue for dedicated servers.

Where do I find these config files on my dedicated server? they arent in bepinex/plugins/config on my ftp server but i do have epic loot installed. Im getting the same issue with the bounties where it wont ever show vanquished. And will I need to make the same edits to all players config files that play on the server too?

**Comment by Digitalroot** [comment]
> > I was running into the same issue.
> > I finally got the Bounty Vanquished message and was able to turn it in by doing this on the dedicated server:
> > randyknapp.mods.epicloog.cfg [Config Sync]
> > ## [Server Only] The configuration is locked and may not be changed by clients once it has been synced from the server. Only valid for server config, will have no effect on clients.
> > # Setting type: Boolean
> > # Default value: false
> > Lock Config = true
> > [Logging]
> > ## Enable logging
> > # Setting type: Boolean
> > # Default value: false
> > Logging Enabled = true
> > randyknapp.mods.extendeditemdataframework.cfg
> > ## Enables log output from the mod.
> > # Setting type: Boolean
> > # Default value: false
> > Logging Enabled = true
> > I then attempted with Logging back to false and wasn't getting the Bounty spawns. Reenabled logging, restarted my server, then reconnected and 2nd bounty completed.
> > @RandyKnapp does this settings need to be on for the clients to be registered to receive the bounty events? If so, sounds like just an update to the README.md would solve a lot of peoples issue for dedicated servers.
> 
> Where do I find these config files on my dedicated server? they arent in bepinex/plugins/config on my ftp server but i do have epic loot installed. Im getting the same issue with the bounties where it wont ever show vanquished. And will I need to make the same edits to all players config files that play on the server too?

Look in `\BepInEx\plugins\EpicLoot`

**Comment by darksinthe** [comment]
> > Where do I find these config files on my dedicated server? they arent in bepinex/plugins/config on my ftp server but i do have epic loot installed. Im getting the same issue with the bounties where it wont ever show vanquished. And will I need to make the same edits to all players config files that play on the server too?
> 
> Look in `\BepInEx\plugins\EpicLoot`
 On my server in the \BepInEx\plugins\EpicLoot all its showing even with hidden files visible;  translations, recipes, magiceffects, lootables, legendaries, itemnames, iteminfo, enchantcosts, adventuredata, abilities (.JSON files) and EpicLoot.dll
 
 No cfg files anywhere :( do i need something to extract the DLL or something to get to the cfg files?

**Comment by darksinthe** [comment]
the files arent on my gportal dedicated server in bepinex/plugins/epicloot
, and they arent in bepinex/config (where they are on my own PC). I edited
the ones on my pc as stated above, and tried uploading those 2 files to
bepinex/plugins/epicloot and it didnt work, and i tried uploading them to
bepinex/config and it didnt work :( i restarted the server in between each
go. still not getting vanquished updates. made sure to kill all minions;
still no vanquished. :( very frustrating. not sure what to do now

**Comment by RandyKnapp** [comment]
So it sounds like you don't have Epic Loot installed correctly on the server. You need to install it on the server the same way you would install it on the client: with both the .dll file and all the .json files in a folder called EpicLoot in the BepInEx/plugins folder.

Once it is running correctly, then the config file in BepInEx/config will appear and you can set the settings from the fix above.

Good luck.

**Comment by sramji** [comment]
On dedicated servers running at 3rd party hosts, the Valheim user may not
have write access to create the log files. In this case Epic Loot can’t
work.

We had to troubleshoot this on our hosted server, and ended up switching
providers so we could get control of the permissions. Once you add write
access then Epic Loot Bounties work flawlessly.

Hope this helps someone!

*Sam* Ramji | ***@***.*** | +1-510-913-6495

Sent via Superhuman iOS ***@***.***>

**Comment by mattklouda** [comment]
> On dedicated servers running at 3rd party hosts, the Valheim user may not have write access to create the log files. In this case Epic Loot can’t work. We had to troubleshoot this on our hosted server, and ended up switching providers so we could get control of the permissions. Once you add write access then Epic Loot Bounties work flawlessly. Hope this helps someone!

I'm running a dedicated server (njordmenu.sh, awesome installer script) on a VM in my house. Bounties do NOT work. I went so far as to set recursive permissions to 755 on the /home/steam/valheimserver/<worldname> directory, and owner is steam:steam. What am I missing? I've never once seen a bounty show up in which we can attempt to complete.

**Comment by Digitalroot** [comment]
> > On dedicated servers running at 3rd party hosts, the Valheim user may not have write access to create the log files. In this case Epic Loot can’t work. We had to troubleshoot this on our hosted server, and ended up switching providers so we could get control of the permissions. Once you add write access then Epic Loot Bounties work flawlessly. Hope this helps someone!
> 
> I'm running a dedicated server (njordmenu.sh, awesome installer script) on a VM in my house. Bounties do NOT work. I went so far as to set recursive permissions to 755 on the /home/steam/valheimserver/ directory, and owner is steam:steam. What am I missing? I've never once seen a bounty show up in which we can attempt to complete.

I suggest enabling and posting your logs from the server.

**Comment by mattklouda** [comment]
> > > On dedicated servers running at 3rd party hosts, the Valheim user may not have write access to create the log files. In this case Epic Loot can’t work. We had to troubleshoot this on our hosted server, and ended up switching providers so we could get control of the permissions. Once you add write access then Epic Loot Bounties work flawlessly. Hope this helps someone!
> > 
> > 
> > I'm running a dedicated server (njordmenu.sh, awesome installer script) on a VM in my house. Bounties do NOT work. I went so far as to set recursive permissions to 755 on the /home/steam/valheimserver/ directory, and owner is steam:steam. What am I missing? I've never once seen a bounty show up in which we can attempt to complete.
> 
> I suggest enabling and posting your logs from the server.

Which logs? Valheim specific, system? I enabled logging, so let me see if I can dig them up.

**Comment by mattklouda** [comment]
Here is the BepInEx LogOutput log
[LogOutput.log](https://github.com/RandyKnapp/ValheimMods/files/7899364/LogOutput.log)
.

**Comment by Digitalroot** [comment]
> Adding context - I am digging through syslog from yesterday, and prior to and after the service restart, these messages are plentiful. Jan 18 23:30:54 hellheim start_valw_bepinex.sh[7459]: Fallback handler could not load library /home/steam/valheimserver/hellheim/valheim_server_Data/Mono/data-0x55804e976190.so
> 
> Permissions?

This is normal.

**Comment by mattklouda** [comment]
Ok - what other logs would you like me to pull?

**Comment by Digitalroot** [comment]
I do not see any error in that log. Try getting a bounty and try to complete it. When it "fails" upload both the server and client logs.

**Comment by mattklouda** [comment]
That's part of the issue...the opportunity to get a bounty is non existent. So I can't even test what's not available.

**Comment by mattklouda** [comment]
Ignore me - we haven't found the vendor yet. So I'm off base here. Thanks for the insight.
