### ISSUE TITLE
create add object list_mobs in file loottables.js

### ISSUE THREAD

**Issue by secrectvn** [RandyKnapp/ValheimMods#248]
Hello Randy,
i find it great if there is a list of CREATURES ( Mobslist) in Loottables, it's similar to ItemSets ). it will be more convenient in game play editing.
For example, I want to increase the difficulty of the game, only drop materials and increase the rarity of legendary materials, editing the file is very time consuming.

Thanks Randy

**Comment by RandyKnapp** [comment]
Thanks, this pull request will do something similar, but I'm waiting for the author to create a version I can merge: https://github.com/RandyKnapp/ValheimMods/pull/186

**Comment by RandyKnapp** [comment]
Fixed in #186
