### ISSUE TITLE
Bounties Not Having Bounty Enemies

### ISSUE THREAD

**Issue by Dquattz** [RandyKnapp/ValheimMods#254]
Hi, I've had 3 bounties (2 I'm 100% sure are older) Lose the Boss name for the monster and they just become a 2 star enemy with no AI to attack. 
They just walk around aimlessly and the bounty doesn't complete after killing them as they lost their title.
I'm not sure if it will spawn a new Bounty enemy after a bit or not or if I just need to abandon it. 
Will possibly post an update about this when I go back after a few in game days or so.
I'm not sure if the latest update has anything to do with it or not.

**Comment by Dquattz** [comment]
Update: I've noticed that the bounties that don't offer the coins in addition to the tokens seem to be the ones that are broken so far. 
Ran into another 2 old bounties

**Comment by ZekeDP** [comment]
Hi,
That’s correct. Please remove the old bounties with no gold rewards so this wont happen again

Thanks

**Comment by Dquattz** [comment]
Alrighty

Thanks

**Comment by Digitalroot** [comment]
Is that what is wrong? They just need coins?

**Comment by RandyKnapp** [comment]
It just means that they're an old version of the bounty, and they're being automatically removed by the system. You should abandon these bounties at the merchant.
