### ISSUE TITLE
open market

### ISSUE THREAD

**Issue by Uber-God** [RandyKnapp/ValheimMods#257]
hi, remember me? wanna get this ball rolling?

**Comment by Uber-God** [comment]
https://discord.gg/t6hVbbvx

**Comment by RandyKnapp** [comment]
No I don't remember. Who are you and what is this link for?

**Comment by Uber-God** [comment]
I didnt think you would. We only had 1 interaction on march 6th and I'm sorry as well. Got you mixed up with another guy. My mod would change ways all serious servers interact with each other if they want the mod on.

**Comment by Uber-God** [comment]
that is just a discord channel. i looked in my email history and the other guy wanted me to start a discord.

**Comment by Uber-God** [comment]
I would love to work with you as you've done the loot one and i would love my mod to work seemlessly with yours as it will be a market mod and tying your mega loot mod together would be much much easier.

**Comment by Uber-God** [comment]
not tie together. they will be stand alone mods,

**Comment by Uber-God** [comment]
i dont know how to do the coding or anything, but my background is simular to yours. started doing it as a kid

**Comment by Uber-God** [comment]
You dont have to commit, but could you help me out?
