### ISSUE TITLE
EpicLoot - Requests/Tweaks

### ISSUE THREAD

**Issue by matias-kovero** [RandyKnapp/ValheimMods#27]
Hi, loving the mod so far, it gives a reason to kill mobs over and over again.

Few suggestions to tweak it a bit more:

- Ability rename item "classes": Ex. I would like to use: Rare, Epic, Unique, Legendary.
- When epic loot drops, it makes an sound (love it), however I see it should only come when it drops from a Enemy? If player drops it, player already knows its Epic loot, no need to info with audio?
- Scale the drop audio with games "effects" audio? Currently the audio is way too high for my preference.

**Comment by RandyKnapp** [comment]
This is great feedback, thank you!

**Comment by RandyKnapp** [comment]
#1 & #3 I've got coming in the next update. I may eventually add #2 as a config option in the future, but it won't be high priority.

**Comment by matias-kovero** [comment]
Thanks, and fyi when using spear second attack - it throws the spear so if mainly using spear the config should be handy.

**Comment by RandyKnapp** [comment]
Fixed in 0.5.6

**Comment by Hzash** [comment]
Hey RandyKnapp, great mod! I wanted to let you know that after the Hearth and Home update (and the newest framework and EpicLoot update) magic items that I am picking up in the world are losing their abilities when added abilities randomly when I log out and back into the game sometimes. The issue appears to be intermittent. (I know, everyone hates that last bit!)

Thanks,
Hzash
