### ISSUE TITLE
Equipment & Quickslots not working

### ISSUE THREAD

**Issue by Xeth96** [RandyKnapp/ValheimMods#278]
Hello,

I'm using the latest version of the mod and Bepinex but the mod does not work, I have created a new profile on r2modmanager and only used Bepinex and the equipment & quickslots mods and the game does not detect quickslots. Also does not work on my multiplayer server, all other mods on the server work except this one.

**Comment by RandyKnapp** [comment]
Hmmm, I'm not sure what's going on. Can you turn on logging in EAQS and send me your player log?
