### ISSUE TITLE
[EpicLoot] Suggestions from GARRthePIRATE

### ISSUE THREAD

**Issue by RandyKnapp** [RandyKnapp/ValheimMods#28]
**Weapon Enchant Ideas;**
paralyze
knockback
Slow (chance to slow enemy)
Mark (chance to aggro surrounding enemies towards your last hit target)
Luck (chance to drop bonus resource/enemy drop)
Greed (chance to drop gem/gold)
Suspend Gravity (chance enemy held in air)
Increase gravity (chance enemy enveloped in vortex drawing in others)
Fate (50/50 chance deal either critical hit weakness damage or deal enemy resisted damage)
Blink (bow or arrow; teleport to contact point of arrow)
Wabbajack (final blow has chance to transmute enemy corpse to random drop/item/other live npc)

**Armor Enchant Ideas;**
Water walk
Hover (stop freefall mid air)
Air step (double jump)
Feather fall (lesser fall damage)
Thorns (enemy attack results in contact damage)
Defender (once health drops below % spawn a lesser to fight for you
Destiny (either negate all damage or provide reduced/no armor bonus)
Target (increases likeliness for aggro enemies to target you as opposed to someone just as near or nearer)
...But I Mead It (% increase to duration/stat of mead bonus)

**Could Be Either Enchant Ideas;**
Magelight (floating orb light or glowing aura)
Enrage (aggro hit target to fight for you)
Blight (distance based damage spread)
Blind (chance to blind target for x ticks)

**Comment by WiseHorror** [comment]
Commenting here a small enchantment suggestion so I don't open another issue just for it.
Hammer enchantment that lets you build without a crafting station.

**Comment by RandyKnapp** [comment]
That would be awesome!

**Comment by WiseHorror** [comment]
I just thought of another enchantment idea, this time for armor: Waterproof (no longer get wet)

**Comment by luceos** [comment]
"Just Like Home" or "Hearthed" - Grants permanent rested bonus.

"Jötunn & Svaðilfari" - fall damage ignored and 25% faster movement while wielding the building hammer (the Ice Giant who built the wall around Midgard is a Jötunn and rode Svaðilfari to carry heavy stones to meet the deadline laid down by the Gods)

Wish I could be of more help, but getting into unity might be a bit too much right now :D
Thanks for all these wonderful addons!
