### ISSUE TITLE
Lag in Boss with Many Player

### ISSUE THREAD

**Issue by HeberPcL** [RandyKnapp/ValheimMods#280]
Man, when there are **5 players** close to the boss, it gets very laggy. Do you think it could have something to do with it?

https://github.com/RandyKnapp/ValheimMods/blob/1dfc0deeea8ed2c728e60dc4f3f24feaaf94a93b/EpicLoot/CharacterDrop_Patch.cs#L87

**Comment by Advo69** [comment]
I am host on my server when I have three or more people we have this issue as well
