### ISSUE TITLE
ModUtils not auto pickable?

### ISSUE THREAD

**Issue by FelixReuthlinger** [RandyKnapp/ValheimMods#283]
I am using the modutils (leatherbelt, silverring and goldrubring) also as enchanted drops. Doing this I found that when those items get dropped by killed creatures, characters will not auto pickup them. Idk what needs to be changed for this, yet, otherwise, I would have created a PR :D

**Comment by baruchvlz** [comment]
>  Idk what needs to be changed for this, yet, otherwise, I would have created a PR

`ItemDrop.m_autoPickup` must be set to true, I think.

**Comment by RandyKnapp** [comment]
All of those items have autopickup set to true in the asset, so I'm not sure why it's not doing it. I will continue investigating.
