### ISSUE TITLE
NRE in StaggeringProjectileHit_Projectile_OnHit_Patch

### ISSUE THREAD

**Issue by Digitalroot** [RandyKnapp/ValheimMods#290]
```
Stack trace:
EpicLoot.MagicItemEffects.StaggeringProjectileHit_Projectile_OnHit_Patch.Prefix (Projectile __instance, UnityEngine.Collider collider) (at <9a7c9cfe9f164c13b5ec76b6b5f364aa>:0)
(wrapper dynamic-method) Projectile.DMD<Projectile::OnHit>(Projectile,UnityEngine.Collider,UnityEngine.Vector3,bool)
Projectile.FixedUpdate () (at <1b865f8b3455488592cdc401081112e3>:0)
```

This happens when `target.GetComponent<Character>()` returns null. 

Source https://github.com/RandyKnapp/ValheimMods/blob/8c50ab7255e529d4d1ee78439cff77566f45bdcb/EpicLoot/MagicItemEffects/ModifyStaggerDuration.cs#L87

**Comment by RandyKnapp** [comment]
I have an attempted fix in 331c2d2, can you check it out?

**Comment by Digitalroot** [comment]
We are doing the same thing to resolve it. This is what I used to reduce nesting. 

```c#
        if (collider == null) return;

        var target = Projectile.FindHitObject(collider);
        if (target == null) return;

        var character = target.GetComponent<Character>();
        if (character == null) return;

        if (!(__instance?.m_nview?.GetZDO() is ZDO zdo)) return;

        var staggerValue = zdo.GetFloat(ModifyStaggerDuration.ZdoKey, 1f);
        character.m_nview.GetZDO().Set(ModifyStaggerDuration.ZdoKey, staggerValue);
```

If I recall you are not a fan of single line conditionals. FYI, I am also not a fan. I only use them with simple return statements, and always on the same line as the conditional. 

e.g. 
`if (collider == null) return;`
or
`if (collider == null) return collider;`

What you did will resolve the NRE.

**Comment by RandyKnapp** [comment]
This is happening because of how Unity treats GameObjects under the hood, FYI. The "as GameObject" cast is bypassing the null check, which for GameObjects is overridden by Unity to check if the object is destroyed under the hood and returning true if that's the case.

That's why I use comparison with null basically everywhere in my code for gameobjects and components.

**Comment by Digitalroot** [comment]
They cover a few ways to do the Exists check. https://docs.unity3d.com/ScriptReference/Object-operator_Object.html

**Comment by Digitalroot** [comment]
Closing as I think this is resolved.
