### ISSUE TITLE
If you run the non-modded version you lose everything that was on the slots

### ISSUE THREAD

**Issue by FacuGra** [RandyKnapp/ValheimMods#3]

**Comment by tonypoly** [comment]
Same here

**Comment by RandyKnapp** [comment]
I'll leave this open for now, and experiment with ways to do this, but it's probably impossible.

**Comment by sweetgiorni** [comment]
Yeah I imagine this could get tricky to solve. At the very least you could try to empty the mod slots into the player's normal inventory during the OnDestroy() method of your BaseUnityPlugin. Then serialize what was moved and write it to a file. During the next load, read the file and move things from the player's inventory back to the mod slots. 
It doesn't handle the case where the player doesn't inventory space, but it's better than nothing...

**Comment by epicmeatwad** [comment]
Damn yeah, I just lost my Swamp Key and my troll armor set.

**Comment by xiaoxiao921** [comment]
https://github.com/Valheim-Modding/ValheimLib/blob/master/ValheimLib/ODB/SaveCustomData.cs

**Comment by RandyKnapp** [comment]
Thanks, I'll take a look

**Comment by Razinell** [comment]
I enabled and then disabled this mod. All my upgraded armor and a troll piece were gone. That really sucks. If you also lose your armor when you die, then this mod is a no-go. Shouldn't even be available for people to use.

**Comment by kajov** [comment]
@Razinell When you die you don't loose the armor and items equipped to the quick slots. If your inventory was not full enough and can fit 8 items that are equipped, they will be present in the death tombstone. If your inventory is full and there is no space the equipment will drop on the floor around the tombstone.

**Comment by derSchotte** [comment]
Hi Randy,

What about playerprevs.save? 

https://docs.unity3d.com/ScriptReference/PlayerPrefs.Save.html

Is this possibly something you can use for your mod to save the slots to a file?

**Comment by RandyKnapp** [comment]
Player prefs is not an appropriate place to store save data, as per the unity docs. I'm working on a new version, just be patient everyone, please.

**Comment by Artaak** [comment]
do not install the mod equipementandquickslot with the auto update of a mod launcher or you will lose everything in your slots 
https://valheim.thunderstore.io/package/RandyKnapp/EquipmentAndQuickSlots/2.0.1/

**Comment by RandyKnapp** [comment]
There's a big warning right on the page: !! READ ME FIRST BEFORE UPGRADING !!
