### ISSUE TITLE
[Suggestion] Auga: Crafting UI

### ISSUE THREAD

**Issue by sbtoonz** [RandyKnapp/ValheimMods#300]
Please add filter to this gorgeous UI 🙏

**Comment by sbtoonz** [comment]
I will poke at getting a groundwork coded up for this today

**Comment by RandyKnapp** [comment]
There is some layout issue here, I didn't use a unity layout group, so
InventoryGui is still doing manual layout on this list. Just FYI

**Comment by sbtoonz** [comment]
I realized I opened these in the wrong git repo, Should I close and move to Auga?
