### ISSUE TITLE
[Epic Loot] Legendary Runestone

### ISSUE THREAD

**Issue by Dominowood371** [RandyKnapp/ValheimMods#302]
After the Epic Loot 0.8.4 update, the **Legendary Runestone** item lost its rarity color.

After looking at the latest changes, I seem to have found the reason in the [file](https://github.com/RandyKnapp/ValheimMods/blob/main/ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/RunestoneLegendary.prefab):

before the change
```
      propertyPath: m_itemData.m_shared.m_ammoType
      value: Runestone
```
after change

```
      propertyPath: m_itemData.m_shared.m_ammoType
      value: $mod_epicloot_assets_reagent
```

As far as I understood, the word **Runestone** is used as an indicator in this [code](https://github.com/RandyKnapp/ValheimMods/blob/main/EpicLoot/Crafting/CraftingItemExtensions.cs), and so I think he could not be touched

**Comment by Dominowood371** [comment]
even in the game I noticed extra text in the description of the item **Gold Bounty Token**

[File](https://github.com/RandyKnapp/ValheimMods/blob/main/ValheimUnity/Assets/EpicLoot/Prefabs/Adventure/GoldBountyToken.prefab)
![Снимок экрана (328)](https://user-images.githubusercontent.com/85061444/127770094-1417e031-e763-4b0b-8eba-022da6a4f7d8.png)

**Comment by anye77** [comment]
Thank you for your discovery. I'm trying to find out

**Comment by sbtoonz** [comment]
https://github.com/RandyKnapp/ValheimMods/pull/303
