### ISSUE TITLE
[EquipmentAndQuickSlots] 2.0.11 item not visible but still in inv 

### ISSUE THREAD

**Issue by korg** [RandyKnapp/ValheimMods#304]
I died and lost my helmet and chest armor, but i can still see it when i go to upgrade at the workbench. I made another chest armor and now i have two in the upgrade tab.

2.0.11 I assume its the same issue?

Probable cause: died with full inventory, but picked up a dropped stone on the way back to the maker. Picking up items was a random clickfest because i was trying to dodge a stone golem at the same time.

**Comment by korg** [comment]
Cleared the issue by logging onto a friends server. Extra 'hidden' armor dissapeared then.

Playing again tonight with 2.0.12 and sadly i had it happen again.
  * died with a full inventory
  * + equipmentAndQuickSlots with all slots filled
  * + better archery and all 3 arrow slots filled (When you die with better archery, it usually drops the arrows on the ground nearby - rather than them being in the grave maker)

On return, inventory full but armor missing. Going to work bench gives option to upgrade armor but it isnt in the grid any more.

**Comment by korg** [comment]
OK. i did some more experimentation.

If i empty my inventory, die, respawn, then i *dont* have the items.

If i then pickup what should be my empty grave, i have an empty inventory *and* the hidden items back (judging by weight used and the fact i can see the items to upgrade).

**Comment by korg** [comment]
Partially solved it.

  * uninstalled EquipmentAndQuickSlots (probably not required)
  * installed ExtendedPlayerInventory_Reupload (adds 2 more inv slots)
  * started game
  * 'lost' items were there in the 2 extra inv rows

Still no idea why they ended up there though.

**Comment by Uberthebutcher** [comment]
Hi my friends and I have the exact same problem with equipmentAndQuickSlots with all slots filled, when we die, the armor is not visible anywhere but the bench

**Comment by kylewhite0225** [comment]
Can also confirm this is happening. All of my armor and my megingjord are all invisible but in my inventory.

**Comment by Czar1249** [comment]
I mistakenly made an entirely new thread discussing this issue happening on 2.0.12. No response from dev yet. Link here: https://github.com/RandyKnapp/ValheimMods/issues/317 I also included video of the issue. I will try the extended player inventory mod and see if it helps.

**Comment by korg** [comment]
Id recommend installing

ExtendedPlayerInventory_Reupload

to get two extra bars of inventory space and then unequip all your armor, save, quit, uninstall this mod and restart and your "lost" items will be in the new inventory slots. Problem solved. (And I found with the extra slots so I didnt need this mod). New mod got my armor back and replaced my need for this mod.

**Comment by kylewhite0225** [comment]
> 
> 
> Id recommend installing
> 
> ExtendedPlayerInventory_Reupload
> 
> to get two extra bars of inventory space and then unequip all your armor, save, quit, uninstall this mod and restart and your "lost" items will be in the new inventory slots. Problem solved. (And I found with the extra slots so I didnt need this mod). New mod got my armor back and replaced my need for this mod.

Good workaround for the time being! I do like the quickslots, though... so I hope it gets fixed.
