### ISSUE TITLE
[EIDF] WatchExtendedItemDataOnEquipment is sending too many packets

### ISSUE THREAD

**Issue by RandyKnapp** [RandyKnapp/ValheimMods#307]
@blaxxun-boop 

https://github.com/RandyKnapp/ValheimMods/blob/a82775f054372b340899be49c70c7fd4668250fd/ExtendedItemDataFramework/Player_Patch.cs#L13

There is a report that this update call is sending packets excessively on dedicated servers. Do you have any thoughts on why? Do you suppose that this method even needs to run on the server?

**Comment by blaxxun-boop** [comment]
Not sure I follow, because that thing doesn't send any packages.
