### ISSUE TITLE
ExtendedItemDataFramework - crafted by not resolved properly

### ISSUE THREAD

**Issue by Griizz** [RandyKnapp/ValheimMods#308]
For me items crafted while having this mod installed will result in weird crafted by tooltips.
![grafik](https://user-images.githubusercontent.com/31661551/128983214-ca5274df-8997-4b31-9911-d569bb14db27.png)

**Comment by Voidheart90** [comment]
![AssemblyLeakInformation](https://user-images.githubusercontent.com/59270760/130218172-ac19beb5-7328-48f8-8ef1-a14fe3762378.png)
Can confirm, this is a character save file .fch

Its leaking assembly information, the extra useless data adds more packets for addons like ServerSideCharacters
