### ISSUE TITLE
EpicLoot - Stamina regen not working as intended

### ISSUE THREAD

**Issue by Metalliguitare** [RandyKnapp/ValheimMods#31]
I dropped a stamina regen leather legs armor but the bonus isn't working as intended.

While the stamina regen bonus is said to be +13%, my stamina bar is now refilling way too fast. (like under a second from 0 to 100%)
Can make a quick video as proof but I suppose you see what i mean.

Thanks for the hard work, you're making a great mod.

**Comment by RandyKnapp** [comment]
Got a fix already in the next version

**Comment by RandyKnapp** [comment]
Fixed in 0.5.3
