### ISSUE TITLE
Epic Loot and Config Mods

### ISSUE THREAD

**Issue by danbartl** [RandyKnapp/ValheimMods#314]
Request: 
Allow EpicLoot to read config files from config/EpicLoot folder, since modmanagers like R2MM can only overwrite files in config folder.

Why: 
Many people use config mods like "Do or die Solo Experience" or "Epic Valheim" which contain new custom config files like loottables.json. Currently these are only read from EpicLoot plugins folder, which cannot be used by modpacks automatically (R2MM will not allow overwrites of other mod folders). Therefore users have to drag and drop manually on top of installing the mod manager, which is inconvenient and prone to errors.

Having mod configpacks easily installable could greatly help with adoption of config mods in Valheim, since otherwise it is often difficult to manually balance the multitude of mods people use.

Simple solution:
Check if config json (like loottables.json) is present in config/EpicLoot folder, if yes read that file, if not read file from plugins/EpicLoot. That way nothing would break for current use cases.

Thanks a lot!

**Comment by Horem** [comment]
I also would liek the JSON's for Epic loot be moved to Config folders over Plugins, due to Mod Manager's miss installing any mod that edits Epic Loot's JSON's.

**Comment by danbartl** [comment]
I think there now exists a plugin to move files around, so not needed.
