### ISSUE TITLE
Dedicated Server Bounties not Completing

### ISSUE THREAD

**Issue by KuuYami** [RandyKnapp/ValheimMods#316]
I'm well aware this has been an ongoing issue but I'd like to help out any way I can.
Current mods installed:
Valheim Plus (Server, Client)
Epic Loot 0.8.4 (Server, Client)
Fishing Overhaul (Server, Client)
Floating Items (Server, Client)
Farm Grid (Client)
Plant Everything (Server, Client)
HookGenPatcher (Server, Client)
Equipment and Quickslots (Server, Client)
Extended Item Data Framework (Server, Client)
MassFarming (Client)
Jams (Server, Client)
Jotunn [Forgot the full name] (Server, Client)
Top Mining (Server, Client)
BetterUI (Client)
![image](https://user-images.githubusercontent.com/89893176/131611238-1bbd792f-a0dd-4e46-873e-7eda002b725f.png)
There's no error upon killing the sea serpent bounty. I've tested with 3 Sea Serpents and 1 Troll, none completed. All high tier bounties (Gold tokens).

**Comment by smeadows0155** [comment]
I am having this issue as well, (bounties not being completed) I do see the RPC death notification debug message in the console but the task is never completed.

**Comment by Visp9** [comment]
We had the same problem but noticed didnt have "Extended Item Data Framework" on Server side, we only had it client. After that it worked without any problems.

**Comment by KuuYami** [comment]
Oooo that makes sense. I'll try that

**Comment by Rodrigo-Urbina** [comment]
I've checked and I do have the extra package on both server and client side and still won't complete my quests
