### ISSUE TITLE
Armor Loss on Death EAQS 2.0.12

### ISSUE THREAD

**Issue by Czar1249** [RandyKnapp/ValheimMods#317]
Hello,

I am experiencing the loss of my armor and food items upon death while using EAQS 2.0.12. This was supposed to be patched by previous versions, so I'd like this to be documented in case there are mod incompatibilities that can be sorted out for posterity.

Mods (in r2modman 3.1.19):

EAQS 2.0.12
BepInExPack_Valheim 5.4.1500
TrashItems 1.2.3
AutoRepair 5.4.1100
BetterArchery 1.6.2
ProperPortals 1.2.0
ExploreTogether 1.3.0
HoldAttack 0.4.2
Bigger_Chests 1.0.1

Here is a link to a video of me dying and losing my armor and two food items, as well as showing old armor in Workbench and Forge which are from previous deaths. Pay attention, also, to the weight change when I try to unequip my cape toward the beginning of the video. Please read the description for more information:
https://www.youtube.com/watch?v=VWBzokiM65c

Please let me know how I can upload the EAQS log. I have enabled this feature hoping to make it easier to fix whatever has gone wrong here.

**Comment by Czar1249** [comment]
I'd also like help, if anyone can, with forcefully clearing the "lost" items from my inventory so that I'm no longer carrying the extra weight and so that I don't accidentally upgrade the wrong items in the Forge/Workbench. Thanks!

**Comment by Czar1249** [comment]
Bump

**Comment by cougarten** [comment]
maybe upgrading them would fix it (have the same bug, but I'm fully upgraded)
