### ISSUE TITLE
Epic Loot Hearth & Home

### ISSUE THREAD

**Issue by JHstrutton2000** [RandyKnapp/ValheimMods#322]
The Epic Loot Valheim mod does not work since the Hearth & Home update.

**Comment by shortybsd** [comment]
This is due to the dependency ExtendedItemDataFramework. There is a temp fixed posted under [](https://github.com/RandyKnapp/ValheimMods/issues/321)

I haven't tested it yet but will a bit later.

**Comment by DerValiser** [comment]
Epic Loot has to be changed a lot. 
There are several Methods in Valheim renamed. For example
Attack.GetStaminaUsage()  is now Attack.GetAttackStamina()

After I tried to fix this, more errors came up. 
It seems that the devs changed a lot of thing.  In the Old Version there was a Method  WaterVolume.GetWaterLevel with 2 Parameters.  This seems to be now  Floating.GetLiquidLevel with 3 Parameters, in which you could choose between Water, Tar and All.  

And this is the point where I would like to stop.  Not only, that I'm not using EpicLoot (which might look a bit selfish, but fixing such things cost a lot of time, especially if this is not your own code),  but as long as I don't now what the orginal Code of Randy with his "Water Walking" should exactly do, it's not a good idea to reprogram it. 
Chaning Method Names is not a big deal.  But if there are changes in content, it's quite difficult.

I think you have to wait for randy.
