### ISSUE TITLE
New version of Equipment & Quick Slots

### ISSUE THREAD

**Issue by IoannisK746** [RandyKnapp/ValheimMods#324]
There might be a problem with the new version of EAQS.
when i run the game, at the loading of the mods, i see that the version .13 is reffered as .12 and failing to load.

![unknown (1)](https://user-images.githubusercontent.com/19365126/133878106-737fdc81-e670-4fce-b23e-6b8f6d2fe3ce.png)

**Comment by IoannisK746** [comment]
Alao in the image you can see the same issue with Extended Item Data Framework

**Comment by flodburg** [comment]
Confirmed. Not working for me either.

**Comment by Dalayeth** [comment]
The DLL's included in the release on ThunderStore and NexusMods are the old 2.0.12 in the 2.0.13 package. Confirmed with dnSpy that the DLL's listed version is 2.0.12 also show in the picture above.

**Comment by DerValiser** [comment]
Really? You are still discussing an already solved problem? Okay. If you like it, do it. I'm just playing valheim with the fixed mod.

**Comment by IoannisK746** [comment]
Unfortunately on thunderstore the problem is not solved. If it was why open an issue?
Can you send a link of fixed version?

**Comment by flodburg** [comment]
> Unfortunately on thunderstore the problem is not solved. If it was why open an issue?
> Can you send a link of fixed version?

That person is talking about the fix they made themselves I assume.

**Comment by RandyKnapp** [comment]
Fixed.

Also, @DerValiser check your attitude. Also, you're not allowed to modify my source and redistribute it. Please take your download links down.

**Comment by DerValiser** [comment]
> 
> 
> Fixed.
> 
> Also, @DerValiser check your attitude. Also, you're not allowed to modify my source and redistribute it. Please take your download links down.

I have not distributed any sources. Better see to working off the PR before blaming others. And maybe provide correct license information.

**Comment by RandyKnapp** [comment]
It's all rights reserved. You modified my source, compiled it, and uploaded
it for others to download. that's redistribution.
