### ISSUE TITLE
ExtendedItemDataFramework - Can't take cooked items off cooking station

### ISSUE THREAD

**Issue by Lucerp** [RandyKnapp/ValheimMods#325]
As stated in the title, I cannot take off any cooked item from the cooking station. This only happens when the ExtendedItemDataFramework mod is in use.

**Comment by shortybsd** [comment]
Please check current issues before posting duplicates - [https://github.com/RandyKnapp/ValheimMods/issues/321](https://github.com/RandyKnapp/ValheimMods/issues/321)

**Comment by RandyKnapp** [comment]
Fixed in 1.0.5
