### ISSUE TITLE
[Equipment & Quick Slots] H&H update auto pickup not working after interacting with enemy

### ISSUE THREAD

**Issue by guythnick** [RandyKnapp/ValheimMods#327]
I have noticed that in this new version of Equipment & Quick Slots that auto pickup is not working after killing an enemy. But, it works up until that point.  I don't see anything odd in the console output, but I can confirm that when I disable the mod, it is not happening.  I am also using ValhiemPlus.

**Comment by IoannisK746** [comment]
Its overrides the Auto Pick Up from vanilla options
press escape and options to change this or change the config file of EQS 3 extra access slots from Z **_V_** B to somethin else

**Comment by guythnick** [comment]
Yep, thank you.
