### ISSUE TITLE
ExtendedItemDataFramework 1.0.4 has the wrong DLL

### ISSUE THREAD

**Issue by Dalayeth** [RandyKnapp/ValheimMods#328]
I saw that this happened with Equipment & Quick Slots as well but that one has been fixed. ExtendedItemDataFramework however still has the DLL for version 1.0.3 inside package on both ThunderStore and NexusMods. Just wanted to make a new issue to bring it to your attention. Thanks for all the hard work guys.

**Comment by RandyKnapp** [comment]
Fixed
