### ISSUE TITLE
[EpicLoot] Compatibility, tabbing library

### ISSUE THREAD

**Issue by abearcodes** [RandyKnapp/ValheimMods#33]
Hey there, @RandyKnapp! 

You have some awesome mods going on and I've picked up some ideas over time by investigating the inner workings of your stuff as it's my first time modding and getting to know how Unity works, for which I would like to thank you! 

Now onto the main point, I was working on making Simple Recycling compatible with EpicLoot. Everything seems to work fine, except for some tabbing interactions, which I managed to work around, but it would help if EpicLoot had a stable harmony patching id, so that I could queue my patches after/before where needed, as by default Harmony generates a completely random id:
```cs
public static Harmony CreateAndPatchAll(Assembly assembly, string harmonyInstanceId = null)
    {
      Harmony harmony = new Harmony(harmonyInstanceId ?? string.Format("harmony-auto-{0}", (object) Guid.NewGuid()));
```

Right now I can work around it by setting `HarmonyPriority` on my prefix instead, but it would be better if I could explicitly tell it to run before your prefix. 

The next topic is more involved. It would be great to have a community tabbing library for Valheim. I doubt the main game is going to have any rework in that department any time soon that would make it easily extendable, and this tabbing problem will only grow worse as more and more people start making bigger mods involving custom "crafting" interactions. I quite like your approach for multi tab management, and if you had the time to, it would be great if it was released as a common library. In the long run, it's easier to migrate code towards some commons bindings rather than having everybody do their own thing and constantly fix compatibility issues. 

Thank you for your work!

**Comment by RandyKnapp** [comment]
Thanks so much for bringing this to my attention! I will update the harmony ID right away.

As far as a crafting tab solution, I think that's a great idea. I'll get something together soon.

**Comment by RandyKnapp** [comment]
0.5.4 has the new harmony id: `randyknapp.mods.epicloot`
