### ISSUE TITLE
[Equipment and Quick Slots] Death with full inventory causes equipped items to disappear

### ISSUE THREAD

**Issue by Fuzzbling** [RandyKnapp/ValheimMods#331]
If you die, with full inventory, your equipped items (Equipment and Quick Slots) are bugged and never show up again. You can see them still in the workbench as being available for upgrades. I've yet to find a solution (another death does not work, nor does equipping new armor, reloading saved game, restarting game).

[Screenshot] ( https://steamcommunity.com/sharedfiles/filedetails/?id=2606476322 )

**Comment by IoannisK746** [comment]
I just came here to report the same!!
![Screenshot_53](https://user-images.githubusercontent.com/19365126/134086671-a1f114b2-637f-4f32-b76e-1c9f204ce9ed.png)

**Comment by Tekfrog** [comment]
Oddly enough, you don't lose the items. they are just hidden from you. If you open the corresponding upgrade station, you can still interact with the items.

**Comment by IoannisK746** [comment]
Did anyone found a workaround to see again the items?

**Comment by Fuzzbling** [comment]
> 
> 
> Did anyone found a workaround to see again the items?

There's a potential workaround that someone found.

Posts section of the Nexus page:
https://www.nexusmods.com/valheim/mods/92?tab=posts

**Comment by Zerville** [comment]
Interesting so all items we "lost" earlier is in a hidden inventory slot?
My workaround is to use Death Tweaks mod so equipped items are never lost anymore... Sorry if im just bumping an old thread but it seems to still be an issue of interest.

**Comment by dev-ious** [comment]
Use more slots to get your items back, and to keep this from happening.
