### ISSUE TITLE
Magic Items reverting to non-magic after logout.

### ISSUE THREAD

**Issue by Hzash** [RandyKnapp/ValheimMods#334]
Love this mod, but I am having some trouble with it. When a magic item drops I can use it until I log out, but once I log back in the item has reverted to its original type. A magic leather helm becomes a leather helm. I have magic items that I acquired prior to the Hearth and Home update, and the subsequent EIDF and EL updates, that survive the logout and function as advertised.

I used the "magicitem" command to get a new magic item into my character inventory. The command spawned a magic leather helm. This is what I found in the player log...

[Warning:Extended Item Data Framework] Loading ExtendedItemData from data ($item_helmet_leather), data: 
[Message:Extended Item Data Framework] Loaded item from data, but it was not extended. Initializing now ($item_helmet_leather)
[Message:Extended Item Data Framework] Reverted data to non-extended mode for item ($item_helmet_leather). m_crafterName: ()
[Message:Extended Item Data Framework] Reverted data to non-extended mode for item ($item_helmet_leather). m_crafterName: ()
[Warning:Extended Item Data Framework] Copying ExtendedItemData ($item_helmet_leather)
[Message:Extended Item Data Framework] Reverted data to non-extended mode for item ($item_helmet_leather). m_crafterName: ()
[Message:Extended Item Data Framework] Reverted data to non-extended mode for item ($item_helmet_leather). m_crafterName: ()

Mods:
BepInEx 5.4.1502
BepInEx Configuration Manager 16.4
Extended Item Data Framework 1.0.5
Epic Loot 0.8.6
Equipment and Quick Slots 2.0.1.4
Creature Level and Loot Control 4.4.3
BuildHelper 0.2.0
Nexus-Clock 1.4.3

If it helps, I stripped all of my mods except BepInEx, EIDF, and EL and the issue still persists.

**Comment by RandyKnapp** [comment]
Did you update BepInEx on the server? Can you post the server logs here?

**Comment by Hzash** [comment]
I originally was not running a dedicated server, but I built one on a Linux box and tried the local dedicated server on the same Windows machine as the client. I installed the same versions of mods on both server platforms. I wondered if the issue was caused by my server shutting down, but the issue persisted even with the dedicated server. I am not sure what server files you would like, but if you let me know what file you want data from I would be happy to run through the scenario again on a dedicated server and post the output for you. 

Thanks,
Hzash

**Comment by Hzash** [comment]
Just checking back in to let you know that I fixed this issue. In typical Windows fashion, I saved my world and character files and then reinstalled the game. Once I had the mods reinstalled I retested the issue and found that my new magic items persisted through my restarts.
