### ISSUE TITLE
Heimdall Guardian of the Gods

### ISSUE THREAD

**Issue by Phoenixmb** [RandyKnapp/ValheimMods#339]
Tried to roll a Heimdall Tower shield (several hundred times). Couldn't.
Checked source code legendaries.json, confirmed  
"AllowedItemTypes": [
          "Shield"
Tried to roll a Heimdall Non-tower shield (several hundred times). Couldn't.
Enabled dev commands, spawned Heimdall set. Received Legendary set item wooden club with Immovable.
Error in the Shield set item, unknown origin.

**Comment by dev-ious** [comment]
Confirmed. 
miset Heimdall
spawns club as Guardian of the Gods

**Comment by skidogg88** [comment]
From what I can tell, I believe its a issue with naming of shields. Which would make sense as I don't believe I've ever seen a shield named other then just the rarity of it and default type.

**Comment by RandyKnapp** [comment]
This is a good solution, thank you

**Comment by vandit49** [comment]
I found it not to be an issue with shield type, but with the ItemHasNoParryPower/ItemHasParryPower.  When I took this requirement out, it would drop on shields.  It seems this qualifier is not working
