### ISSUE TITLE
Epic Loot Conflict with CraftingWithContainers

### ISSUE THREAD

**Issue by BurroTile** [RandyKnapp/ValheimMods#34]
Thanks for the mod! Loving it!

Happens randomly when interacting with containers/forge. No problem until Epic loot was installed. Both mods seem to work fine independently. 

https://valheim.thunderstore.io/package/abearcodes/CraftingWithContainers/
https://valheim.thunderstore.io/package/RandyKnapp/EpicLoot/

Collected: 

[Error  : Unity Log] KeyNotFoundException: The given key was not present in the dictionary.
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
EpicLoot.MagicItem.GetEffectText (EpicLoot.MagicItemEffect effect, EpicLoot.ItemRarity rarity, System.Boolean showRange) (at <ec10bda24bd8420c8ea2c9d250855e27>:0)
EpicLoot.MagicItem.GetTooltip () (at <ec10bda24bd8420c8ea2c9d250855e27>:0)
EpicLoot.MagicItemTooltip_ItemDrop_Patch.Prefix (System.String& __result, ItemDrop+ItemData item, System.Int32 qualityLevel, System.Boolean crafting) (at <ec10bda24bd8420c8ea2c9d250855e27>:0)
(wrapper dynamic-method) ItemDrop+ItemData.DMD<ItemDrop+ItemData::GetTooltip>(ItemDrop/ItemData,int,bool)
ItemDrop+ItemData.GetTooltip () (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
EpicLoot.InventoryGrid_CreateItemTooltip_MagicItemComponent_Patch.Prefix (ItemDrop+ItemData item, UITooltip tooltip) (at <ec10bda24bd8420c8ea2c9d250855e27>:0)
(wrapper dynamic-method) InventoryGrid.DMD<InventoryGrid::CreateItemTooltip>(InventoryGrid,ItemDrop/ItemData,UITooltip)
(wrapper dynamic-method) InventoryGrid.DMD<InventoryGrid::UpdateGui>(InventoryGrid,Player,ItemDrop/ItemData)
InventoryGrid.UpdateInventory (Inventory inventory, Player player, ItemDrop+ItemData dragItem) (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
InventoryGui.UpdateInventory (Player player) (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
InventoryGui.Update () (at <f48d6a22696245bf8d820aad6afa4fdb>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ABearCodes.Valheim.CraftingWithContainers.Crafting.UIVisualPatches.PatchDoCraftingHook (Player player, Recipe ___m_craftRecipe) (at <06048c31eab24880b534d5998685a355>:0)
(wrapper dynamic-method) InventoryGui.DMD<InventoryGui::DoCrafting>(InventoryGui,Player)
(wrapper dynamic-method) InventoryGui.DMD<InventoryGui::UpdateRecipe>(InventoryGui,Player,single)
InventoryGui.Update () (at <f48d6a22696245bf8d820aad6afa4fdb>:0)

Thanks!

**Comment by RandyKnapp** [comment]
Just a followup. The first exception is fixed in 0.5.4. The second is an issue with the other mod. But it would go away if you go change its config value of `LogItemRemovalsToConsole` to false.
