### ISSUE TITLE
Base burried after accepting haldor quest (EpicLoot I think)

### ISSUE THREAD

**Issue by jethrolarson** [RandyKnapp/ValheimMods#342]
Met haldor for the first time. Accepted two quests. portaled back home and saw this. 
![image](https://user-images.githubusercontent.com/32480/136715713-cab6ffd9-ec0c-44f9-9407-df5759c97d17.png)

Attempting to mine or level the terrain does nothing.

**Comment by jethrolarson** [comment]
Restarting the game seemed to fix it though.

**Comment by RandyKnapp** [comment]
This is incredible strange.

**Comment by jethrolarson** [comment]
My best theory is that the quest acceptance changed the world and the chunk regenerated before applying the player modifications. Then somehow the terrain modifications failed to apply but the construction ones didn't.
