### ISSUE TITLE
Epic Loot Different info

### ISSUE THREAD

**Issue by Doxramos** [RandyKnapp/ValheimMods#345]
Hey there! Friend got some legendary bronze leg pieces, but they show as normal bronze to me. Is that intended or a bug?

**Comment by jere535** [comment]
very little info to go on, but if you also cant enchant/disenchant stuff or you dont get any drops its likely Epic loot as a whole doesnt work for some reason.
I've had problems with epicloot where it randomly stops working for no reason.
