### ISSUE TITLE
Tranlations.json needs to be a server synced for multiplayer

### ISSUE THREAD

**Issue by davidtaylornc** [RandyKnapp/ValheimMods#350]
Currently one cannot add any server side JSON bits that reference modified  $ variables in translations.json or its language counterparts without risking a text display error on other clients in multiplayer.  

This makes it impossible to add new custom items or abilities without pushing new translation files to everyone.

The translation files file should be server synced like the other json files.  

I hacked it into my epicloot by making the whole translation strings file into a CustomSyncedValue<string> but I am sure there is a better C# way.

**Comment by RandyKnapp** [comment]
This is an interesting problem but that's not how I would solve it. That forces everyone to use the same language for the EL items (and UI), and that feels like incorrect behavior to me. Instead, just name your items without the `$` in front and they won't be translated at all.

**Comment by davidtaylornc** [comment]
Thanks for the response, and for keeping this mod up to date.  I agree, the way I did it gets weird in a multiple language client environment.  It also wastes a ton of memory and network bandwidth syncing the whole file every time a tiny change occurs.  

The number one thing my players complain about is having to download and add files for trivial updates.  In a dedicated server environment, the better thing is that the server side add the data and the clients get it seamlessly.  Item names and descriptions are a huge part of the flavor EpicLoot brings into the game.  My thought process is that if translations are important enough to have, they are important enough to sync like the rest of the server side data.

Of course, it is no problem for anyone in single player mode.
