### ISSUE TITLE
Move json files to the BepInEx\config folder

### ISSUE THREAD

**Issue by thedefside** [RandyKnapp/ValheimMods#353]
Would you be willing to have the json files moved to the config folder? This would allow mod pack authors to distribute customized json files with the TS mod manager. I can do the work, but wanted to check with you first to see if that's something you would allow.

**Comment by RandyKnapp** [comment]
I don't think it's a good idea. The json files are not so much "config" as
"data definitions".

**Comment by thedefside** [comment]
Okay. Figured it wouldn't hurt to ask.
