### ISSUE TITLE
Armor/Item Stands in 0.206.5 remove enchants

### ISSUE THREAD

**Issue by Voidheart** [RandyKnapp/ValheimMods#356]
Placing anything on the ItemStands / ArmorStands removes enchantments in Patch 0.206.5

**Comment by JMCY26** [comment]
Hoping to see this fixed, players found out the hard way losing their enchants

**Comment by smeadows0155** [comment]
Can confirm that this is an issue... It allows you to disenchant items and re-enchant them... When a different player is nearby and you remove your item from the stand, they hear the sound that accompanies an enchanted loot beam... This leads me to believe that the item is only disenchanted for the person who retrieves the item from the armor stand.
