### ISSUE TITLE
EpicLoot.MagicItemEffects function errors

### ISSUE THREAD

**Issue by westor7** [RandyKnapp/ValheimMods#358]
Hello,

Using that mod on a friend server and got an error, maybe will help u fix the issue.

`[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
EpicLoot.MagicItemEffects.ExecutionerCheckDamage_Character_Damage_Patch.Prefix (Character __instance, HitData hit) (at <26436b77be1942e49446de9e2ce13196>:0)
(wrapper dynamic-method) Character.DMD<Character::Damage>(Character,HitData)
Aoe.OnHit (UnityEngine.Collider collider, UnityEngine.Vector3 hitPoint) (at <0b427da81d26480c885ae3fba0ed94c4>:0)
Aoe.CheckHits () (at <0b427da81d26480c885ae3fba0ed94c4>:0)
Aoe.FixedUpdate () (at <0b427da81d26480c885ae3fba0ed94c4>:0)`

- Thanks!

**Comment by Elledar** [comment]
Hi!
Same problem! Can you tell how to fix it?
Thanks!

**Comment by Kupoman** [comment]
I am also seeing a similar error:
```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
EpicLoot.MagicItemEffects.StaggeringProjectileHit_Projectile_OnHit_Patch.Prefix (Projectile __instance, UnityEngine.Collider collider) (at <c721b9fc860a402996cf4fc2e73a48de>:0)
(wrapper dynamic-method) Projectile.DMD<Projectile::OnHit>(Projectile,UnityEngine.Collider,UnityEngine.Vector3,bool)
Projectile.FixedUpdate () (at <19063e3c1dfa48538b17f68f613828b2>:0)

NullReferenceException: Object reference not set to an instance of an object
  at EpicLoot.MagicItemEffects.StaggeringProjectileHit_Projectile_OnHit_Patch.Prefix (Projectile __instance, UnityEngine.Collider collider) [0x00072] in <c721b9fc860a402996cf4fc2e73a48de>:0 
  at (wrapper dynamic-method) Projectile.DMD<Projectile::OnHit>(Projectile,UnityEngine.Collider,UnityEngine.Vector3,bool)
  at Projectile.FixedUpdate () [0x0015c] in <19063e3c1dfa48538b17f68f613828b2>:0 
 
(Filename: <c721b9fc860a402996cf4fc2e73a48de> Line: 0)
```
