### ISSUE TITLE
[EpicLoot][0.8.7-0.8.8] loottable.json not overriding base json

### ISSUE THREAD

**Issue by FrederickEngelhardt** [RandyKnapp/ValheimMods#362]
Nothing happens when attempting to override epic loot's base loot config.

The mod such as [epic-loot-mats-only](https://valheim.thunderstore.io/package/FixItFelix/EpicLoot_MatsOnly_LootTables/) adds EpicLoot config overrides to the folder `BepInEx\config\EpicLoot`.

It looks like this folder may not be supported anymore or we need to override the base plugins/files folder for epic loot.

Example working config overrride
- Create a separate config mod that overrides `BepInEx\plugins\files\loottables.json` or whatever files you need
- override the base epic loot folder and add the config override and install the mod after re-zipping.
- manually Copy all EpicLoot config overrides to the files section `BepInEx\plugins\files`.

**Comment by RandyKnapp** [comment]
Place the EpicLoot files in a folder called "EpicLoot" instead of "files". As per the installation instructions.

**Comment by werner-mayer** [comment]
same issue before updating to 0.8.8

![image](https://user-images.githubusercontent.com/36904541/151266547-38faaf77-3c56-43a0-8fb8-7ce0f81e70bd.png)
