### ISSUE TITLE
0.5.4: Sacrificing an item sacrifices the wrong thing if you change items while crafting

### ISSUE THREAD

**Issue by bonesbro** [RandyKnapp/ValheimMods#37]
If you begin sacrificing an item and click on a different item while the progress bar is still going up it will sacrifice the item that is currently selected when the progress bar completes.

Repro steps:
0: Add at least two sacrificable items to your inventory.
1: Use a forge with enchanter, click the Sacrifice tab, and select the first item.
2: Click the big Sacrifice button
3: Click a different item while the progress bar is still going up

Expected: The item you began sacrificing in step 2 is destroyed
Actual: The item you selected in step 3 is destroyed

**Comment by RandyKnapp** [comment]
Fixed in 0.5.5
