### ISSUE TITLE
Epic Loot: Items appearing outside chest duplicating contents

### ISSUE THREAD

**Issue by Sos339** [RandyKnapp/ValheimMods#38]
Running: 
Epic loot v5.5
ValheimBrawler
Jam
ExtendedItemDataFramework
SimpleRecycling
BuildCamera
Drop That
QuickStack

/title; It appears that 'unenchanted' items are spawning outside the chest in parallel to whats inside the chest if it's an enchanted item
example: stone axe on the ground where the chest is, and an enchanted stone axe within the chest
can cause progression issues with meadows secret circle chest containing iron armor that 'floats' to the surface for easy grabbing before even obtaining the pickaxe

Screenshots:
https://i.imgur.com/NS6xuTQ.jpg
https://i.imgur.com/cpPWLg9.jpg
https://i.imgur.com/MRlhNxp.jpg

**Comment by RandyKnapp** [comment]
Thanks! Great report!

**Comment by Sos339** [comment]
update: Tested just the mod and item framework by itself on a fresh character and fresh world, same issue.

**Comment by RandyKnapp** [comment]
Fixed in 0.5.7
