### ISSUE TITLE
Incorrect item tiers dropping

### ISSUE THREAD

**Issue by collinsmith** [RandyKnapp/ValheimMods#383]
I can't seem to get loot tables or drops via `mi Magic ShieldWood` (spawns a club) to work as they should. I tried spawning GoblinKing and he just drops clubs, rags, etc, and not his t5 stuff. Same story across other monsters.

BepInEx 5.4.19.0
Valheim 0.207.20
Extended Item Data Framework 1.0.7
Epic Loot 0.8.8

I've tried clearing my entire directory and removing all other mods and removing any changes I've made and using the package on Nexus. There aren't any errors reported, either with json syntax or with the item drops, it just seems to pick the wrong item? I can control the numbers of items, rarity, etc, but not the specific item.

**Comment by RandyKnapp** [comment]
There's a gating system, use the `cheatgating` command to have it drop the
actual item rather than downgrading to what you can currently craft

**Comment by collinsmith** [comment]
Thank you! Is there a config option to disable this server-wide?

**Comment by RandyKnapp** [comment]
Yeah it's called `Item Drop Limits` in the config file, and you can set it to `Unlimited`

**Comment by collinsmith** [comment]
Thank you!
