### ISSUE TITLE
Suggested feature: change loot quality color scheme

### ISSUE THREAD

**Issue by BevansDesign** [RandyKnapp/ValheimMods#389]
First, I haven't tried this mod (but I want to) so I don't know if this feature already exists. If so, I apologize for wasting your time.

Anyway, it'd be great if players could customize the quality coloring they see to match their preference. For example, I prefer WoW colors (green, blue, purple, orange) while a friend might prefer Diablo/PoE colors (white, blue, yellow, orange).

**Comment by CallumWalley** [comment]
Yep you can change that in the config file. :+1:
