### ISSUE TITLE
Trader Workshop

### ISSUE THREAD

**Issue by Kaelns** [RandyKnapp/ValheimMods#393]
1) Problem: 
    - the counter died
    - the goods disappeared 
    - the tasks are not taken (tasks are taken, but they don't disappear)
2) Solution attempts: completely reinstalled but it didn't help
3) Screenshots:
![Screenshot_25](https://user-images.githubusercontent.com/67708215/174896287-bf5ac444-8c47-4680-ad3d-4781f4b0d6c8.png)
![Screenshot_26](https://user-images.githubusercontent.com/67708215/174896293-97c69dc0-e2b3-48bb-bdcc-4b563523aec6.png)
4) Log file:
[LogOutput.log](https://github.com/RandyKnapp/ValheimMods/files/8952758/LogOutput.log)

**Comment by MeldorMage** [comment]
Hello, just adding my voice to the stream here.  I followed your threads on discord KaeIns and I’m having the exact same issue since update.  Eager to hear how to fix if possible.  Really miss the bounties, treasure maps, etc…. Awesome app btw Randy. Epic loot just makes our game on the server!! Thanks!

**Comment by RandyKnapp** [comment]
Hi folks, can you please try this updated version and let me know if it works? Just replace the dll file in your plugins/EpicLoot folder.
[EpicLoot.zip](https://github.com/RandyKnapp/ValheimMods/files/8985193/EpicLoot.zip)

**Comment by MeldorMage** [comment]
Works perfectly for me now.  Thanks so much man! You are a genius and your efforts are truly appreciated.

**Comment by MeldorMage** [comment]
Randy do you have a patreon or some such that i can help support?  Very new here, sorry if that sounds like something I should already know.  Just really want to show my appreciation for what you have done and continue doing.  Thanks again!

**Comment by RandyKnapp** [comment]
Hey thanks!

> Message ID: ***@***.***>
>

PayPal is what I use. ***@***.***

**Comment by MeldorMage** [comment]
Can’t see anything in your post other about PayPal other than **@****.*** and it doesn’t seem to be a link. Try again?

**Comment by RandyKnapp** [comment]
Really weird that it censored my email. Here's a link https://www.paypal.com/donate/?hosted_button_id=UFYR7AKYFPXLY

**Comment by MeldorMage** [comment]
Got it thanks again Randy!
