### ISSUE TITLE
Dont work on dedicated server

### ISSUE THREAD

**Issue by tonypoly** [RandyKnapp/ValheimMods#4]
on dedicated server i get  [Warning:   BepInEx] Skipping [Equipment and Quick Slots 1.0.1] because of process filters (valheim.exe)"

seem to not work on valheim_server.exe

**Comment by RandyKnapp** [comment]
I'm not sure this mod is necessary for the server, it's pretty much client only and if the server passes the players inventory around normally, it should be fine?
