### ISSUE TITLE
DvergerColor: Bees not lootable

### ISSUE THREAD

**Issue by LunaValheim** [RandyKnapp/ValheimMods#40]
with this plugin included in BepinEx, I'm not able to "break" wild  hives and loot the queen bees. As soon as I delete the folder, I'm able to break/loot as per normal.

**Comment by RandyKnapp** [comment]
Can you please describe what you mean? I have this mod active, and last night while playing I shot two bee hives with arrows and they broke and the queen bee dropped.

**Comment by LunaValheim** [comment]
*facepalm*

I had god mode activated - which apparently also makes Beehives immortal.
I'd apparently forgotten to turn it off while testing - having flown around
in search for hives to test on.

Apologies - and please mark the issue closed.

**Comment by RandyKnapp** [comment]
No worries, thanks for the feedback! I hope you're enjoying my mods!
