### ISSUE TITLE
Legendary Sets / Items drop from Bosses

### ISSUE THREAD

**Issue by nelugio** [RandyKnapp/ValheimMods#400]
Is there a way to change the Loottable.json to let Bosses drop the added legendary Items like Mjolnir etc. ?
Or is it planned to be implemented later on?
As far as i know so far the only way to get the Mjolnir would be to spawn it via console commands?

**Comment by nelugio** [comment]
Is there a way to change the Loottable.json to let Bosses drop the added legendary Items like Mjolnir etc. ?
Or is it planned to be implemented later on?
As far as i know so far the only way to get the Mjolnir would be to spawn it via console commands?

**Comment by BranTuna** [comment]
You're looking for loottables.json and iteminfo.json, and if you wanna gamble for it, then adventuredata.json as well. I've added the entirety of Judes Equipment, Chaos Armor, Odins Backpacks, and Epic Valheim Additions items this way. If you wanna learn .json if you don't already know it, this is a great time to learn. :)
