### ISSUE TITLE
Multiplayer Issue

### ISSUE THREAD

**Issue by shigetiro** [RandyKnapp/ValheimMods#402]
right after adding the "Epic Loot" mod i am unable to connect to my Dedicated Server if i remove it it works normally could it be incompatible with the GamePass version ?
![image](https://user-images.githubusercontent.com/24944943/194595872-8bcb6c81-600a-4b39-84fc-135176570715.png)

**Comment by kr4toos19** [comment]
the problem is the plugin Extended Item Data Framework, the plugin creator does not respond there is no way

**Comment by shigetiro** [comment]
I know but it's easy to fix just rebuild the mods with the new ServerSync file already did a pull request for it

**Comment by kr4toos19** [comment]
How can I do it on my server, can you explain?

**Comment by kr4toos19** [comment]
(https://user-images.githubusercontent.com/19381174/197002712-fa0688df-6e45-40cc-90b4-80356e5821db.png)  

where do i put this?

**Comment by shigetiro** [comment]
[EpicLoot.zip](https://github.com/RandyKnapp/ValheimMods/files/9832114/EpicLoot.zip)

Use this one extract it in the BepinEx/Plugins folder on both Client and Server then it should work normally

**Comment by kr4toos19** [comment]
I'm going to test, my problem even though on the dedicated server the players are being kicked out

**Comment by shigetiro** [comment]
Do you have other mods installed if yes which exactly?

**Comment by kr4toos19** [comment]
so there aren't many more it's hard to open a server with them together, AnyPortal EpicLoot BetterTrader TeleportEverything EquipmentAndQuickSlots

**Comment by Holzwurst** [comment]
We're having somehow the same error. It neither works with version 0.8.9 nor with the one postet here, clients are getting timeouts

**Comment by shigetiro** [comment]
[EpicLoot.zip](https://github.com/RandyKnapp/ValheimMods/files/9892387/EpicLoot.zip)
Updated version should work with the newest update 0.211.11

**Comment by technokiddd** [comment]
Yeah, even with this still getting issues connecting. Getting a black screen when I try to join my friends modded server and it continually says I'm trying to connect.

**Comment by DSMTurboAWD** [comment]
We were having the same issue, we ended up installing the server sync fix and it seemed to address the issue.
https://github.com/JereKuusela/valheim-server_sync_fix
