### ISSUE TITLE
Retrieving full corpse deletes armor

### ISSUE THREAD

**Issue by EdvinOlofsson** [RandyKnapp/ValheimMods#403]
If you die with a full inventory, your tombstone will not contain your armor/quick slot items when retrieved and will be permanently lost...

:(

**Comment by Dom063** [comment]
Can also confirm this issue, although I have no proof to verify. I am thinking it may be an issue with BetterArchery even though I have disabled the quiver. Not sure yet.

**Comment by shigetiro** [comment]
Just use the mod "Gravekeeper" to save the armor/quickslot stuff

**Comment by EdvinOlofsson** [comment]
Thanks for the tip!

**Comment by Eltharien** [comment]
I and others i play with had this issue pre Mistlands, We started using Death Tweaks mod to avoid this issue so i cant say if the updates post mistlands have fixed it, has anyone had this issue since?
