### ISSUE TITLE
Mod throwing errors after official Mistlands update.

### ISSUE THREAD

**Issue by MancV21** [RandyKnapp/ValheimMods#411]
I don't know if development is still active, but if so the mod is throwing this error on load after the new Mistlands update. The game loads but the camera spins rapidly and is unplayable. The log states - 

```
[Error  : Unity Log] MissingMethodException: bool Player.IsItemQueued(ItemDrop/ItemData)
Stack trace:
(wrapper dynamic-method) HotkeyBar.DMD<HotkeyBar::UpdateIcons>(HotkeyBar,Player)
EquipmentAndQuickSlots.HotkeyBarController+Hud_Update_Patch.Postfix (Hud __instance) (at <44c37e2b6b244061b63a757fdedf4599>:0)
(wrapper dynamic-method) Hud.DMD<Hud::Update>(Hud)
```
```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
EquipmentAndQuickSlots.EquipmentSlotHelper.RefreshEquipmentInSlots (Player player) (at <44c37e2b6b244061b63a757fdedf4599>:0)
EquipmentAndQuickSlots.EquipmentSlotHelper+Humanoid_EquipItem_Patch.Postfix (Humanoid __instance, System.Boolean __result, ItemDrop+ItemData item) (at <44c37e2b6b244061b63a757fdedf4599>:0)
(wrapper dynamic-method) Humanoid.DMD<Humanoid::EquipItem>(Humanoid,ItemDrop/ItemData,bool)
Player.EquipIventoryItems () (at <2908ee13764f4b9b9dc90e3a253fd4dd>:0)
Player.Load (ZPackage pkg) (at <2908ee13764f4b9b9dc90e3a253fd4dd>:0)
PlayerProfile.LoadPlayerData (Player player) (at <2908ee13764f4b9b9dc90e3a253fd4dd>:0)
Game.SpawnPlayer (UnityEngine.Vector3 spawnPoint) (at <2908ee13764f4b9b9dc90e3a253fd4dd>:0)
Game.UpdateRespawn (System.Single dt) (at <2908ee13764f4b9b9dc90e3a253fd4dd>:0)
Game.FixedUpdate () (at <2908ee13764f4b9b9dc90e3a253fd4dd>:0)

```
Is there a chance of an update or is the mod dead?

Thanks.

**Comment by MancV21** [comment]
Was just asking mate, take all the time you need. ;) Appreciate your work, thank you. :)

**Comment by RandyKnapp** [comment]
Lol sorry! Thanks for your support, I've just been overwhelmed with questions today

**Comment by MancV21** [comment]
> Lol sorry! Thanks for your support, I've just been overwhelmed with questions today

I can imagine lol. Don't apologise, take your time, do what you need to do and fit this in when you can, if you can. ;)

**Comment by viperp12** [comment]
> Lol sorry! Thanks for your support, I've just been overwhelmed with questions today

Love your work. Very tempted to get involved with the modding as well. Thank you for your time!

**Comment by Julien00859** [comment]
For those (like me) who are fine running the game without mods for the time being and just want to get their armor/quick-slot from the Equipment and Quick Slot mod. I've just tested the [EquipmentAndQuickSlots-MistlandsTest2.zip](https://github.com/RandyKnapp/ValheimMods/blob/main/EquipmentAndQuickSlots/EquipmentAndQuickSlots-MistlandsTest2.zip) from yesterday commit 92e01ff4ee81e7dbf94ed6a2150cc37453fa3e21. Thanks to this test version I was able to start the game, move my stuff from the quick-slots to the main inventory. I then restarted the game without the mod and my stuff is safe in my inventory :) The installation process is straithforward, just open vortex, click "install from file" and select the zip file (no need to unzip it). Thank you Randy for the good work, I see you have plenty of mods to update, courage!

**Comment by MancV21** [comment]
> For those (like me) who are fine running the game without mods for the time being and just want to get their armor/quick-slot from the Equipment and Quick Slot mod. I've just tested the [EquipmentAndQuickSlots-MistlandsTest2.zip](https://github.com/RandyKnapp/ValheimMods/blob/main/EquipmentAndQuickSlots/EquipmentAndQuickSlots-MistlandsTest2.zip) from yesterday commit [92e01ff](https://github.com/RandyKnapp/ValheimMods/commit/92e01ff4ee81e7dbf94ed6a2150cc37453fa3e21). Thanks to this test version I was able to start the game, move my stuff from the quick-slots to the main inventory. I then restarted the game without the mod and my stuff is safe in my inventory :) The installation process is straithforward, just open vortex, click "install from file" and select the zip file (no need to unzip it). Thank you Randy for the good work, I see you have plenty of mods to update, courage!

That works perfectly, thank you for this, I got my gear back!

**Comment by acferrarijr** [comment]
> For those (like me) who are fine running the game without mods for the time being and just want to get their armor/quick-slot from the Equipment and Quick Slot mod. I've just tested the [EquipmentAndQuickSlots-MistlandsTest2.zip](https://github.com/RandyKnapp/ValheimMods/blob/main/EquipmentAndQuickSlots/EquipmentAndQuickSlots-MistlandsTest2.zip) from yesterday commit [92e01ff](https://github.com/RandyKnapp/ValheimMods/commit/92e01ff4ee81e7dbf94ed6a2150cc37453fa3e21). Thanks to this test version I was able to start the game, move my stuff from the quick-slots to the main inventory. I then restarted the game without the mod and my stuff is safe in my inventory :) The installation process is straithforward, just open vortex, click "install from file" and select the zip file (no need to unzip it). Thank you Randy for the good work, I see you have plenty of mods to update, courage!

tks, really helpfull

**Comment by benloz10** [comment]
I found this post after having this same error spam, but found that after removing this mod, I still had errors, and my hotbar was still missing. After removing Better Archery, then even with Equipment and Quick Slots installed, I got no errors. Figured i'd post here in case it might help someone.

**Comment by derekguenther** [comment]
@RandyKnapp You're the best!  I was prepared to be patient, but you were _fast_.  Thanks for knocking it out so quickly, and all the effort you put into this mod and keeping it up to date.  Very much appreciated!

**Comment by MancV21** [comment]
> 

Seconded. Thank you!
