### ISSUE TITLE
ExplodingArrowHit_Projectile_OnHit_Patch issue

### ISSUE THREAD

**Issue by Zors** [RandyKnapp/ValheimMods#412]
I currently have a working versions of EpicLoot for Mistlands with your latest changes from a few days ago and I get this error from the ExplodingArrows.cs every time a Greydrawf throws a rock at me and it hits me. It doesn't occur when they miss. I compared the old versions of Valheim to the latest and did notice some changes to the "Projectile.OnHit" that may be causing this issue. 

I noticed that you haven't updated any of the code from ExplodingArrows.cs recently for Mistlands, and since it builds without issue, I wanted to let you know about it. If you're already aware, have already fixed, or can't replicate the issue, then please ignore.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
EpicLoot.MagicItemEffects.ExplodingArrowHit_Projectile_OnHit_Patch.Postfix (System.Boolean __state, UnityEngine.Vector3 hitPoint, Projectile __instance) (at <fb449cd52c9045589e30ee98b9adb7a0>:0)
(wrapper dynamic-method) Projectile.DMD<Projectile::OnHit>(Projectile,UnityEngine.Collider,UnityEngine.Vector3,bool)
Projectile.FixedUpdate () (at <035307060cbb4b30b916cd82ebd80490>:0)

**Comment by RandyKnapp** [comment]
Thank for for the detailed report. I was aware but I am still working on a fix. Hopefully updating soon!
