### ISSUE TITLE
[steamdeck] in-game start button doesn't work

### ISSUE THREAD

**Issue by Sensang** [RandyKnapp/ValheimMods#413]
Clicking the start button after selecting a world will not do anything visible.

I have the minimum amount of mods, so bepinex, extended itemdata framework and epic loot. It works if I remove epic loot.

**Comment by Sensang** [comment]
logfile:

`[Message:   BepInEx] BepInEx 5.4.19.0 - valheim (12/08/2022 18:37:08)
[Info   :   BepInEx] Running under Unity vUnknown (post-2017)
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Linux
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.19.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Info   :   BepInEx] Detected Unity version: v2020.3.33f1
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 3 plugins to load
[Info   :   BepInEx] Loading [Display BepInEx Info In-Game 2.0.0]
[Info   :   BepInEx] Loading [Extended Item Data Framework 1.0.7]
[Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type Inventory and name AddItem and parameters (string, int, float, Vector2i, bool, int, int, long, string)
[Error  : Unity Log] ArgumentException: Undefined target method for patch method static bool ExtendedItemDataFramework.Inventory_AddItemFromLoad_Patch::Prefix(Inventory __instance, Boolean& __result, string name, int stack, float durability, Vector2i pos, bool equiped, int quality, int variant, long crafterID, string crafterName)
Stack trace:
HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
Rethrow as HarmonyException: Patching exception in method null
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.<PatchAll>b__11_0 (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.CreateAndPatchAll (System.Reflection.Assembly assembly, System.String harmonyInstanceId) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
ExtendedItemDataFramework.ExtendedItemDataFramework.Awake () (at <dfd72d765e1645ba9a4759fa398691c4>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()

[Info   :   BepInEx] Loading [Epic Loot 0.8.9]
[Info   : Unity Log] 12/08/2022 19:20:23: Loaded localization CSV:localization language:English

[Info   : Unity Log] 12/08/2022 19:20:23: Loaded localization CSV:localization_extra language:English

[Error  : Unity Log] AmbiguousMatchException: Ambiguous match found.
Stack trace:
System.RuntimeType.GetMethodImpl (System.String name, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Reflection.CallingConventions callConv, System.Type[] types, System.Reflection.ParameterModifier[] modifiers) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Type.GetMethod (System.String name, System.Reflection.BindingFlags bindingAttr) (at <695d1cc93cca45069c528c15c9fdd749>:0)
HarmonyLib.AccessTools.DeclaredMethod (System.Type type, System.String name, System.Type[] parameters, System.Type[] generics) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchTools.GetOriginalMethod (HarmonyLib.HarmonyMethod attr) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
Rethrow as HarmonyException: Ambiguous match for HarmonyMethod[(class=SE_Rested, methodname=CalculateComfortLevel, type=Normal, args=undefined)]
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.<PatchAll>b__11_0 (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.CreateAndPatchAll (System.Reflection.Assembly assembly, System.String harmonyInstanceId) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
EpicLoot.EpicLoot.Awake () (at <967dff30df8e47cf958595b66efa7e1c>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()

[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] 12/08/2022 19:20:26: Starting to load scene:start

[Warning: Unity Log] Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Amb_MainMenu).
[Info   : Unity Log] 12/08/2022 19:20:30: Using environment steamid 892970

[Info   : Unity Log] 12/08/2022 19:20:30: Using steam APPID:892970

[Info   : Unity Log] 12/08/2022 19:20:30: Authentication:k_ESteamNetworkingAvailability_Attempting

[Info   : Unity Log] 12/08/2022 19:20:30: Steam initialized, persona:Exosus

[Info   : Unity Log] 12/08/2022 19:20:30: PlayFab custom ID set to "Steam_76561198005814333"

[Info   : Unity Log] 12/08/2022 19:20:30: Running on Steam Deck!

[Info   : Unity Log] 12/08/2022 19:20:30: Valheim version:0.212.7

[Info   : Unity Log] 12/08/2022 19:20:30: Worldgenerator version setup:2

[Info   : Unity Log] 12/08/2022 19:20:30: Render threading mode:MultiThreaded

[Warning: Unity Log] 12/08/2022 19:20:30: Missing audio clip in music respawn

[Info   : Unity Log] 12/08/2022 19:20:30: Checking for installed DLCs

[Info   : Unity Log] 12/08/2022 19:20:30: DLC:beta installed:False

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData/SharedData.m_holdAnimationState' not found.
Stack trace:
EpicLoot.Crafting.CraftingItemExtensions.GetRunestoneRarity (ItemDrop+ItemData item) (at <967dff30df8e47cf958595b66efa7e1c>:0)
EpicLoot.ItemDataExtensions.GetRarity (ItemDrop+ItemData itemData) (at <967dff30df8e47cf958595b66efa7e1c>:0)
EpicLoot.EpicLoot.TryRegisterItems () (at <967dff30df8e47cf958595b66efa7e1c>:0)
EpicLoot.ObjectDB_CopyOtherDB_Patch.Postfix () (at <967dff30df8e47cf958595b66efa7e1c>:0)
(wrapper dynamic-method) ObjectDB.DMD<ObjectDB::CopyOtherDB>(ObjectDB,ObjectDB)
FejdStartup.SetupObjectDB () (at <035307060cbb4b30b916cd82ebd80490>:0)
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::Start>(FejdStartup)

[Info   : Unity Log] 12/08/2022 19:20:31: Ticket is System.Byte[] of length 369

[Info   : Unity Log] 12/08/2022 19:20:31: UI Group status changed Menu = True

[Info   : Unity Log] 12/08/2022 19:20:33: PlayFab logged in as "Steam_76561198005814333"

[Info   : Unity Log] 12/08/2022 19:20:33: PlayFab local entity ID is A6841E93E39F8D4

[Info   : Unity Log] 12/08/2022 19:20:33: UI Group status changed Menu = True

[Info   : Unity Log] 12/08/2022 19:20:35: FOund selected Start game

[Info   : Unity Log] 12/08/2022 19:20:35: show character selection

[Info   : Unity Log] 12/08/2022 19:20:37: OnCharacterStart

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
FejdStartup.OnCharacterStart () (at <035307060cbb4b30b916cd82ebd80490>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <c9fb31c2eee14ce4aeb36e4c61e154d8>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <c9fb31c2eee14ce4aeb36e4c61e154d8>:0)
UnityEngine.UI.Button.Press () (at <67859b8eac9e4f3b99606821e32b26c6>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <67859b8eac9e4f3b99606821e32b26c6>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <67859b8eac9e4f3b99606821e32b26c6>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <67859b8eac9e4f3b99606821e32b26c6>:0)
UnityEngine.EventSystems.EventSystem:Update()

[Info   : Unity Log] 12/08/2022 19:20:38: OnCharacterStart

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
FejdStartup.OnCharacterStart () (at <035307060cbb4b30b916cd82ebd80490>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <c9fb31c2eee14ce4aeb36e4c61e154d8>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <c9fb31c2eee14ce4aeb36e4c61e154d8>:0)
UnityEngine.UI.Button.Press () (at <67859b8eac9e4f3b99606821e32b26c6>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <67859b8eac9e4f3b99606821e32b26c6>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <67859b8eac9e4f3b99606821e32b26c6>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <67859b8eac9e4f3b99606821e32b26c6>:0)
UnityEngine.EventSystems.EventSystem:Update()

[Info   : Unity Log] 12/08/2022 19:20:41: OnCharacterStart

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
FejdStartup.OnCharacterStart () (at <035307060cbb4b30b916cd82ebd80490>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <c9fb31c2eee14ce4aeb36e4c61e154d8>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <c9fb31c2eee14ce4aeb36e4c61e154d8>:0)
UnityEngine.UI.Button.Press () (at <67859b8eac9e4f3b99606821e32b26c6>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <67859b8eac9e4f3b99606821e32b26c6>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <67859b8eac9e4f3b99606821e32b26c6>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <67859b8eac9e4f3b99606821e32b26c6>:0)
UnityEngine.EventSystems.EventSystem:Update()

[Info   : Unity Log] 12/08/2022 19:20:46: OnCharacterStart

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
FejdStartup.OnWorldStart () (at <035307060cbb4b30b916cd82ebd80490>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <c9fb31c2eee14ce4aeb36e4c61e154d8>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <c9fb31c2eee14ce4aeb36e4c61e154d8>:0)
UnityEngine.UI.Button.Press () (at <67859b8eac9e4f3b99606821e32b26c6>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <67859b8eac9e4f3b99606821e32b26c6>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <67859b8eac9e4f3b99606821e32b26c6>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <67859b8eac9e4f3b99606821e32b26c6>:0)
UnityEngine.EventSystems.EventSystem:Update()

[Info   : Unity Log] 12/08/2022 19:20:55: show character selection

[Info   : Unity Log] 12/08/2022 19:20:55: UI Group status changed SelectCharacter = True

[Info   : Unity Log] 12/08/2022 19:20:57: UI Group status changed Menu = True

[Info   : Unity Log] 12/08/2022 19:20:59: Steam manager on destroy
`

**Comment by Proctalgia** [comment]
I can confirm this issue on my PC. When enabled it stops functionality of the start button

**Comment by chris-droney** [comment]
Same issue ever since Mistlands update. Randy has said on his twitter that he's working on patches for all his mods

**Comment by Sensang** [comment]
Oh.. my bad I could've sworn it said updated in nexusmods I assumed it was working on pc.
