### ISSUE TITLE
epic loot 0.9.0  bug

### ISSUE THREAD

**Issue by Taotaolxt** [RandyKnapp/ValheimMods#420]
1.在工作台对升级过的装备附魔，会给其继续升级。
2.在工作台上对升级过的装备，进行祷告会出现报错，屏幕卡住，按TAB能恢复，但是装备会直接满级，

**Comment by RandyKnapp** [comment]
Machine translation:

1. Enchanting upgraded equipment at the workbench will continue to upgrade it.
 2. When praying for upgraded equipment on the workbench, an error will be reported, and the screen will be stuck. Press TAB to restore it, but the equipment will be directly at full level.

**Comment by Taotaolxt** [comment]
Do you understand what I mean?

**Comment by Taotaolxt** [comment]
> 机器翻译：
> 
> 1. 在工作台上迷人的升级设备将继续升级它。
> 2. 在工作台上祈祷升级设备时，会报告错误，屏幕会卡住。按 TAB 键恢复它，但设备将直接处于满级。

Do you understand what I mean?

**Comment by Taotaolxt** [comment]
> Machine translation:
> 
> 1. Enchanting upgraded equipment at the workbench will continue to upgrade it.
> 2. When praying for upgraded equipment on the workbench, an error will be reported, and the screen will be stuck. Press TAB to restore it, but the equipment will be directly at full level.

Do you understand what I mean?

**Comment by RandyKnapp** [comment]
I do not, but I can test. Are you saying that the ENCHANTS get better when you upgrade an item?

**Comment by Taotaolxt** [comment]
> I do not, but I can test. Are you saying that the ENCHANTS get better when you upgrade an item?

1.For example, enchanting level 2 equipment will reach level 3 for free
2.Modifying the entry on an enchanted piece of equipment that has already been upgraded will result in an error, pressing the TAB key to recover, and the equipment will be upgraded to the highest level.

**Comment by RandyKnapp** [comment]
Yes I found the bug, thank you. I will work on a fix shortly

**Comment by Taotaolxt** [comment]
thank you

**Comment by Taotaolxt** [comment]
> Yes I found the bug, thank you. I will work on a fix shortly

thank you

**Comment by RandyKnapp** [comment]
This only happens when creative mode or debugmode free build is active.
