### ISSUE TITLE
EpicLoot 0.9.0 issue

### ISSUE THREAD

**Issue by ddxing1** [RandyKnapp/ValheimMods#422]
Hi, for some reason I'm not getting any drops from new mistlands mobs, it works for any other enemy though

**Comment by RandyKnapp** [comment]
If you have CLLC installed the mistlands mods don't drop anything. Best to
uninstall it (unfortunately) because the author is planning on making it
permanently incompatible with Epic loot.

**Comment by ddxing1** [comment]
got it, thanks

**Comment by ddxing1** [comment]
kinda sucks because these two mods were balancing each other out, it would get too easy without CLLS and too hard without EL
