### ISSUE TITLE
ItsJustWood.. err-bug?

### ISSUE THREAD

**Issue by Cronosus** [RandyKnapp/ValheimMods#43]
`[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Common.PrefabCreator.CreateRecipe (System.String name, System.String itemId, Common.RecipeConfig recipeConfig) (at <c4a7dcea9e824608a394a9f906977e99>:0)
Common.PrefabCreator.AddNewRecipe (System.String name, System.String itemId, Common.RecipeConfig recipeConfig) (at <c4a7dcea9e824608a394a9f906977e99>:0)
ItsJustWood.ItsJustWood.TryRegisterRecipes () (at <c4a7dcea9e824608a394a9f906977e99>:0)
ItsJustWood.ObjectDB_Awake_Patch.Postfix () (at <c4a7dcea9e824608a394a9f906977e99>:0)
(wrapper dynamic-method) ObjectDB.DMD<ObjectDB::Awake>(ObjectDB)
UnityEngine.GameObject:AddComponent()
FejdStartup:DMD<FejdStartup::SetupObjectDB>(FejdStartup)
FejdStartup:DMD<FejdStartup::Start>(FejdStartup)`

**Comment by tilkinsc** [comment]
I get the same error with EpicLoot

**Comment by RandyKnapp** [comment]
This was a previous incompatibility with PlantingPlus. Should be fixed in ItsJustWood 1.0.2
