### ISSUE TITLE
0.9的魔法效错误

### ISSUE THREAD

**Issue by NAJJZ** [RandyKnapp/ValheimMods#432]
首先感谢您创造了如此有趣的模组，但我跟我的朋友在游玩中发现了一个错误，我的朋友制作的装备在给予我时，“mod_epicloot_me_indestructible_suffix”会失去效果，变为可损坏的。其他的词条我并没有测试是否会出现这样的错误

**Comment by RandyKnapp** [comment]
I only speak English, can you please translate your issue?

**Comment by NAJJZ** [comment]
When the equipment made by my friend is given to me, "mod _ epic loot _ me _ indestructible _ suffix" will lose its effect. I didn't test whether there would be such an error in other terms.

**Comment by Vapok** [comment]
I would make sure that your translation files have been updated.  It could be you're missing a translation entry.
