### ISSUE TITLE
Mobs that have Instant death animations not dropping loot

### ISSUE THREAD

**Issue by mhundemer** [RandyKnapp/ValheimMods#433]
Not sure if this has been reported. Mobs such as Skeletons, Serpents, Deathsquitos, Leeches, Wraiths anything that doesn't die and ragdoll then explode will not drop loot.  This means that seekers, seeker brutes and gjalls will also not drop loot when inputed. I manually added them into the game and was able to get Dverger mobs to drop loot but all things with instant deaths won't drop for some reason.  Wonder if the game devs maybe changed the way they are done and unattached itself from the loot calculation maybe?

**Comment by RandyKnapp** [comment]
Do you have CLLC installed?

**Comment by mhundemer** [comment]
yes I have CLLC, hmmmm if they don't clash well with each other darn i like the combo.

**Comment by Devestatio** [comment]
CLLC currently only works with EL if you create a custom drop table in the yaml file of CLLC, in order for the EL items you want mobs to drop. Otherwise you will need to wait to see if/when a fix is put it.

There are videos showing how to do it, it's not too hard just time consuming.

**Comment by Vapok** [comment]
This has been resolved as of the 0.9.2 Epic Loot version.
