### ISSUE TITLE
Console Erro 0.9.1

### ISSUE THREAD

**Issue by HeberPcL** [RandyKnapp/ValheimMods#434]
`[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
EpicLoot.MagicItemEffects.StaggeringProjectileHit_Projectile_OnHit_Patch.Prefix (Projectile __instance, UnityEngine.Collider collider) (at <b35e4cf8e8b34b66853452b3a76b7a76>:0)
(wrapper dynamic-method) Projectile.DMD<Projectile::OnHit>(Projectile,UnityEngine.Collider,UnityEngine.Vector3,bool)
Projectile.FixedUpdate () (at <035307060cbb4b30b916cd82ebd80490>:0)
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object`

**Comment by Vapok** [comment]
Should be resolved with the 0.9.3 release.
