### ISSUE TITLE
HoneyPlus mod interaction

### ISSUE THREAD

**Issue by Devestatio** [RandyKnapp/ValheimMods#435]
Not sure which side is causing the problem, but posting to both to see who can fix it, this is being spammed non stop.

"[Warning: Epic Loot] Tried to get element for $custom_item_honeyneckjerky at 5,6, but element was null (total elements = 2)
[Warning: Epic Loot] Tried to get element for $custom_item_honeydeerjerky at 6,6, but element was null (total elements = 2)
[Error  : Unity Log] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack trace:
System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <695d1cc93cca45069c528c15c9fdd749>:0)
BetterUI.GameClasses.BetterHotkeyBar.PatchHotkeyBar (HotkeyBar& __instance, Player& player) (at <782a6fbf20064a6bb00c8bb10338286a>:0)
(wrapper dynamic-method) HotkeyBar.DMD<HotkeyBar::UpdateIcons>(HotkeyBar,Player)
HotkeyBar.Update () (at <035307060cbb4b30b916cd82ebd80490>:0)"

**Comment by Vapok** [comment]
This should be resolved with the 0.9.3 Release.
