### ISSUE TITLE
Epic Loot 0.5.7: Warning Unity Log: Objects under cursor

### ISSUE THREAD

**Issue by gitmitzu** [RandyKnapp/ValheimMods#45]
Getting this warning now on my console after updating to 5.7. Reverted back to 5.6 and the warning doesn't show up anymore. I also tested this with no other mods. I'm not really sure if it's affecting any gameplay but I just thought you should know

![image](https://user-images.githubusercontent.com/79719119/111006648-06cb5080-8342-11eb-8f94-461b82398cf1.png)

**Comment by RandyKnapp** [comment]
My bad, got a fix incoming

**Comment by RandyKnapp** [comment]
Fixed in 0.5.8
