### ISSUE TITLE
epicloot 0.9.3 Localization error

### ISSUE THREAD

**Issue by Taotaolxt** [RandyKnapp/ValheimMods#461]
“ReagentRare” cannot be localized properly

**Comment by Vapok** [comment]
Can you provide a bit more detail into the issue you're seeing and where you're seeing it?  What are you trying to set?

**Comment by Vapok** [comment]
Oh snipes... I see it.  Thanks for the report.

**Comment by Taotaolxt** [comment]
> 哦狙击...我看到了。感谢您的报告。

Ok, hope you can fix the localization soon, I like your mod very much,

**Comment by Vapok** [comment]
I've cut an updated one with the proper localization.  You can find that here: https://github.com/RandyKnapp/ValheimMods/releases/tag/v0.9.3.1

**Comment by Taotaolxt** [comment]
> I've cut an updated one with the proper localization. You can find that here: https://github.com/RandyKnapp/ValheimMods/releases/tag/v0.9.3.1
Thank you very much!! But which connection do I want to download!?

**Comment by Taotaolxt** [comment]
> I've cut an updated one with the proper localization. You can find that here: https://github.com/RandyKnapp/ValheimMods/releases/tag/v0.9.3.1

Thank you so much! It can already be used normally~!
