### ISSUE TITLE
Cannot complete bounties

### ISSUE THREAD

**Issue by dharkness** [RandyKnapp/ValheimMods#467]
I completed a couple of bounties before the Mistlands update, roughly several months ago. I picked up a few bounties yesterday and killed the targets, but the markers are still on the map, and Haldor won't let me turn them in. My friend tried this as well on the same server.

Has anything changed about how bounties work? In both that I acquired, the target appeared first without needing to fight any minions (deer and Brute).

**Comment by Vapok** [comment]
We have tested Bounties on Dedicated Servers extensively, and have found no issues with bounties on dedicated servers. 

However, in order for you to be able to turn in bounties or see that the bounties was "Vanquished", the following thing must be true.

**On dedicated servers, the server must be running the same version of EpicLoot and have the correct JSON files loaded on to it.**  

The JSON files are extremely important.

If you can't turn in bounties, it's because there is something off about the install of the mod on the dedicated server.

**Comment by dharkness** [comment]
I'm not running the server, but I would bet my friend didn't know about the JSON files. I certainly didn't. I assume those are only needed for the server and aren't installed with the regular mod installation? I'll let him know.

Thanks a ton for the quick update! I came back to list out my mods in case there's a clash, but I'll try this first and report back.

**Comment by Vapok** [comment]
The entire plugin "dll and json's" are needed on both client and server side.

**Comment by RandyKnapp** [comment]
Is Extended Item Data Framework installed as well? Can you see in the server startup logs that EpicLoot is loaded correctly?

**Comment by dharkness** [comment]
Good question. Now that I think about it, the server console probably doesn't know to install dependencies like Thunderstore on the client. I'll ask him, thanks!

**Comment by dharkness** [comment]
Okay, he installed EIDF and restarted, and the only errors in the logs are about shaders not being supported on the GPU, which seems reasonable for a dedicated server. The log has nothing about EpicLoot.

I rejoined, abandoned my existing bounties, and claimed another. I went there, killed the boar, and came back to Haldor, but no dice. The bounty is still in progress, and the icon is still on the map. Should there be a message when I kill the target, and should the icon disappear from the map immediately? Is it a problem if I one-shot the target? It saw me and rushed to attack, and I saw its name and health bar. Everything seems to work except detecting that I killed it.

I suspect there's a conflict with one of the other mods we're using (all updated for Mistlands except ValheimRAFT which I see got deprecated the other day, but I wasn't using it when I first noticed the issue). I'll see if I can figure out which one it is, if any, in an offline game. Here are the mods if anyone else has this issue:

* AnyPortal
* AutoRepair
* BepInExPack
* BiggerBoatMapRadius (tho I was running without this before)
* CraftFromContainers
* EquipmentAndQuickSlots
* FarmGrid
* FuelEternal
* HoneyPlus
* Jotunn
* MoreDefenses (I also ran without this)
* PlantEverything
* QuickerStack
* RecyclePlus
* TrashItems
* TripleBronze
* UnrestrictedPortals
* ValheimRAFT

Thanks for helping out, guys. This mod really is amazing and makes the game more interesting. <3

**Comment by Vapok** [comment]
Why don't you catch me on Discord.  https://discord.gg/randyknappmods 

This might be easier to do a screen share.  You've got a pretty similar mod list to what our gaming group runs on our dedicated server, and we're having no problem with bounties.  I've been able to solve these screen shares fairly quickly.

**Comment by dharkness** [comment]
OMG, I am _so sorry!_ 🙏  My friend didn't have the mod installed on the server. That never occurred to us since everything else was working just fine. 🤣
