### ISSUE TITLE
Epic Loot - Cheat Sword

### ISSUE THREAD

**Issue by FunkyBigdog** [RandyKnapp/ValheimMods#47]
So idk if you meant to leave this in the loot pool but my friend got this drop and well yeah xD, its op.

**Comment by RandyKnapp** [comment]
The only way they got it would be from generating one from the "magicitem" console command, right?

**Comment by FunkyBigdog** [comment]
He isn't very tech savvy so I never told him what the commands were to just spawn it in.  He said it dropped for him from one of the bosses.  I do have the custom raids mod downloaded and have custom events that spawn harder versions of the bosses.  I can double check with him to make sure but the times I asked him he said it dropped from a boss from one of those events while he was playing with another person.

**Comment by RandyKnapp** [comment]
What rarity is it?

**Comment by FunkyBigdog** [comment]
It is legendary (Teal).

**Comment by RandyKnapp** [comment]
Your friend cheated and is lying to you. There is no way for the game to
naturally roll a cheat sword at all, let alone a legendary one.

**Comment by FunkyBigdog** [comment]
Alright man.  I am just relaying this information as is.  I didn't think he would lie for something like this, its not like we are children here and I've known him for 10 plus years.  Is it possible that it dropped because the enemy level is higher than the base game?  Like most of the bosses in my events are level 5 or above to make it challenging for us.  But if you said that its not in the regular loot pool for the enemies than that's that as you created this mod.  Thank you for taking your time to look into this.
