### ISSUE TITLE
Epic Loot console spam error related to Legendary set effects

### ISSUE THREAD

**Issue by ApolloReaper** [RandyKnapp/ValheimMods#473]
Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ZNetScene.RemoveObjects (System.Collections.Generic.List`1[T] currentNearObjects, System.Collections.Generic.List`1[T] currentDistantObjects) (at <35c0f7aa1999477788815a7bf78200d7>:0)
ZNetScene.CreateDestroyObjects () (at <35c0f7aa1999477788815a7bf78200d7>:0)
ZNetScene.Update () (at <35c0f7aa1999477788815a7bf78200d7>:0)

This has been an ongoing thing for many players for close to a year now, your mod is amazing so pls put this as a high priority fix, it spams the console until your fps reaches 0

**Comment by Vapok** [comment]
HI there, I have tested this with both Legendary Sets and all of the Legendary Swords with effects and can not reproduce any error messages. 

Can you provide more of your log that might show more of a stack trace? Can you also provide your mod list as well as your JSON files that are being used?  And lastly, can you confirm the version of Epic Loot you are using?

**Comment by ApolloReaper** [comment]
so for right now i seem to have fixed it, it seems it was a bug with extended player inventory, after deleting it and starting the world without it then putting it back in i have yet to run into the error, hopefully it wont happen again but if it does ill be sure to include all the above you mentioned

**Comment by Vapok** [comment]
Thanks for the update. I'm going to close this one out for now.  Holler at us if you spot something.
