### ISSUE TITLE
Conflict with cooking

### ISSUE THREAD

**Issue by VikaCatova** [RandyKnapp/ValheimMods#474]
[Error  :   BepInEx] Could not load [Cooking 1.1.11] because it is incompatible with: randyknapp.mods.extendeditemdataframework
https://valheim.thunderstore.io/package/Smoothbrain/Cooking/1.1.11/

**Comment by VikaCatova** [comment]
With 1.1.10 working 
Its problem with cooking not in EDF

**Comment by Vapok** [comment]
This is a dependency that the module creator for Cooking 1.1.11 has placed on their mod.  They would have to remove the incompatibility for it to work.
