### ISSUE TITLE
Is this mod working on not Steam versions of the game?

### ISSUE THREAD

**Issue by hugonh** [RandyKnapp/ValheimMods#48]
Im trying to understand if this mod is working, i try to force cheat on console, but it doesnt spawn any item

I do have installed: BepInEx\Plugins\ExtendedItemDataFramework and BepInEx\Plugins\EpicLoot

**Comment by RandyKnapp** [comment]
Did you do "imacheater" first?

**Comment by hugonh** [comment]
Can you specifiy, please? Where can i check the steps

**Comment by hugonh** [comment]
Do you say about this? I already tried, nothing happens on invetory neither on ground
"""
Cheats
Enter these into the console (F5):

magicitem <rarity> <itemtype> <amount>: Roll a random magic item using the specified values. (alias: mi)
<rarity>: (String) One of: magic, rare, epic, legendary, random. If left empty, uses random.
<itemtype>: (String) The internal ID of an item. May be "random". If left empty, uses random.
<amount>: (Int) The number of magic items to roll. If the other values are set to random, rerolls that random item each time. If left empty, uses 1.
magicmats: Spawns a bunch of all the magic crafting materials
"""

**Comment by hugonh** [comment]
I still have SimpleRecycling; EquipmentAndQuickSlots; Spawnthat

Maybe its conflicting with [Spawnthat ](https://github.com/ASharpPen/Valheim.SpawnThat)mod?

**Comment by WiseHorror** [comment]
You need to type `imacheater` in the F5 console to enable cheats in the game, only then can you use the `magicitem` and `magicmats` commands

**Comment by hugonh** [comment]
> You need to type `imacheater` in the F5 console to enable cheats in the game, only then can you use the `magicitem` and `magicmats` commands

Thanks. it worked!!

**Comment by hugonh** [comment]
I guess by default still not working, i kill mobs, do chests, just working with console commands =(

**Comment by RandyKnapp** [comment]
Any red text in the log? Did you install the loottables?

**Comment by hugonh** [comment]
> Any red text in the log? Did you install the loottables?

No

Info   :   BepInEx] Loading [Extended Item Data Framework 1.0.0]
[Info   :   BepInEx] Loading [Epic Loot 0.5.11]
[Info   : Unity Log] Added ItemSet: Tier0Weapons
[Info   : Unity Log] Added ItemSet: Tier0Tools
[Info   : Unity Log] Added ItemSet: Tier0Armor
[Info   : Unity Log] Added ItemSet: Tier0Shields
[Info   : Unity Log] Added ItemSet: Tier0Everything
[Info   : Unity Log] Added ItemSet: Tier1Weapons
[Info   : Unity Log] Added ItemSet: Tier1Armor
[Info   : Unity Log] Added ItemSet: Tier1Tools
[Info   : Unity Log] Added ItemSet: Tier1Everything
[Info   : Unity Log] Added ItemSet: TrollArmor
[Info   : Unity Log] Added ItemSet: Tier2Weapons
[Info   : Unity Log] Added ItemSet: Tier2Armor
[Info   : Unity Log] Added ItemSet: Tier2Shields
[Info   : Unity Log] Added ItemSet: Tier2Tools
[Info   : Unity Log] Added ItemSet: Tier2Everything
[Info   : Unity Log] Added ItemSet: Tier3Weapons
[Info   : Unity Log] Added ItemSet: Tier3Armor
[Info   : Unity Log] Added ItemSet: Tier3Shields
[Info   : Unity Log] Added ItemSet: Tier3Tools
[Info   : Unity Log] Added ItemSet: Tier3Everything
[Info   : Unity Log] Added ItemSet: Tier4Weapons
[Info   : Unity Log] Added ItemSet: Tier4Armor
[Info   : Unity Log] Added ItemSet: Tier4Shields
[Info   : Unity Log] Added ItemSet: Tier4Everything
[Info   : Unity Log] Added ItemSet: Tier5Weapons
[Info   : Unity Log] Added ItemSet: Tier5Armor
[Info   : Unity Log] Added ItemSet: Tier5Shields
[Info   : Unity Log] Added ItemSet: Tier5Everything
[Info   : Unity Log] Added LootTable: Greyling
[Info   : Unity Log] Added LootTable: Greydwarf
[Info   : Unity Log] Added LootTable: Greydwarf_Elite
[Info   : Unity Log] Added LootTable: Greydwarf_Shaman
[Info   : Unity Log] Added LootTable: Troll
[Info   : Unity Log] Added LootTable: Skeleton
[Info   : Unity Log] Added LootTable: Ghost
[Info   : Unity Log] Added LootTable: Blob
[Info   : Unity Log] Added LootTable: BlobElite
[Info   : Unity Log] Added LootTable: Draugr
[Info   : Unity Log] Added LootTable: Draugr_Elite
[Info   : Unity Log] Added LootTable: Leech
[Info   : Unity Log] Added LootTable: Surtling
[Info   : Unity Log] Added LootTable: Wraith
[Info   : Unity Log] Added LootTable: Wolf
[Info   : Unity Log] Added LootTable: Hatchling
[Info   : Unity Log] Added LootTable: StoneGolem
[Info   : Unity Log] Added LootTable: Fenring
[Info   : Unity Log] Added LootTable: Deathsquito
[Info   : Unity Log] Added LootTable: Lox
[Info   : Unity Log] Added LootTable: Goblin
[Info   : Unity Log] Added LootTable: GoblinBrute
[Info   : Unity Log] Added LootTable: GoblinShaman
[Info   : Unity Log] Added LootTable: Serpent
[Info   : Unity Log] Added LootTable: Eikthyr
[Info   : Unity Log] Added LootTable: gd_king
[Info   : Unity Log] Added LootTable: Bonemass
[Info   : Unity Log] Added LootTable: Dragon
[Info   : Unity Log] Added LootTable: GoblinKing
[Info   : Unity Log] Added LootTable: TreasureChest_meadows
[Info   : Unity Log] Added LootTable: TreasureChest_blackforest
[Info   : Unity Log] Added LootTable: TreasureChest_forestcrypt
[Info   : Unity Log] Added LootTable: TreasureChest_fCrypt
[Info   : Unity Log] Added LootTable: TreasureChest_trollcave
[Info   : Unity Log] Added LootTable: shipwreck_karve_chest
[Info   : Unity Log] Added LootTable: TreasureChest_meadows_buried
[Info   : Unity Log] Added LootTable: TreasureChest_sunkencrypt
[Info   : Unity Log] Added LootTable: TreasureChest_swamp
[Info   : Unity Log] Added LootTable: TreasureChest_mountains
[Info   : Unity Log] Added LootTable: TreasureChest_plains_stone
[Info   : Unity Log] Added LootTable: TreasureChest_heath

**Comment by hugonh** [comment]
It doesnt show any option about enchantment, or drops, chests, etc. Just working with console commands, is something about this request. I extracted the files of File(folder) to a folder called EpicLoot

**Comment by WiseHorror** [comment]
Magic items don't drop every time. Try doing this:

1. Open console with F5
2. Type `imacheater` to enable cheats
3. Type `godmode` to become invincible
4. Type `spawn Greydwarf_Elite 10 3` to spawn some monsters
5. Type `killall` to kill them instantly
6. Check for any magic items

Try it a few times, if no magic items are dropped, there might be a conflict with some other mod you may have installed.

**Comment by hugonh** [comment]
> Magic items don't drop every time. Try doing this:
> 
> 1. Open console with F5
> 2. Type `imacheater` to enable cheats
> 3. Type `godmode` to become invincible
> 4. Type `spawn Greydwarf_Elite 10 3` to spawn some monsters
> 5. Type `killall` to kill them instantly
> 6. Check for any magic items
> 
> Try it a few times, if no magic items are dropped, there might be a conflict with some other mod you may have installed.

I guess its conflicted, because once dropped a hammer and it was blue, on a greydwarf, but already opened 10 chests on a dungeon, already killed dozens of skeletons, nothing special, just normal loot(bones, gold)

**Comment by WiseHorror** [comment]
Sounds to me like the mod is working fine, just looks like you got a bit unlucky. Skeletons don't have a good chance to drop magic items. Just keep playing and eventually you'll get them.
