### ISSUE TITLE
Cooking 1.1.11 issues with the Extended Item Framework

### ISSUE THREAD

**Issue by Syranth** [RandyKnapp/ValheimMods#488]
Receiving the following error launching the game:

[Error : BepInEx] Could not load [Cooking 1.1.11] because it is incompatible with: randyknapp.mods.extendeditemdataframework

**Comment by RandyKnapp** [comment]
We'll deprecate EIDF soonish

**Comment by Syranth** [comment]
Is there a workaround we can use to play? Sadly most of our group are cooks. haha

**Comment by RandyKnapp** [comment]
You can join the discord: https://discord.gg/randyknappmods and grab the 0.9.4 release candidate from #epicloot-releases. That version has deprecated EIDF and does not need to have it installed to run. The server AND all your group need the same version.

**Comment by Syranth** [comment]
Love you thiiiiiiiiiis much!!
