### ISSUE TITLE
Mistlands

### ISSUE THREAD

**Issue by nathanbwalters** [RandyKnapp/ValheimMods#492]
Love epic loot - can’t play valheim without it…. Latest patch for mistlands (0.9.3) - I don’t get any drops from mistlands creatures nor any drops of more recent armor/weapons from mountain caves through to mistlands. I’ve killed all bosses including queen with this character on this world seed… am I missing something? Thanks

**Comment by RandyKnapp** [comment]
Do you have CLLC installed?

**Comment by nathanbwalters** [comment]
Ah that will be it, knew I was doing something stupid. So installed with mod manager it should be good to go?

**Comment by nathanbwalters** [comment]
Thank you!!

**Comment by nathanbwalters** [comment]
Hmmm tested back in mistlands and so far no drops still… are drops rarer from seekers or should I be seeing something most drops?

**Comment by RandyKnapp** [comment]
Are you sure that Epic Loot is running? I wasn't asking about CLLC to make sure it was installed, it doesn't need to be. But Extended Item Data Framework DOES need to be installed for Epic Loot 0.9.3 to work

**Comment by nathanbwalters** [comment]
Yes, got that installed

**Comment by nathanbwalters** [comment]
![Uploading image.jpg…]()

**Comment by Vapok** [comment]
Make sure you've updated the JSON files.  The JSON files were also updated.
