### ISSUE TITLE
Files look right; bounties dont complete

### ISSUE THREAD

**Issue by kylefurby** [RandyKnapp/ValheimMods#496]
Hello!

I have epicloot installed on a gportal dedicated server. On both the client side and server side the mod as been installed. I see all files being the same. The only difference I see is the loot table file I edited on server side. 

Bounties have ceased to complete. When killed you see no "vanquished" nor does the marker go away. 

I have looked on your github and on the nexusmod forum and cannot find an issue past being how i installed it. but i see no issue in the installation. not seeing any errors in bepinex when starting; no indication of mod failure. 

Any idea on how i can go about looking where to solve this?

**Comment by Vapok** [comment]
So a couple things stick out. I recently helped someone having the same exact issue on a G-Portal server.

In G-Portal, are you using the Valheim+ modded version of their game?   If not, the game server won't start BepInEx and thus EpicLoot, regardless of how certain you are that the files are in the right spot, won't start.  Which is why the bounties aren't completing.

on G-Portal, you must activate Valheim+ in order for BepInEx to start which will then allow you to use other mods.

**Comment by kylefurby** [comment]
I have valheim plus enabled on the server and the clients all have one. 

It worked until about two days before the new year. Treasures still work, albeit bloody difficult to find some. Loot drops and works perfectly. 

We are using more modd and bepinex is running on everything and smoothly from what I can see.

**Comment by RandyKnapp** [comment]
Can you post your server log? There will be a file called "LogOutput.log" in the BepInEx directory on your server.

**Comment by kylefurby** [comment]
[LogOutput.log](https://github.com/RandyKnapp/ValheimMods/files/10370322/LogOutput.log)

**Comment by RandyKnapp** [comment]
You've got a syntax error in your epic loot files, not sure which one. Line 320 of your log is an epic loot exception. Plus you have a ton of Valheim+ errors. I don't see Epic Loot actually starting on your server.

**Comment by kylefurby** [comment]
That is odd. Everything outside of bounties work as intended.

**Comment by RandyKnapp** [comment]
The only thing that epic loot runs on the server is bounties. Everything
else is client authoritative.

**Comment by altaaro** [comment]
I have exactly same problem on my server, everything but bouties works. Killing the bounty boss does not activate anything

**Comment by RandyKnapp** [comment]
@altaaro Have you looked at your server logs? Can you see if EpicLoot is starting up or not?

**Comment by altaaro** [comment]
Love you man :) sometimes i should check easiest things. There was no plugin loading on server start. Seems like file was corrupted or something. After clearing the plugins files and copying them again it started. I will try to do some bounty and give a feedback.

**Comment by altaaro** [comment]
It's working :)

**Comment by Vapok** [comment]
Glad we got to the root of the issue. Have a good one!
