### ISSUE TITLE
Enchant table quantities incorrect and failed for enchant

### ISSUE THREAD

**Issue by plopyy** [RandyKnapp/ValheimMods#498]
Sacrifice moder pearl don't give shard
Enchant cost are incorrect
Upgrade cost are incorrect

I think something wrong with cost quantity ?

**Comment by RandyKnapp** [comment]
Can you share a screenshot please?

**Comment by ValheimReloaded** [comment]
I also noticed this. I can change the enchant cost but the quantity always says 1

**Comment by plopyy** [comment]
Hum for sacrifice, it's just me.

But for Enchanting:
In enchant table
https://i.imgur.com/TXbYkGa.png
In forge
https://i.imgur.com/JMTpXl6.png

And enchant failed, resources are consumed but the enchantment failed. The item didn't change

**Comment by ValheimReloaded** [comment]
![image](https://user-images.githubusercontent.com/50849175/211205829-6f19a0bf-d551-45c3-8b8c-c20fc88ea14a.png)
Its set to 5 dust in the configuration but shows up as 1 in Enchanting table

**Comment by RandyKnapp** [comment]
okay, thanks folks. I'll get a fix in
