### ISSUE TITLE
[???] Override for the CraftFromContainers version check.

### ISSUE THREAD

**Issue by aaroncblack** [RandyKnapp/ValheimMods#5]
The CraftFromContainers mod is getting pretty frequent updates.  Would it be possible to provide a config option for the version that is checked for?  For example, I'm using CraftFromContainers 1.0.3.

This would be a 'use at your own risk' option, for newer versions that you haven't tested against yourself.

Alternatively, I can just tweak and compile this mod myself, so its up to you whether you think this is worth it for most people

Thanks.

**Comment by Fundryi** [comment]
Have the same issue here


```
[Info   :  HarmonyX] Running ILHook manipulator on Vector2i Inventory::FindEmptySlot(bool topFirst)
[Info   :  HarmonyX] Writing prefixes
[Info   :  HarmonyX] Patching harmony-auto-c9b83e95-b64b-4e0b-ab7f-194ad1c9fad2 took 7ms
[Info   :   BepInEx] Loading [Improved Build HUD 1.0.1]
[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'CraftFromContainers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
```

**Comment by RandyKnapp** [comment]
What mod was this for?
