### ISSUE TITLE
Can not repair Armor.

### ISSUE THREAD

**Issue by ManuelKahle** [RandyKnapp/ValheimMods#50]
Hey there,

I have installed the Plugin/Mod EquipmentAndQuickSlots Version
*Last updated: Sat Mar 06 2021, 02:26:09* from r2modman.

Im unable to repair any armor now. I have also uninstalled the mod but it's still not working.
Here is a proof for this: https://i.postimg.cc/G2Rj86Nx/Unbenannt.png

**Comment by RandyKnapp** [comment]
Doesn't iron armor need forge level 2 to repair? Try building an upgrade and then let me know. Can you repair your bronze stuff?

**Comment by RandyKnapp** [comment]
I can repair all armor with both EpicLoot and EquipmentAndQuickSlots installed. Please message me again if you can provide more info.
