### ISSUE TITLE
Back with the console spam

### ISSUE THREAD

**Issue by ApolloReaper** [RandyKnapp/ValheimMods#502]
[LogOutput.log](https://github.com/RandyKnapp/ValheimMods/files/10369562/LogOutput.log)

**Comment by ApolloReaper** [comment]
it seems to trigger from a long range teleport

**Comment by RandyKnapp** [comment]
And this is on 0.9.3? Or the 0.9.4 from here or the discord? Do you have Ragnar's set? Do you use the ice axe attack?

**Comment by Vapok** [comment]
Please try Release 0.9.7 and see if the Console spam went away.  You can download the release candidate here: https://github.com/RandyKnapp/ValheimMods/releases/tag/v0.9.7-beta

**Comment by ApolloReaper** [comment]
sadly it did not and the null checking is adding some lag as well, also would like to apologize for the veinmine spam in that log
[LogOutput.log](https://github.com/RandyKnapp/ValheimMods/files/10419016/LogOutput.log)

**Comment by ApolloReaper** [comment]
ima honestly try a few things on a test world removing mods and what not

**Comment by ApolloReaper** [comment]
So it looks like its either a conflict with monsternomicon mobs, or just the mod in itself

**Comment by ApolloReaper** [comment]
so monsternomicon updated and looks like it fixed the conflict
