### ISSUE TITLE
Enchant tab doesn't work

### ISSUE THREAD

**Issue by Sluggasaurus** [RandyKnapp/ValheimMods#503]
My friends and I play on our own private server, we recently had to switch over from Valheim+ to OdinQOL due to SmoothBrain making their mods incompatible with V+

Sacrificing and Augmenting work fine, its just the Enchant tab that won't work for us and throws an error when trying to open said tab. Is this a compatibility issue since we switched? any help is appreciated, and I can give the full modlist if needed

**[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
EpicLoot.EpicLoot.IsNotRestrictedItem (ItemDrop+ItemData item) (at <12595b05c14542b187994bedef0ab72e>:0)
EpicLoot.EpicLoot.CanBeMagicItem (ItemDrop+ItemData item) (at <12595b05c14542b187994bedef0ab72e>:0)
EpicLoot.Crafting.EnchantTabController.GenerateEnchantRecipesForItem (ItemDrop+ItemData item) (at <12595b05c14542b187994bedef0ab72e>:0)
EpicLoot.Crafting.EnchantTabController.GenerateRecipes () (at <12595b05c14542b187994bedef0ab72e>:0)
EpicLoot.Crafting.TabController.SetActive (System.Boolean active) (at <12595b05c14542b187994bedef0ab72e>:0)
EpicLoot.Crafting.EnchantTabController.SetActive (System.Boolean active) (at <12595b05c14542b187994bedef0ab72e>:0)
EpicLoot.Crafting.CraftingTabs.OnTabPressed (EpicLoot.Crafting.TabController tab) (at <12595b05c14542b187994bedef0ab72e>:0)
EpicLoot.Crafting.TabController+<>c__DisplayClass10_0.<TryInitialize>b__1 () (at <12595b05c14542b187994bedef0ab72e>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <c9fb31c2eee14ce4aeb36e4c61e154d8>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <c9fb31c2eee14ce4aeb36e4c61e154d8>:0)
UnityEngine.UI.Button.Press () (at <67859b8eac9e4f3b99606821e32b26c6>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <67859b8eac9e4f3b99606821e32b26c6>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <67859b8eac9e4f3b99606821e32b26c6>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <67859b8eac9e4f3b99606821e32b26c6>:0)
UnityEngine.EventSystems.EventSystem:Update()**

**Comment by Bilkoo** [comment]
@Sluggasaurus did you fix this issue?
