### ISSUE TITLE
Equipment Tombstone missing

### ISSUE THREAD

**Issue by Eviltwentyseven** [RandyKnapp/ValheimMods#508]
After i died the last two times once in a Frost Cave and once outside in the Mountains when i came back to my corpse there was only my Item Tombstone and my Equipment was gone. When i died i saw two Tombstones but after getting through the portal to get my stuff it was gone. Also my 2 Buddies that played with me saw the normal two tombstones. Must have been despawned glitched away or is it possible that mobs destroy the tombstone? Really annoying issue. U have to Cheat via Console Command to get all my Armor and Utility Slot Back. It was two times in Multiplayer. My Budddy died some Minutes before and everything was fine. I'am the Serverhost if that helps. Never happened in Single Player. Maybe its an MP bug Maybe its because of the Mountain Biome Maybe its pure randomness i dont know :-) Thx in Advance

**Comment by tokurwacojestdostepne** [comment]
check around above and below - quite often when you die you can see tombstones as normal, but when you come back game locates them well above on nearest edge or below - especially in mountain biome

**Comment by Eviltwentyseven** [comment]
Believe me i looked everywhere around. The only thing i didnt do is started digging into the ground to maybe find it :D

**Comment by Vapok** [comment]
This happened to us in mistlands.. except the opposite.. the EAQS tombstone was visible... but the vanilla tombstone that had the rest of the inventory was gone.  We started digging at the spot where the EAQS tombstone was, and we found it lying on the inside of a hollow rock.
