### ISSUE TITLE
Previously enchanted gear is now unenchanted, and the feather fall enchantment no longer works. EpicLoot 9.6

### ISSUE THREAD

**Issue by Shenanigans7** [RandyKnapp/ValheimMods#510]
![currentmods](https://user-images.githubusercontent.com/122594363/212254649-c9c036b2-4db5-4369-b1fc-01640e61b64a.PNG)
![20230113010355_1](https://user-images.githubusercontent.com/122594363/212254770-06e43369-c413-45e3-a89d-d1bf35d8f329.jpg)
![20230113010405_1](https://user-images.githubusercontent.com/122594363/212254771-59e1f41c-2f49-447d-8bf4-091f44e44eff.jpg)
![20230113010423_1](https://user-images.githubusercontent.com/122594363/212254772-b3b91fde-cacb-4188-84a0-1a0b4b4ffec7.jpg)
![20230113010345_1](https://user-images.githubusercontent.com/122594363/212254773-ac99913e-beac-4488-89de-8bbfdcbfe494.jpg)
![20230113010352_1](https://user-images.githubusercontent.com/122594363/212254775-d5759642-9b21-476c-bdaf-62d03488edf1.jpg)

**Comment by tokurwacojestdostepne** [comment]
can confim below
- indestructible not working - but if you move item to different slot looks like working
- feather fall - wasn't working for friend yesterday, he gave me item and when i gave it back started working as normal, today stops working for me and didn't have time to check if swapping item with someone else repairs it

**Comment by Vapok** [comment]
> ![20230113010352_1](https://user-images.githubusercontent.com/122594363/212254775-d5759642-9b21-476c-bdaf-62d03488edf1.jpg)

@Shenanigans7 - Can you do me a huge solid.. and save your character locally, and then give me the fch file for Wulfgar?

You can find those files here: `\AppData\LocalLow\IronGate\Valheim\characters_local\Wulfgar.hcf`

**Comment by tokurwacojestdostepne** [comment]
revert to 0.9.5 didnt help, feather fall still not working 
some of previously enchanted items now are just legendary, without any attributes
indestructible items are flashing red ...

**Comment by Vapok** [comment]
Solved with Release 0.9.7 - https://github.com/RandyKnapp/ValheimMods/releases/tag/v0.9.7-beta
