### ISSUE TITLE
Indestructible no longer works

### ISSUE THREAD

**Issue by azeDevs** [RandyKnapp/ValheimMods#512]
Items with Indestructible now have a durability bar.

**Comment by MaddHatterHX** [comment]
> Items with Indestructible now have a durability bar.

I can confirm this is an issue.

**Comment by Vapok** [comment]
We have a fix incoming shortly.

**Comment by Vapok** [comment]
All of this is now fixed in 0.9.7.  Will be released soon.  Check Discord for new file.  (it's too large to attach here).
