### ISSUE TITLE
Unable to complete bounties after changing to version 0.9.6

### ISSUE THREAD

**Issue by mcfizzlestag** [RandyKnapp/ValheimMods#516]
I updated my linux server to EpicLoot to 0.9.6 from 0.9.5 and and bounties no longer would "Vanquish" when bounty + minions are killed.  Red circles would remain on map for every client.  Going back to the trader and abandoning the bounty will remove the map markers for them, but the bounties still remain in the "Active Bounties" list in the Compendium.

My installed mods (source in brackets at latest versions):
Epic Loot (Nexus)
Equipment and Quickslots (Nexus)
Extended Item and Data Framework (Nexus)
Valheim  Plus (Nexus)
TargetPortal (Thunderstore)

All clients are using the same versions of only the listed addons, 4 different systems have had similar issues

**Comment by Vapok** [comment]
Solved in 0.9.7 - https://github.com/RandyKnapp/ValheimMods/releases/tag/v0.9.7-beta

**Comment by Vapok** [comment]
Bounties have been tested in 0.9.7.  And found to be working as expected.

**Comment by mpawlowski** [comment]
I'm on 0.9.7 on a multiplayer server and see the same issue as described here. It might be a mod incompatibility since we are also using the mentioned mods, except for TargetPortal.

**Comment by heberholanda** [comment]
I have the same problem.
