### ISSUE TITLE
mobs not dropping normal items

### ISSUE THREAD

**Issue by Toyzukor** [RandyKnapp/ValheimMods#518]
tested the newest update & the last 2 had issue that some mobs not dropping normal items.  Like Trolls not dropping items, serpent didnt seem to either.  Draugers ive killed about a dozen and occasionaly will get epic loot but no normal drops.

**Comment by jadelyn1015** [comment]
I am having the same issue.

**Comment by lordfoulsplane** [comment]
Having the same issue as well.  When I kill trolls, no skins or gold.  When monsters kill monsters then there are the usual drops.  Noticed this with trolls, draugers plus some other mod monsters.  The forest boss doesn't drop the key or a trophy.

**Comment by Toyzukor** [comment]
We killed 6 elder Boss no key or trophies also.  10 more trolls with no drops but the deer boss is dropping antlers and occasionally a trophy On Jan 25, 2023, at 11:46 PM, lordfoulsplane ***@***.***> wrote:﻿
Having the same issue as well.  When I kill trolls, no skins or gold.  When monsters kill monsters then there are the usual drops.  Noticed this with trolls, draugers plus some other mod monsters.  The forest boss doesn't drop the key or a trophy.

**Comment by lordfoulsplane** [comment]
I tracked this issue in my case to the WackyEpicMMOSystem mod.  Also happened when I tried EpicMMOSystem by LambaSun.  Disabled both of those and I'm getting troll skins again.  Haven't tried the Elder boss yet.

**Comment by lordfoulsplane** [comment]
Toyzukor,

Thanks for the email.  I think in my case I've been barking up the wrong
tree.  I commented again on the issues page on Github:

I tracked this issue in my case to the WackyEpicMMOSystem mod. Also
happened when I tried EpicMMOSystem by LambaSun. Disabled both of those and
I'm getting troll skins again. Haven't tried the Elder boss yet.


Do you have any variant of the MMO system mod in place?

**Comment by Toyzukor** [comment]
I am using WackyEpicMMOSystem on the Client side, for the server i'm only running 2 mods: Better_Trader_Remake by Digitalroot
& ValheimRAFT by NexusTransfer.  I'll disable the Wacky Client side and see if that helps.
Thank you for the Suggestion

**Comment by Toyzukor** [comment]
Turning off WackyEpicMMOSytem fixed the drops on the server
