### ISSUE TITLE
magicitem command not dropping correct items

### ISSUE THREAD

**Issue by Starisho** [RandyKnapp/ValheimMods#523]
When typing the following "magicitem legendary MaceSilver 1" it drops a legendary wooden club. If I type "magicitem epic MaceNeedle 1" it drops an epic wooden club. If I type something such as "magicitem rare ArmorIronChest 1" it drops a rag tunic. It seems like the specified item parameter for this command can only spawn Tier0 gear.

This is with a fresh install of the mod.

![20230125213815_1](https://user-images.githubusercontent.com/33465053/214746505-b312f1d7-bfa9-457f-8076-48271608b555.jpg)
![20230125213835_1](https://user-images.githubusercontent.com/33465053/214746501-d8a04dd2-834e-4432-ae4f-e9a2f92adab0.jpg)
![20230125213958_1](https://user-images.githubusercontent.com/33465053/214746504-584519b3-480a-4a6b-a6ae-37c0e534f3df.jpg)

**Comment by RandyKnapp** [comment]
use the command `cheatgating` before using those commands to bypass the item gating system

**Comment by Starisho** [comment]
oh that's a thing? thanks haha
