### ISSUE TITLE
Incompatible With Vitality - Smoothbrain

### ISSUE THREAD

**Issue by bigreefer** [RandyKnapp/ValheimMods#526]
Smoothbrain mods dev says the issue is caused by the epic loot code and thus the incompatibility flag was put in place.

**Comment by RandyKnapp** [comment]
Unfortunately I am not planning on supporting Smoothbrain's mods

**Comment by bigreefer** [comment]
@RandyKnapp Do you mind if I ask why?

**Comment by RandyKnapp** [comment]
It's her prerogative if she wants to add the incompatibility. However, I have made Epic Loot in the way it needs to be made, and since it does something very similar to what Vitality does (i.e. increase base health) there's just going to be inherent incompatibility.

**Comment by bigreefer** [comment]
Makes sense, I've noticed she likes to use the incompatible flag quite a lot XD
