### ISSUE TITLE
[EpicLoot] No effects on magic items

### ISSUE THREAD

**Issue by CHANDLERNC** [RandyKnapp/ValheimMods#53]
picking up new or old items has no magic buffs on them including blue,green,and yellows is this a fixiable issue?

**Comment by RandyKnapp** [comment]
I don't understand the problem. Can you describe the steps or post a screenshot?

**Comment by nanonull** [comment]
hey @CHANDLERNC 
which plugins did you have installed? did you have BetterUI installed? 
It looks like you encounter known issue which is easy to fix
![image](https://user-images.githubusercontent.com/8210414/111866292-19aed800-8975-11eb-8f35-dbbbe07c27d2.png)
