### ISSUE TITLE
Remove EpicLoot reagent crafting from normal craftmenu now that we have dedicated bench

### ISSUE THREAD

**Issue by lupuleasa-core** [RandyKnapp/ValheimMods#534]
Talking about this one

![image](https://user-images.githubusercontent.com/5671120/218329330-0df9b527-767f-495b-8cf0-f70cd7723772.png)

It can be overwhelming for new players to see all those things.

The new epicloot crafting bench is great, and it has everything we need.

**Comment by lupuleasa-core** [comment]
Similarly, removing them from the normal workbench might also be a good idea, it spams a lot over there as well

![image](https://user-images.githubusercontent.com/5671120/218329441-1bb0609c-2edf-4f3e-b1e2-a79555f84d1e.png)

**Comment by RandyKnapp** [comment]
Yeah that's the plan, I wanted to give people a chance to get the new table built before I cut it off completely.
