### ISSUE TITLE
Error on game start (just before main menu) Nothing on enchant tab.

### ISSUE THREAD

**Issue by Archesr** [RandyKnapp/ValheimMods#54]
Game is able to run with the mod fine, however i did notice there is nothing on the enchant tab (no enchant recipes loading i think). Enchant tab looks like upgrade tab with the current item on upgrade tab on it and the upgrade button. No list to select 

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
EpicLoot.EpicLoot.TryRegisterPieces (System.Collections.Generic.List`1[T] pieceTables, System.Collections.Generic.List`1[T] craftingStations) (at <6ca368f5a2814eb2bc1d8802f8a23b90>:0)
EpicLoot.EpicLoot.TryRegisterItems () (at <6ca368f5a2814eb2bc1d8802f8a23b90>:0)
EpicLoot.ObjectDB_Awake_Patch.Postfix () (at <6ca368f5a2814eb2bc1d8802f8a23b90>:0)
(wrapper dynamic-method) ObjectDB.DMD<ObjectDB::Awake>(ObjectDB)
UnityEngine.GameObject:AddComponent()
FejdStartup:SetupObjectDB()
FejdStartup:DMD<FejdStartup::Start>(FejdStartup)

[LogOutput.log](https://github.com/RandyKnapp/ValheimMods/files/6137563/LogOutput.log)

Is there a way to narrow down the problem to see if its a clash with another mod? (hopefully not trying them out one by one as that would take a while XD)

**Comment by RandyKnapp** [comment]
There's a known conflict with Planting Plus that I haven't figured out. To get some enchanting recipes you need to sacrifice a boss trophy

**Comment by Archesr** [comment]
Is there a chance that [Useful Trophies](https://www.nexusmods.com/valheim/mods/123) and/or [Passive Forsaken Powers](https://www.nexusmods.com/valheim/mods/390) can cause conflic problems? or just with Planting Plus recipes just don't work? I sacrificed an Elk boss trophy and it didn't add any recipes in two worlds.

**Comment by Archesr** [comment]
Got it it's working now, did not think you meant sacrifice on the enchanting tab XD i did the"sacrifice on the stones XD
 thank you :D
