### ISSUE TITLE
EpicLoot  & Equipment and Quick Slots 

### ISSUE THREAD

**Issue by Devlap13** [RandyKnapp/ValheimMods#552]
Hi, 

both mods seem to stopped working properly. 
Epic Loot breaks ingame tooltips, they show only "tooltip".
Equipment and Quick Slots mess up your inventory and no items show up or the inventory.  Workbench is weired too. 

Cheers 
Chris

**Comment by jeroenwijdemans** [comment]
I seem to have the same issue. The logs show a lot of these errors:

```
[Error  : Unity Log] MissingMethodException: void UITooltip.Set(string,string)
Stack trace:
(wrapper dynamic-method) InventoryGrid.DMD<InventoryGrid::CreateItemTooltip>(InventoryGrid,ItemDrop/ItemData,UITooltip)
(wrapper dynamic-method) InventoryGrid.DMD<InventoryGrid::UpdateGui>(InventoryGrid,Player,ItemDrop/ItemData)
InventoryGrid.UpdateInventory (Inventory inventory, Player player, ItemDrop+ItemData dragItem) (at <afd4e3f8ab8b460f8ff25d476fbd573e>:0)
(wrapper dynamic-method) InventoryGui.DMD<InventoryGui::UpdateContainer>(InventoryGui,Player)
InventoryGui.Update () (at <afd4e3f8ab8b460f8ff25d476fbd573e>:0)
```

Also when you shift click a stack of items (when they are in your inventory only) the item of the stack sticks to your pointer disallowing you to do anything else. Splitting and merging in a container looks unaffected.

**Comment by eugenefedotov** [comment]
@Vapok I created PR for you. Could u check and merge this fix?

**Comment by eugenefedotov** [comment]
@Vapok mb u can check and merge?

**Comment by RandyKnapp** [comment]
I am not sure why you did the PR you did, @eugenefedotov . It just... undoes the fix that Vapok already did earlier? Were you building from source for your own game, and not updating Valheim?

**Comment by jeroenwijdemans** [comment]
@RandyKnapp thanks! Update 0.9.9 fixed all issues 🎉 

- no more error in the logs
- tooltips are back
- item no longer sticks to cursor after double click
