### ISSUE TITLE
[EpicLoot] Wrong loot on treasure chest? TreasureChest_plains_stone

### ISSUE THREAD

**Issue by WiseHorror** [RandyKnapp/ValheimMods#56]
The stone chests that spawn in the stonehenge-type structures have the same type of loot as chests from the Black Forest which is odd.

Here is an image: https://i.imgur.com/iMeVrDX.png

**Comment by RandyKnapp** [comment]
Yeah that's definitely wrong. I'll change it so it's the same as the heath one.

**Comment by RandyKnapp** [comment]
Fixed in 0.5.12
