### ISSUE TITLE
Quick_Stack_Store_Sort_Trash_Restock mod By Goldenrevolver compatibility with Auga mod

### ISSUE THREAD

**Issue by Loki4242** [RandyKnapp/ValheimMods#569]
Hello i found out that mod [Quick Stack Store Sort Trash Restock](https://valheim.thunderstore.io/package/Goldenrevolver/Quick_Stack_Store_Sort_Trash_Restock/) doesn't work with [Auga](https://valheim.thunderstore.io/package/RandyKnapp/Auga/). I think it's because it adds buttons to old interface. I wanted to ask if you can check it out and maybe make it work? Because i like both mods a lot and it would be cool to have them at the same time. Thanks for reading that. Have a nice day!

**Comment by GrubbyZebra** [comment]
second

**Comment by Vapok** [comment]
Please check with Golden on this.  I know last I heard he was working on adding in Auga compatibility.  the compatibility is written on the Mod's side.. not the Auga side.
