### ISSUE TITLE
More of a featurerequest.

### ISSUE THREAD

**Issue by xAhlen** [RandyKnapp/ValheimMods#57]
As you need 5 slots for armor and 3 for the extra quickslots. Isn't it possible to just remove the bottom row in the bag and use that for the armor and qs. Because it cleans up the ui but you don't risk of losing gear/items when removing the mod.

**Comment by RandyKnapp** [comment]
Thats...... exactly what I'm doing?

**Comment by xAhlen** [comment]
Oh. But i can still use that row? The backpack is still 8x4, and thats why i guess you lose gear if you have items on the 4th row and also have gear equiped.
