### ISSUE TITLE
[EpicLoot] Error with launching game

### ISSUE THREAD

**Issue by sch00lb0yq** [RandyKnapp/ValheimMods#58]
[Error  : Unity Log] Failed to decompress data for the AssetBundle 'C:\Program Files (x86)\Steam\steamapps\common\Valheim\BepInEx\plugins\EpicLoot\epicloot'.
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
EpicLoot.EpicLoot.LoadAssets () (at <8edd548f20734c1ab2f7a25ab40a57ab>:0)
EpicLoot.EpicLoot.Awake () (at <8edd548f20734c1ab2f7a25ab40a57ab>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()

Im trying to instal this on a online server, what am i doing wrong?
Plugins installed:
ValheimPlus
ValheimIHaveArrived
Modify_data_rate
Extendeditemdataframework
Discordnotifier
Customtextures

**Comment by RandyKnapp** [comment]
Huh. That's a new one. I dunno, I'll put it on the list to look at.
