### ISSUE TITLE
Character load failed after update Epic Loot Version 0.9.14

### ISSUE THREAD

**Issue by mspoehrle** [RandyKnapp/ValheimMods#582]
Valheim Version :  0.216.9
Valheim Plus Fork : Grantapher
Valheim Plus Fork Version : 0.9.9.16
Epic Loot Version :  0.9.14
Extended ItemDataFramework Version : 1.0.11

Valheim Plus Fork downloaded from Git Grantapher/ValheimPlus
Mods Epic Loot and Extended ItemDataFramework downloaded from Thunderstore.

After updating all Versions to latest build all characters will be loaded in default design without any items. It doesnt matter which one you select. it does not change anything.

In Unity Log I see the following warning for each character while loading: 

`[Warning: Unity Log] Error loading player data: /characters/walburga.fch, error: Field 'ItemDrop/ItemData.m_equiped' not found.`

If I remove Epic Loot / EIDF everything will be loaded fine without warnings. (but without the epic part :-) )

**Comment by HughODwyer90** [comment]
Ive the same issue

**Comment by mspoehrle** [comment]
Any other suggestions? Still not working with 0.9.18.

**Comment by HughODwyer90** [comment]
> Any other suggestions? Still not working with 0.9.18.

I uninstalled all mods and reinstalled and then it worked.

**Comment by mspoehrle** [comment]
Unfortunatly does this not work. :-(

**Comment by mspoehrle** [comment]
I have tried to create a new character. May be it was something with the existing characters. 

Still the same Error, but this time with a StackTrace

`[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
ExtendedItemDataFramework.ItemDrop_Load_Patch.Postfix (ItemDrop __instance) (at <d46560f89bca4fd5abdca2df20a8de64>:0)
(wrapper dynamic-method) ItemDrop.DMD<ItemDrop::Load>(ItemDrop)
Humanoid.Pickup (UnityEngine.GameObject go, System.Boolean autoequip, System.Boolean autoPickupDelay) (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
Humanoid.PickupPrefab (UnityEngine.GameObject prefab, System.Int32 stackSize, System.Boolean autoequip) (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
Humanoid.GiveDefaultItem (UnityEngine.GameObject prefab) (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
Humanoid.GiveDefaultItems () (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
FejdStartup.OnNewCharacterDone (System.Boolean forceLocal) (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) (at <80fe1a4e36fe44618284312cb721a597>:0)
UnityEngine.Events.CachedInvokableCall`1[T].Invoke (System.Object[] args) (at <80fe1a4e36fe44618284312cb721a597>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <80fe1a4e36fe44618284312cb721a597>:0)
UnityEngine.UI.Button.Press () (at <e97aac8d17514bea83fadfd039e9187a>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <e97aac8d17514bea83fadfd039e9187a>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <e97aac8d17514bea83fadfd039e9187a>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <e97aac8d17514bea83fadfd039e9187a>:0)
UnityEngine.EventSystems.EventSystem:Update()`

It seams to be something with EIDF what fails.

**Comment by HughODwyer90** [comment]
I heard there were issues with Valheim plus before. I can't confirm that though. Try without V+. Are you using nexus or thunderstore? Try launch with r2modman maybe?

**Comment by mspoehrle** [comment]
I download eveything from Thunderstore or directly from Git.

I will try without V+.

**Comment by HughODwyer90** [comment]
If that doesn't work you could try disabling all mods and then try turning them on individually to see which one causes the issue. I did that previously for a different issue. I use about 30 mods so I reenabled in groups of 3 until the issue occurred, and then narrowed it down from there.

**Comment by mspoehrle** [comment]
So the current Results:

Blank Valheim Installation
Just BepInEx
EL
EIDF

Same issue

**Comment by HughODwyer90** [comment]
Could potentially be some caching issues. Maybe have to delete the BepinEx folder and resinstall mods then?

**Comment by mspoehrle** [comment]
Installation was from Scratch. Removed all folders before installation.

**Comment by HughODwyer90** [comment]
Hmm. I can't think of anything else to resolve the issue. I wonder if your save file has been corrupted? Did you try make a new character and just see if that works as a test?

**Comment by mspoehrle** [comment]
Yes. I created a new one.  During creation process I will see the following Error in log.

`[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found. Stack trace: ExtendedItemDataFramework.ItemDrop_Load_Patch.Postfix (ItemDrop __instance) (at <d46560f89bca4fd5abdca2df20a8de64>:0) (wrapper dynamic-method) ItemDrop.DMD<ItemDrop::Load>(ItemDrop) Humanoid.Pickup (UnityEngine.GameObject go, System.Boolean autoequip, System.Boolean autoPickupDelay) (at <2959d3c128e64c61a08dcc9bb6744ec3>:0) Humanoid.PickupPrefab (UnityEngine.GameObject prefab, System.Int32 stackSize, System.Boolean autoequip) (at <2959d3c128e64c61a08dcc9bb6744ec3>:0) Humanoid.GiveDefaultItem (UnityEngine.GameObject prefab) (at <2959d3c128e64c61a08dcc9bb6744ec3>:0) Humanoid.GiveDefaultItems () (at <2959d3c128e64c61a08dcc9bb6744ec3>:0) FejdStartup.OnNewCharacterDone (System.Boolean forceLocal) (at <2959d3c128e64c61a08dcc9bb6744ec3>:0) UnityEngine.Events.InvokableCall1[T1].Invoke (T1 args0) (at <80fe1a4e36fe44618284312cb721a597>:0)
UnityEngine.Events.CachedInvokableCall1[T].Invoke (System.Object[] args) (at <80fe1a4e36fe44618284312cb721a597>:0) UnityEngine.Events.UnityEvent.Invoke () (at <80fe1a4e36fe44618284312cb721a597>:0) UnityEngine.UI.Button.Press () (at <e97aac8d17514bea83fadfd039e9187a>:0) UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <e97aac8d17514bea83fadfd039e9187a>:0) UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <e97aac8d17514bea83fadfd039e9187a>:0) UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction1[T1] functor) (at :0)
UnityEngine.EventSystems.EventSystem:Update()`

After that error Valheim does not proceed the creation process.

**Comment by HughODwyer90** [comment]
Sorry man. I don't think I've any more suggestions. Hopefully the Mod Devs have some further insight

**Comment by mspoehrle** [comment]
So, new Results.

I "played" with several versions of EIDF, which just to be saved within my Download Folder. ;-)

EIDF Version         |       Does it work
======================
1.0.11                   |         nope
1.0.10                   |         nope
1.0.8                     |          Yarp

Unfortunatly, when I run Valheim with 1.0.8 I get a ton of warnings like that one:

`[Warning:  HarmonyX] AccessTools.GetTypesFromAssembly: assembly System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 => System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0
  at HarmonyLib.AccessTools.GetTypesFromAssembly (System.Reflection.Assembly assembly) [0x0000d] in <474744d65d8e460fa08cd5fd82b5d65f>:0
[Warning:  HarmonyX] AccessTools.GetTypesFromAssembly: assembly System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 => System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0
  at HarmonyLib.AccessTools.GetTypesFromAssembly (System.Reflection.Assembly assembly) [0x0000d] in <474744d65d8e460fa08cd5fd82b5d65f>:0`

Game seams to run fine with no other issues as the warnings.

There may be a signifikant change from 1.0.8 to 1.0.10/1.0.11 that cause the error.

**Comment by mspoehrle** [comment]
The last update of Valheim fixed the problem. Now I am on latest versions of Epic loot and EIDF.

But now I have an other issue. But for this I will open a new ticket.

I will close this one
