### ISSUE TITLE
[EpicLoot] Missing description of effects when getting magic item

### ISSUE THREAD

**Issue by Blanketeer-X** [RandyKnapp/ValheimMods#59]
Playing with your latest version of it, and I noticed that even if you got the durability modifier on it, the info isn't showing up alongside with any other effects.

I noticed this when I had reinstalled this mod, so I'm curious on this behavior.
![valheim_Jls8hXzkWW](https://user-images.githubusercontent.com/24882034/111236897-8dd62e00-85b9-11eb-80f2-88596731d80b.jpg)
![valheim_nYzubI9xOV](https://user-images.githubusercontent.com/24882034/111236898-8e6ec480-85b9-11eb-9c10-bc6bebec12bd.jpg)
![valheim_XQwxSlzmYM](https://user-images.githubusercontent.com/24882034/111236899-8e6ec480-85b9-11eb-85b2-50a42eb53b19.jpg)

**Comment by RandyKnapp** [comment]
Turn off advanced tooltips by better ui

**Comment by Blanketeer-X** [comment]
Ah okay, now it's good. Forgot about that part. Thanks!
