### ISSUE TITLE
Enchantment tab empty

### ISSUE THREAD

**Issue by Ithyb** [RandyKnapp/ValheimMods#60]
Hi Mate, 

Thank you for the mod I love it so far, I am trying to resolve a possible bug issue on my end. 

I have uninstalled all other mods ( apart from dependency) however When I go into the game the enchant tab in the forge there is no items to upgrade.
The sacrifice tab works and I am carrying items that I think should be enchant-able,.

Could you suggest any fixes or is there anything I can provide to help troubleshoot this.
![2](https://user-images.githubusercontent.com/80751881/111288796-3eaefc80-8690-11eb-803c-0ec60c643801.JPG)
![1](https://user-images.githubusercontent.com/80751881/111288808-41115680-8690-11eb-9a48-ac7f46e89dd0.JPG)

Cheers Daniel

**Comment by RandyKnapp** [comment]
Have you sacrificed a boss trophy yet?

**Comment by R4DN3BUL4** [comment]
Having the same issue, but I have several other mods installed. Sacrificing was conflicting with the Valheim Recycle mod, tab wouldn’t even show up till I uninstalled it and have disabled the planting plus mod to make sure it still wasn’t affected. Haven’t tried sacrificing a boss trophy yet either.

**Comment by Ithyb** [comment]
HI mate, 

That was it fixed the issues and i could put my other mods back in.

Thank you for the help
