### ISSUE TITLE
[Epic loot] Unable to augment

### ISSUE THREAD

**Issue by Nomad221** [RandyKnapp/ValheimMods#603]
I attempted to augment a piece of gear and it left me stuck in the results menu with no new specs to choose from. I was also unable to close this menu and had to force close the game. It seems to be a persisting issue even after a fresh install or restart. My first intuition was due to the Extended Item Data Framework mod no longer being available. Any solutions?

**Comment by PrimeVoid** [comment]
I second not able to augment anything
The screen stays up only when augmenting, if I convert items it is able to be clicked away but augmenting the screen stays ontop. Also saving the world to keep the items doesnt save as if enchanting and augmenting are broken. 

I did notice that I was able to move my character around even while augmenting but it kept me in that screen.

![132142345](https://github.com/RandyKnapp/ValheimMods/assets/37918114/1b13aa41-01f6-4696-8cec-522aa204f044)

**Comment by Nomad221** [comment]
I have found the solution, there is another crafting piece called the enchanting table, that seems to have replaced the forge upgrade piece

**Comment by PrimeVoid** [comment]
Awesome, I did get this error code just in case if it helps. 
![1245253455](https://github.com/RandyKnapp/ValheimMods/assets/37918114/cadce5c1-83ea-4a08-aab9-2bc884b553bf)

**Comment by Vapok** [comment]
Please use the Enchanting Table in order to Enchant, Augment, and Disenchant. The crafting table functionality has been deprecated and currently the Augmenting functions have stopped working.  The legacy functionality will be removed in the next Epic Loot update.
