### ISSUE TITLE
EpicLoot Error

### ISSUE THREAD

**Issue by nakia0406** [RandyKnapp/ValheimMods#606]
Magic Enhancement
![epic_error](https://github.com/RandyKnapp/ValheimMods/assets/129840098/bca38403-c4b8-4d1f-96a2-566821abba6c)

**Comment by IrcDirk** [comment]
Seems there is a bug in newest EpicLoot. Configuration file `enchantingupgrades.json` has no Helheim entries, tho they should nod be required but they are. I just added Helheim entries by my self. Now the error doesnt show up.

@Vapok please fix this :)

**Comment by gkgk1235** [comment]
> 

can you tell how you did it? im having the same problem

**Comment by Vapok** [comment]
This should not be an issue with the latest versions of Epic Loot. But you will want to make sure that you completely and fully update the JSON files that are packaged with the mod
