### ISSUE TITLE
[EpicLoot] Disabling augmenting in the config doesn't remove the Augment tab in forges with the Enchanter.

### ISSUE THREAD

**Issue by Jenda44** [RandyKnapp/ValheimMods#609]
Hi, I wanted to disable augmenting items on my server as the system in my opinion completely breaks immersion and incentive to seek better loot. However, removing the augmentation option only removes the augment tab from the enchanting table, but not from a forge that has the Enchanter upgrade attached. Could you please look into this?

**Comment by Vapok** [comment]
As of EpicLoot 0.9.20 - All enchanting features have been removed form the Forge and Workbench.
