### ISSUE TITLE
This re-registers all the items again in the piece tables - why? 

### ISSUE THREAD

**Issue by yardik** [RandyKnapp/ValheimMods#61]
From this line: https://github.com/RandyKnapp/ValheimMods/blob/afbbba07851234ef605d5ea19f4a18807eb503ea/EpicLoot/EpicLoot.cs#L430

You proceed to add all items in the database to a list, then go and re-register all the pieces again. This will pick up other items created by other modders and likely create incompatibilities. Can you find another way to achieve what you are doing here? Perhaps create a list of all the items you want to modify and then just iterate that instead?

**Comment by RandyKnapp** [comment]
No?

That function does this:
1. Clean up display names of my new prefabs
2. Add all the new prefabs to the ObjectDB
3. Find every item in the ObjectDB that has a piece table, and save off a reference to it
4. Find every item in the piece tables that is a crafting station and save off a reference to it
5. Register all new prefabs that are pieces to the right piece table using the saved piece tables and crafting stations lists

Nothing in `TryRegisterPieces` modifies the ObjectDB, nothing is being added twice, see this line:
https://github.com/RandyKnapp/ValheimMods/blob/afbbba07851234ef605d5ea19f4a18807eb503ea/EpicLoot/EpicLoot.cs#L422

**Comment by yardik** [comment]
Sorry, I explained incorrectly. You're rebuilding all the piece tables in the workbenches again are you not?

//This creates a list of ALL items in m_items, including ones that may have come from other mods that initialize before yours.
            var pieceTables = new List<PieceTable>();
            foreach (var itemPrefab in ObjectDB.instance.m_items)
            {
                var item = itemPrefab.GetComponent<ItemDrop>().m_itemData;
                if (item.m_shared.m_buildPieces != null && !pieceTables.Contains(item.m_shared.m_buildPieces))
                {
                    pieceTables.Add(item.m_shared.m_buildPieces);
                }
            }

// This iterates all crafing stations and adds them to a list
            var craftingStations = new List<CraftingStation>();
            foreach (var pieceTable in pieceTables)
            {
                craftingStations.AddRange(pieceTable.m_pieces
                    .Where(x => x.GetComponent<CraftingStation>() != null)
                    .Select(x => x.GetComponent<CraftingStation>()));
            }

// This then rebuilds all the crafting table piece tables again - regardless of if they need to be rebuilt, and not just ones you've added or modified in your mod.
            TryRegisterPieces(pieceTables, craftingStations);

**Comment by RandyKnapp** [comment]
No I am not.

In your first snippet, `m_buildPieces` is a single object of type `PieceTable`. If it exists on that item and it does not currently exist in my table, I add a reference to it in the table. I am not create a list of all items in any way. (See how the `pieceTables` variable is a `List<PieceTable>`.)

`TryRegisterPieces` does not rebuild any tables at all, it only adds custom pieces from my new piece registry to existing piece tables.

**Comment by yardik** [comment]
> No I am not.
> 
> In your first snippet, `m_buildPieces` is a single object of type `PieceTable`. If it exists on that item and it does not currently exist in my table, I add a reference to it in the table. I am not create a list of all items in any way. (See how the `pieceTables` variable is a `List<PieceTable>`.)
> 
> `TryRegisterPieces` does not rebuild any tables at all, it only adds custom pieces from my new piece registry to existing piece tables.

Randy - I fail to see how iterating all the items in m_items and adding each of their piece tables is only adding custom pieces?

  foreach (var itemPrefab in ObjectDB.instance.m_items)  //iterating all (not just your custom items)

if (item.m_shared.m_buildPieces != null && !pieceTables.Contains(item.m_shared.m_buildPieces)) //are their pieces in pieceTable?
                {
                    pieceTables.Add(item.m_shared.m_buildPieces); //add them
                }

The above guarantees all items buildPieces get added to your custom table - since m_items is populated with all items.

Not sure where the check is that says 'only do this for the items that are from EpicLoot'?

**Comment by RandyKnapp** [comment]
I'm... just... getting a reference to all piece tables?

Like, okay. Write me a function that does this: returns a list of all piece tables in the game. What would you write? Would you iterate all items and see which ones have piece tables?

I'm not sure what you think I'm doing with this list, but please take a look at TryRegisterPieces. All it does is USE that list to find the piece tables by name, and hook up my new pieces to them. This is literally the only non-log reference to them in that method:

```cs
var pieceTable = pieceTables.Find(x => x.name == pieceDef.Table);
```

I just look up a piece table by name, man! That's all I'm doing with it!

**Comment by yardik** [comment]
Hey no worries Randy! To be fair, I hadn't dug through TryRegisterPieces yet - so I was just worried that the entire list of all piece tables in the game was being passed to it. Given what you've shown above, it seems fine. 

This all comes from some cats complaining that your mod and one of mine have incompatibilities, and having both of them enabled was causing some recipes to get corrupted/switched around. So I was digging through your code to see where that may have come from. In my case, I literally add a single new item to the ObjectDB (at the end of the list) and pieces table (a map prefab) to the hammer - and I do this Postfix on ObjectDB.Awake (also generating the hash and firing that into the item hash table).  Perhaps I'm missing something else that could be causing the errors.

**Comment by RandyKnapp** [comment]
Can we connect on Discord? I think I found out what the issue was.
RandyKnapp#2059
