### ISSUE TITLE
[EquipmentAndQuickSlots] CraftingWithContainers Broken

### ISSUE THREAD

**Issue by rcayne** [RandyKnapp/ValheimMods#62]
Hello,

Upon installing the latest version of your EquipmentAndQuickSlots mod, I was no longer able to craft with containers. 
I don't know what is causing this problem but this does not happen with the previous version. 
Pls fix this your mod is very useful!

Thank you,

**Comment by JourneyOver** [comment]
Craft with containers isn't the only mod that 2.0.0 broke, It seems to have broke Build Camera mod as well. Not sure what other mods it's broken yet, but glad to know it's not only me now that is having this issue.

**Comment by RandyKnapp** [comment]
Sorry folks, it was a big undertaking and modifies the player inventory in funky ways. The latest 1.x release may still work for you.

**Comment by RandyKnapp** [comment]
Build Camera is working fine for me.

**Comment by RandyKnapp** [comment]
Craft Build Smelt Cook Fuel Pull From Containers also works for me. Please get the 2.0.1 hotfix and see if that fixes your issue.

**Comment by JourneyOver** [comment]
@RandyKnapp Well build Camera is now working again, but CraftingWithContainers is still broken from the looks of things. This is with the 2.0.1 hotfix.

**Comment by RandyKnapp** [comment]
please send me your player.log and describe what you mean by "broken"

**Comment by JourneyOver** [comment]
@RandyKnapp 
[Player.log](https://github.com/RandyKnapp/ValheimMods/files/6161557/Player.log)
There is a fresh one from a fresh run, not sure why it is still telling me it's loading `2.0.0` for `Equipment and Quick Slots` unless you didn't change the version string? as I def updated to the `2.0.1 hotfix`.

Anyways what I mean by "broken" is that, it does not see anything from any chests when I either open my inventory or go to any of the crafting structures. Things will show either the count for what I have in my inventory, or just come up showing `{requirednumber}/0`. 

Disabling the `Equipment and Quick Slots` mod or downgrading back down to `1.0.5` makes the `craftingwithcontainers` mod work perfectly fine again. BTW the mod we are talking about is https://valheim.thunderstore.io/package/abearcodes/CraftingWithContainers/ and not https://www.nexusmods.com/valheim/mods/40 .. I'm sure @rcayne is talking about the one from thunderstore as well.

**Comment by rcayne** [comment]
Hello,

Thank you for your hard work on releasing the hotfix.
Unfortunately CraftingWithContainers is still not working fully.
Refueling/building from containers works but I cannot craft items in my workbench without having the required items in my inventory.

Hope this helps!

**Comment by JourneyOver** [comment]
@rcayne at least for now I would suggest switching over to `Craft Build Smelt Cook Fuel Pull From Containers` mod located here https://www.nexusmods.com/valheim/mods/40 at least until this issue is fixed.
