### ISSUE TITLE
MissingFieldException + warnings while loading EpicLoot mod

### ISSUE THREAD

**Issue by Wagadidou323** [RandyKnapp/ValheimMods#624]
Hi !

I just installed this mod via Thunderstore Manager and i have an error message + warnings while checking the console.

EpicLoot : v0.9.18 (because it's the last supported version on our Valheim server)
BepInExPack : v5.4.2105

![image](https://github.com/RandyKnapp/ValheimMods/assets/145479795/447879eb-e96d-4a4b-a204-2f6d155750b3)

If i try any MagicLoot commands in game, non of them are recognized :(

Did i missed some extra steps after installing the mod with the manager ?

Greetings,

**Comment by Vapok** [comment]
This error message is speaking to the fact that you have the wrong version of the mod for the wrong version of the game.

If you're on the live branch running 0.217.14 of Valheim, you'll want to use 0.9.22  of Epic Loot.
