### ISSUE TITLE
[EquipmentAndQuickSlots] Can't craft/Armor lost on death

### ISSUE THREAD

**Issue by CeyowenCt** [RandyKnapp/ValheimMods#63]
Cannot use cooking pot, get the error "inventory full" despite a near-empty inventory.

Also, my buddy using 2.0.0 died and lost his armor and quick slot items, weren't dropped on ground.

**Comment by RandyKnapp** [comment]
The entire inventory should have been in the tombstone. I have a fix for the crafting thing soon.

**Comment by NeonCarbide** [comment]
Can also confirm all items in extra slots add by `EquipmentAndQuickSlots` are lost/destroyed on death

Currently using version 2.0.0 of the mod

**Comment by RandyKnapp** [comment]
Do you have any mods that modify how things are done on death?

**Comment by RandyKnapp** [comment]
Also, both of you, please send me your Player.log file found at C:\Users\\<user>\AppData\LocalLow\IronGate\Valheim\Player.log

**Comment by RandyKnapp** [comment]
This is how it works for me: 

https://user-images.githubusercontent.com/3331569/111577255-26fa7580-876f-11eb-9532-4c628174962d.mp4

**Comment by kgabin** [comment]
can confirm. losing everyhting equipped and extra slots when i die. using newest 2.0.1

**Comment by NeonCarbide** [comment]
> Do you have any mods that modify how things are done on death?

I'm currently using my modpack, [NeonPack](https://valheim.thunderstore.io/package/NeonCarbide/NeonPack/). The only mod that I know for sure modifies death functions is FortifySkills, but I'm pretty sure that it doesn't touch anything on the inventory/item side of things, only skills.

> Also, both of you, please send me your Player.log file found at `C:\Users\<user>\AppData\LocalLow\IronGate\Valheim\Player.log`

Here's my [player.log](https://gist.github.com/NeonCarbide/1ba5b174e306915e9c587f97c925d7ac)

**Comment by RandyKnapp** [comment]
I think this is fixed in 2.0.2
