### ISSUE TITLE
[EquipmentAndQuickSlots] Enabling the mod causes the console-like panel to appear in the main menu

### ISSUE THREAD

**Issue by CoffinHunter** [RandyKnapp/ValheimMods#634]
Very similar to #https://github.com/RandyKnapp/ValheimMods/issues/608
Prerequisites: enable only latest bepinex (v 5.4.22) and EquipmentAndQuickSlots (v 2.1.7) and start Valheim.

After the main menu loads, the user sees a big console-like area, which is an issue. It is possible to start the game only with arrow navigation since some buttons are covered by the mentioned area. After the game started bepinex console outputs lots of errors.
Dropping some attachments aswell.

[Main menu](https://imgur.com/pPnJIcu)

[In the game](https://imgur.com/FLbuIDo)

Example of logs output:

`[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Raven.Update () (at <885fde5117a141d19eed8c0292c3d1fd>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Raven.Update () (at <885fde5117a141d19eed8c0292c3d1fd>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
KeyHints.UpdateHints () (at <885fde5117a141d19eed8c0292c3d1fd>:0)
KeyHints.Update () (at <885fde5117a141d19eed8c0292c3d1fd>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Minimap.UpdateShoutPins () (at <885fde5117a141d19eed8c0292c3d1fd>:0)
Minimap.UpdateDynamicPins (System.Single dt) (at <885fde5117a141d19eed8c0292c3d1fd>:0)
Minimap.Update () (at <885fde5117a141d19eed8c0292c3d1fd>:0)`

**Comment by Geksli** [comment]
confirm, same error

**Comment by CoffinHunter** [comment]
Works with the latest version 2.1.8
