### ISSUE TITLE
Html Color tag

### ISSUE THREAD

**Issue by meigrafd** [RandyKnapp/ValheimMods#635]
Just installed latest 0.9.30 to our dedicated server but we'r having an display bug with Item Discription e.g.:

![grafik](https://github.com/RandyKnapp/ValheimMods/assets/5682038/45ce93a7-0060-439d-af3b-214d533ef23b)
![grafik](https://github.com/RandyKnapp/ValheimMods/assets/5682038/12344846-5dba-4a53-89f6-f2015c320602)

using CustomUI from Nexus, but i guess thats only to move Hud elements - so its vanilla hud.

**Comment by OrianaVenture** [comment]
This is an issue with the VNEI tooltip, I have reported it to the mod author and it will get fixed on their end.

**Comment by Vapok** [comment]
Also, just to close the loop, I have doubly made sure that the color tags have been updated appropriately as of 0.9.32.
