### ISSUE TITLE
[Feature request] Minimal Status Effects - Expose Screen Space offsets through configuration file

### ISSUE THREAD

**Issue by Magnacoder** [RandyKnapp/ValheimMods#639]
Would you please make the screen space offsets exposed through a configuration file so that users can set the location on screen of their status effect indicators? 

https://github.com/RandyKnapp/ValheimMods/blob/main/MinimalStatusEffects/MinimalStatusEffects.cs

**Comment by Vapok** [comment]
Just checking here, but isn't that what the ScreenPosition config is for?

MinimalStatusEffectConfig.ScreenPosition = Config.Bind("General", "ScreenPosition", new Vector2(-230, -290),
                "The position offset from the top right corner of the screen.");

**Comment by Magnacoder** [comment]
Ah I'm sorry for the misunderstanding then on my part. Overlooked at this was supported by configuration. This can be closed.
