### ISSUE TITLE
Disabling Quick Slots in Config does nothing

### ISSUE THREAD

**Issue by SSyl** [RandyKnapp/ValheimMods#64]
When you set `Enable Quick Slots = false` in the config file, it doesn't actually disable the quick slots in-game.

All it does seem to do is stop you from using the hotkeys for the quick slots, but the actual quick slots are still there and usable. You can fill them with items and right click on them manually to use the item, just like you would an ordinary inventory slot.

I'm using version 2.0.1. The versions prior to 2.0 did disable the slots properly.

**Comment by RandyKnapp** [comment]
Fixed in 2.0.2
