### ISSUE TITLE
[Improvement Request] Minimal Status Effects - Make screen set offset ratio based from player's resolution

### ISSUE THREAD

**Issue by Magnacoder** [RandyKnapp/ValheimMods#640]
For minimal status effects, instead of arbitrary hard coded offsets, can you make the code either detect the user's resolution and ratio off that, or have a configuration setting that places the location of the status effects at different sets depending on hard coded resolution pairings?

Probably better if it were more dynamic to accommodate more resolutions. Please also remember there are some players who play without a minimap.

Thank you for the cool mod.
https://github.com/RandyKnapp/ValheimMods/blob/main/MinimalStatusEffects/MinimalStatusEffects.cs

**Comment by Vapok** [comment]
Thanks, we do have nomap options coming into the mod in the next update this week.

I'll see what I can do about positioning.

**Comment by Magnacoder** [comment]
Thanks for taking the feedback. This issue can be closed.
