### ISSUE TITLE
New update removed all items in added slot

### ISSUE THREAD

**Issue by Magnymbus** [RandyKnapp/ValheimMods#65]
Exactly what it says, when I loaded up the game with the new version, all Items in the armor and quick slots disappeared. I had to cheat to get them back.

**Comment by JourneyOver** [comment]
You was warned three different places! here https://github.com/RandyKnapp/ValheimMods/blob/main/EquipmentAndQuickSlots/README.md#-read-me-first-before-upgrading- and https://valheim.thunderstore.io/package/RandyKnapp/EquipmentAndQuickSlots/ and here https://www.nexusmods.com/valheim/mods/92 to unequip everything before upgrading from version 1.X.X to version 2.X.X

So this is not a bug or an issue at all.
