### ISSUE TITLE
[Equipment&QuickSlots] Players on server losing everything in extra slots.

### ISSUE THREAD

**Issue by Sketaful** [RandyKnapp/ValheimMods#685]
It's strange. I'm not even sure it's this mod's fault. But anyway. Players on my server loses what they have in the extra slots from time to time. Last night it happened again. 

It happens really random and very few times. Like 5 times during the last 3 months.

Any idea?

**Comment by l1m3r** [comment]
1. _how to get help on the internet_ \[1\]
2. I have an idea of what the problem could be but I'm not investing the time to write it down \[\*\*\*\] until you do 1. ...
3. what's missing: versions, circumstances, etc...

----

\[1\]
* [Justin Pot - "How To Ask Questions Online & Actually Get Answers"](https://www.makeuseof.com/tag/how-to-ask-questions-online-actually-get-answers-opinion/) (**from 2012!**)
* [Alex Eames - "How to ask for (and receive) technical help on the internet"](https://raspi.tv/2017/how-to-ask-for-and-receive-technical-help-on-the-internet)
* [wikiHow - "Formulating Your Question"](https://www.wikihow.com/Ask-a-Question-on-the-Internet-and-Get-It-Answered#Formulating-Your-Question)
* [Eric Steven Raymond / Rick Moen - "How To Ask Questions The Smart Way"](http://catb.org/~esr/faqs/smart-questions.html) ("*Copyright © **2001,2006,2014***" - *Web 0.0 warning*)
* and here's a video: [Ask for help like a pro! - DevConf.CZ 2023](https://www.youtube.com/watch?v=EkjGUNELwlE)

**Comment by Sketaful** [comment]
So much typing when you could just have posted a link to Google with the text "answer to your question here".

I mean, if you're gonna be a dick about it, why out down so much effort into it?

Now. As I wrote, I wasn't even sure if this mod was the problem or not. And I didn't write that it was. I asked if it was a "known" problem or not. You know, the kinda question that doesn't need a better description and doesn't need a log posted because it wasn't a cry for help searching for any problems, just a quizz if it was something already known.

But anyway. Found the problem, and it was my own mess up. I somewhere accidently installed this mod during some update when I wasn't supposed since I already moved on to an updated version.

Sometimes you just f**k up. But that's no reason not to be nice about it.

**Comment by l1m3r** [comment]
\[\*\*\*\] forgot something there: "_because it would be a shot in the dark. So_ "

And I had most of that post already at hand - not so much a written down explanation of a similar sounding problem I reproducible experienced with EaQS ~a year ago.

So you found/solved your problem and didn't close this "Issue" which makes it functionally spam - and I'm the dick? Well I guess then you're one too.

Oh and explaining what the actual problem was would've been nice to for anyone experiencing something similar...

**Comment by RandyKnapp** [comment]
Locked, I get email notifications on these and I don't need to listen to this kind of bickering
