### ISSUE TITLE
[Equipment&QuickSlots] Not working in bog witch public beta

### ISSUE THREAD

**Issue by MBrinks2239** [RandyKnapp/ValheimMods#697]
### Versions
Valheim version: 0.219.10
Mod version: 2.1.13

### Expected behavior:
When opening the game, all the characters are wearing their armor like before the update on the main screen
When entering the world, it functions the same as before the update

### Actual behavior: 
All characters are now not wearing any equipment if said equipment was equipped using the mod before the update. (All characters who equipped gear in vanilla valheim will still wear that gear)
When loading into a game, your POV is spinning at max speed and your console is filled with the following error:

```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
EquipmentAndQuickSlots.CustomHotkeyBar+HotkeyBar_UpdateIcons_Patch.UpdateIcons (HotkeyBar instance, Player player, System.Collections.Generic.List`1[T] m_items) (at <d4daa5809ad04e43bfc80f43b912ac1a>:0)
(wrapper dynamic-method) HotkeyBar.DMD<HotkeyBar::UpdateIcons>(HotkeyBar,Player)
EquipmentAndQuickSlots.HotkeyBarController+Hud_Update_Patch.Postfix (Hud __instance) (at <d4daa5809ad04e43bfc80f43b912ac1a>:0)
(wrapper dynamic-method) Hud.DMD<Hud::Update>(Hud)
```

**Comment by MBrinks2239** [comment]
## Update
Bog witch update has now officially left the public test branch and is now on main branch. A fix would be awesome!

**Comment by samwest7** [comment]
+1 on this. Unplayable on latest version with this mod as of today. Any items that were left in equipment / quick-slots are gone / not accessible. A fix would be greatly appreciated!

**Comment by ShiroMBY** [comment]
+1

**Comment by GamerRyan** [comment]
+1

**Comment by samwest7** [comment]
I do see an update to the mod was released. Seems to have fixed the issues I was having. I did save my character with the mod turned off which did mean I didn't get my items back when I enabled the mod again. However a simple rollback to an earlier character save file brought my items back :)   thank you!!
