### ISSUE TITLE
[EquipmentAndQuickSlots] Incompatibility between InventorySorting and version 2.0.0/2.0.1

### ISSUE THREAD

**Issue by Magnymbus** [RandyKnapp/ValheimMods#70]
Mod: [InventorySorting by end360](https://valheim.thunderstore.io/package/end360/InventorySorting/1.3.0/)

Mod Version: 2.0.1

Describe the bug

Inventory sorting ceases to function altogether within any inventory

How To Reproduce

join world
sort inventory
nothing happens, not even log errors

Additional details

the bug only occurs on version 2.0.0 / .1 of EquipmentAndQuickSlots

Am also listing this bug on the IS github. Will mention the issue here when done.

**Comment by Magnymbus** [comment]
InventorySorting issue number [13](https://github.com/end360/Valheim-Inventory-Sorting/issues/13#issue-834803405)

**Comment by PwrSrg** [comment]
**SAME issue here**.  This plugin KILLS the **InventorySorting** mod 😣, which unfortunately, I find more useful than THIS mod.
