### ISSUE TITLE
[EpicLoot] Problems with furnace and charcoal klin + can't see enchantments on most of the equipment I get/enchant

### ISSUE THREAD

**Issue by Moik-sama** [RandyKnapp/ValheimMods#74]
I went to kill the elder to get some iron, went back to my base using my boat, when I tried interacting with both Klin and Smelter/Furnace a message popped up saying I didn't have any processable items even when I had them on my inventory, I tried adding the iron scraps and wood to my utility belt (Z, V, B) and using them from there into both the klin and furnace and it worked.

I got a few items from bosses and mobs and some of them didn't say anything specific about having an enchantment even when they were yellow or blue, some items do say something like they have another type of damage for example a spear with either blunt or slashing damage plus the base piercing damage, and some bows also come with frost, fire and poison damage but most of the items say nothing, I tried enchanting my helmet and well it did turn blue but it doesn't really say anything new.

**Comment by RandyKnapp** [comment]
First issue should be fixed in latest version of EAQS.

What version of Epic Loot are you using?

**Comment by Moik-sama** [comment]
> First issue should be fixed in latest version of EAQS.
> 
> What version of Epic Loot are you using?

I'm using 1.0.0
