### ISSUE TITLE
Compiler Error CS1061

### ISSUE THREAD

**Issue by Release** [RandyKnapp/ValheimMods#76]
Sorry, but I can't compile this code.
I am getting errors when accessing fields with access modifiers such as "private".
As an example.
In the file "InventoryGrid_Patch.cs" there is a line:
`var element = __instance.m_elements[i];`
But "_m_elements_" is declared as "_**private** List <InventoryGrid.Element>_", where "_Element_" is declared as "_**private** class Element_".
Because of this, the "Compiler Error CS1061" error occurs.

**Comment by RandyKnapp** [comment]
You've got to get the publicized assemblies using MrPurple's plugin. https://github.com/MrPurple6411/Bepinex-Tools
