### ISSUE TITLE
[EquipmentandQuickSlotsv2.02] Issue with Equipment and Quickslots v2.x and other Mods (CraftingWithContainers and PreWorkout)

### ISSUE THREAD

**Issue by dave-sherman** [RandyKnapp/ValheimMods#77]
I use r2modman to manage my mods for Valheim, and ever since updating to ver. 2.x of EquipmentandQuickSlots I have been having issues with the following mods working properly:  https://valheim.thunderstore.io/package/abearcodes/CraftingWithContainers/1.0.13/ and https://valheim.thunderstore.io/package/Xenofell/PreWorkout/0.2.0/

I have uninstalled EquipmentandQuickSlots and both of the other mods work fine, installed the latest version - 2.02 of EquipmentandQuickSlots and both of the other mods quit working.  Once I uninstall EquipmentandQuickSlots 2.x the other mods start working properly again.

One more note:  When upgrading from 1.x to 2.x I did not see the patch notes in time because I use a Mod manager and lost all of my equipped gear and stacks of food.  I understand that's why I should make sure I don't upgrade until I see all of the patch notes, but please understand, people that are using r2modman to manage mods, the patch notes are not displayed like they are on the website.

Thank you for your time! 
[LogOutput.log](https://github.com/RandyKnapp/ValheimMods/files/6173411/LogOutput.log)
[Player.log](https://github.com/RandyKnapp/ValheimMods/files/6173417/Player.log)

**Comment by Scoottie949** [comment]
I'm so glad I found this! Hello guys, just wanted to say I was also having this same problem. Also I love mod, it's amazing, thankyou for all for hard work and time you put into this for everyone to enjoy!

Much love and happiness Randyknapp
