### ISSUE TITLE
[EquipmentandQuickSlots] Weapons/Tools lose their m_equiped value on world load

### ISSUE THREAD

**Issue by SSyl** [RandyKnapp/ValheimMods#78]
Whenever you restart the game or load up a world, any weapons or tools you were using before you quit the game will have `ItemDrop.ItemData.m_equiped` set to `false`, even though the weapon/tool is still in your hand and usable.

For example, let's say I equip a Pickaxe in game. The pickaxe will get equipped properly and the `m_equiped` value will be set to true. You can verify this in the GUI as well because the Ppckaxe will have the blue background behind it indicating that it's equiped.

If you leave the game and load the world again, the pickaxe will still be equipped (as expected), but `m_equiped` will be `false`. You can verify this in the GUI again by seeing the pickaxe doesn't have the blue equipped background behind it.

I could see this conflicting with other mods if they might check to see if a weapon/item/tool is equipped via that field or `Inventory.GetEquipedItems()`.

I'm currently making a mod that interacts with equipped weapons and noticed this. I switched to using `Player.m_localPlayer.GetRightItem()` and `GetLeftItem()`, since they're more appropriate for me anyway.

**Comment by RandyKnapp** [comment]
Great report, I'll look into it, thanks
