### ISSUE TITLE
[EquipmentandQuickSlots] Can't scroll through crafting recipes with gamepad

### ISSUE THREAD

**Issue by ramonsantana** [RandyKnapp/ValheimMods#79]
Having issues with the crafting recipe window with the mod, made a video of the issue

https://user-images.githubusercontent.com/26915006/111858938-8b017300-8902-11eb-9c5a-6a73c5e31106.mp4

**Comment by chathamdl** [comment]
I will close my request I am having the same problem as this with my gamepad.  Thanks Randy
