### ISSUE TITLE
Enchantment Tab wont load for ''some'' player

### ISSUE THREAD

**Issue by sch00lb0yq** [RandyKnapp/ValheimMods#80]
As i updated the plugin to its newest version (5.16), i came across a problem. Not knowing at first sight everything was working perfectly for me as the server owner. After a while i got some member that werent able to see their enchanting tab on the forge. 
I stopped my server tested it and found out that with some characters on my pc i could see it but with some others i couldnt.

Hope this makes sence and helps you in the development as for me 5.16 is not playable as 50% of my members are not seeing the enchantment tab anymore (updated from 5.12)
- both members the plugin was working and not working didnt have any cmd errors
- same pc: character 1 everything worked, character 2 it didnt
**Present Plugins:**
- ForcedPvP
- SimpleRecycle
- BetterUI
- ExtendedItemDataFrameWork
- Quickconnect
- IHaveArrived
- ValheimPlus
- ValheimStands

**Comment by FunkyBigdog** [comment]
My friend is having a similar issue, I am able to see and enchant things, but he is not.  We both just updated to the most recent version of EpicLoot.  He already had sacrificed the boss heads and nothing is showing.

**Comment by nanonull** [comment]
@sch00lb0yq @FunkyBigdog hey, can you check if Enchanter upgrade was built and connected to the Forge (please refer to image below)?
I installed all plugins except ValheimPlus and was able to see Enchant tabs with brand new character without any magic recipes available and without sacrificing boss trophy:
![image](https://user-images.githubusercontent.com/8210414/111888021-98415f00-89e1-11eb-93fa-95134cfba668.png)

**Comment by RandyKnapp** [comment]
This is an interesting bug, I'll be looking at it soon. If the other players build an Enchanter themselves, does it fix the issue? What about the artisan table, does it happen with that too?

**Comment by NewFake** [comment]
Have the same issue. Single Player World
![NoEnchant](https://user-images.githubusercontent.com/28830055/112164320-766cf580-8bf6-11eb-858e-cb372e125aa8.jpg)

**Comment by RandyKnapp** [comment]
Thank you all for your help looking at these issues. Please send me your player logs! (you can upload to pastebin)

Some things to try:
- Make sure you are on the latest version of EpicLoot (6.0.3 as of 3/23/21)
- Please ensure that all players have exactly the same mods of exactly the same versions
- Try to reproduce this with ONLY EpicLoot and its dependencies installed
- Try to reproduce this without SimpleRecycling installed

**Comment by NewFake** [comment]
https://pastebin.com/ABMe1uVu

> Thank you all for your help looking at these issues. Please send me your player logs! (you can upload to pastebin)
> 
> Some things to try:
> 
> * Make sure you are on the latest version of EpicLoot (6.0.3 as of 3/23/21)
> * Please ensure that all players have exactly the same mods of exactly the same versions
> * Try to reproduce this with ONLY EpicLoot and its dependencies installed
> * Try to reproduce this without SimpleRecycling installed

**Comment by NewFake** [comment]
Just unlocked Augmenter and it seems its working fine.

**Comment by FunkyBigdog** [comment]
So my friend has been going through a bunch for a little so I couldn't test it whether or not having him craft the build pieces did anything.  As with the new update that came out we came across a different issue where his world was different and such.  After removing the Data Rate Modifier that we have been using for a while it fixed the world.  After his regular world returned I had him craft the things himself and it looks like its working now but idk what the actual cause is.  But if anyone is having issues with their worlds try removing the Data Rate Modifier mod as it probably does not work anymore due to the network changes in the update that came out recently.

**Comment by Jdawg6922** [comment]
same issue as above , the tabs are there .. but everything is blank .. even after sacrifing the eikthyr head

https://pastebin.com/UtehQhJC

**Comment by sch00lb0yq** [comment]
So I’ve figured the issue that “might” cause this to happen:
After updating into the last version of EpicLoot I edited the config file. We had the setting set to “true” where you needed to sacrifice all the needed items to actually Be able to enchant. This was why people who had the items weren’t able to “craft/enchant” a magic item. So I suggest make sure you craft/sacrifice all the items needed to enchant first to have it unlock the actual enchanting!
