### ISSUE TITLE
[EpicLoot] Balance suggestion

### ISSUE THREAD

**Issue by Salty-Panda** [RandyKnapp/ValheimMods#83]
### Problem 
 
Currently, on-off effects like Poison Protection or Indestructible have the same weight as other ones, despite being significantly stronger due to their nature of not relying on secondary roll for effect's actual value.
So when we get any other effect we still can get something more or less useful, but binary enchantments always provide full value.

 ### Idea
  
 - First roll for effect's strength, then for the effect itself. Only if rolled strength is past certain threshold consider on-off effect like Indestructible.
 - Or in order not co complicate, just make one more roll.
 So e.g. you need to roll {0,1} >= 0.67 in order to have those binary enchantments included on the following rolls.
 - Make binary enchantments arbitrarily rarer

**Comment by RandyKnapp** [comment]
Good feedback. Fortunately I predicted that this would need to be the case, so there is already a SelectionWeight property for the magic effect definitions. I can play with it a little bit in an future update.
