### ISSUE TITLE
[EpicLoot] 0.6.3 - UIs broken + enchanting materials deleted

### ISSUE THREAD

**Issue by NeonCarbide** [RandyKnapp/ValheimMods#86]
Currently using [NeonPack 2.1.0](https://valheim.thunderstore.io/package/NeonCarbide/NeonPack/)

[Demonstration](https://www.dropbox.com/s/vb4uof74gjg2knd/EpicLoot0.6.0-Bugs.mp4?dl=0)

There's quite a few bugs demonstrated in the video, mostly to do with UI, however I have also been having an issue regarding the Enchanting tab never showing recipes despite having sacrificed numerous enchanted items and boss trophies (Eikthyr)

Here is my [Player.log](https://gist.github.com/NeonCarbide/78cd25a1402781325565a54f5fc87f1f) from the session of the video recording, which is the same session I discovered that my enchanting materials had been removed from my chests

Let me know if you need anything else

**Comment by RandyKnapp** [comment]
Please update to the latest version of EpicLoot (currently 0.6.3). The 0.6.0 version had serious problems that were addressed in later versions.

**Comment by NeonCarbide** [comment]
I've updated to 0.6.3 and am still noticing quite a few issues regarding characters with previous interactions with the mod

[Demonstration](https://www.dropbox.com/s/s46fmxbrlvn38x1/EpicLoot0.6.3-Bugs.mp4?dl=0) | [Player.log](https://gist.github.com/NeonCarbide/5b3cf8906a24852b205de9ba16fabc60)

However, I don't seem to be having any issues with characters that haven't had any interaction with the mod before now

I haven't tested new characters, only my main character and a character I use for debugging my modpack
