### ISSUE TITLE
[EpicLoot] Issues when using on a dedicated server

### ISSUE THREAD

**Issue by jasonmbrown** [RandyKnapp/ValheimMods#88]
`[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
EpicLoot.Crafting.RecipesHelper.SetupRecipes () (at <1a6ba44b6109460e98e1a48dfbef60d6>:0)
EpicLoot.EpicLoot.TryRegisterRecipes () (at <1a6ba44b6109460e98e1a48dfbef60d6>:0)
EpicLoot.ObjectDB_CopyOtherDB_Patch.Postfix () (at <1a6ba44b6109460e98e1a48dfbef60d6>:0)
(wrapper dynamic-method) ObjectDB.DMD<ObjectDB::CopyOtherDB>(ObjectDB,ObjectDB)
FejdStartup.SetupObjectDB () (at <64ceb8e535bf4a63b40d2371ecc128a4>:0)
FejdStartup.Start () (at <64ceb8e535bf4a63b40d2371ecc128a4>:0)`

That's the First error. Then it starts spamming the following error nonstop (I think this is due to the dedicated server not having a UI? But im honestly not too sure.)

```[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
FejdStartup.UpdateCursor () (at <64ceb8e535bf4a63b40d2371ecc128a4>:0)
FejdStartup.Update () (at <64ceb8e535bf4a63b40d2371ecc128a4>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ZInput.IsGamepadActive () (at <a1ec94a1bc6248789ca1f6e6556f8371>:0)
UIGroupHandler.Update () (at <4327ccad071449009511542e645ff851>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
FejdStartup.UpdateCursor () (at <64ceb8e535bf4a63b40d2371ecc128a4>:0)
FejdStartup.Update () (at <64ceb8e535bf4a63b40d2371ecc128a4>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ZInput.IsGamepadActive () (at <a1ec94a1bc6248789ca1f6e6556f8371>:0)
UIGroupHandler.Update () (at <4327ccad071449009511542e645ff851>:0)`

**Comment by RandyKnapp** [comment]
What version of Epic Loot are you using? Can you confirm that a file called recipes.json exists in the same directory as EpicLoot.dll?

**Comment by jasonmbrown** [comment]
I was using version 0.6.3 off the nexus page, I copied all the files alongside the dll. Ive removed the mod from my server for the time being however I believe it did have the recipes.json file in the bepinex Plugins folder.

**Comment by GalacticRuler** [comment]
not using Epic Loot but I'm also getting this error spam
