### ISSUE TITLE
[EpicLoot-Addon-MCE 1.0] Could not be instantiated!

### ISSUE THREAD

**Issue by jnelson76** [RandyKnapp/ValheimMods#92]
Updated server to bepenix 5.4.9
installed epicloot
installed epicloot MCE
installed modconfigenforcer, but I'm getting this error on server start up.  All the other plugins loaded.  The .dll has the same permissions on it as the rest.

[Info   :Valheim Plus] Configuration file loaded succesfully.
Mar 25 13:33:58 valheim start_server_bepinex.sh[23410]: [Info   :Valheim Plus] ValheimPlus [0.9.6] is up to date.
Mar 25 13:33:58 valheim start_server_bepinex.sh[23410]: [159B blob data]
Mar 25 13:33:58 valheim start_server_bepinex.sh[23410]: [Info   :   BepInEx] Loading [Extended Item Data Framework 1.0.0]
Mar 25 13:33:58 valheim start_server_bepinex.sh[23410]: [151B blob data]
Mar 25 13:33:58 valheim start_server_bepinex.sh[23410]: [136B blob data]
Mar 25 13:33:58 valheim start_server_bepinex.sh[23410]: [Info   :   BepInEx] Loading [Epic Loot 0.6.3]
Mar 25 13:33:58 valheim start_server_bepinex.sh[23410]: [134B blob data]
Mar 25 13:33:58 valheim start_server_bepinex.sh[23410]: [134B blob data]
Mar 25 13:33:59 valheim start_server_bepinex.sh[23410]: [Info   :   BepInEx] Loading [Epic Loot Addon - MCE 1.0.0]
Mar 25 13:33:59 valheim start_server_bepinex.sh[23410]: [144B blob data]
Mar 25 13:33:59 valheim start_server_bepinex.sh[23410]: The script 'EpicLoot_Addon_MCE.EpicLoot_Addon_MCE' could not be instantiated!
Mar 25 13:33:59 valheim start_server_bepinex.sh[23410]: (Filename:  Line: 227)

**Comment by RandyKnapp** [comment]
Hmmm, not really sure how this is happening. Hang tight, I'm probably going to integrate it into the main mod anyway.
