### ISSUE TITLE
Asset bundle generation 

### ISSUE THREAD

**Issue by BKorenek** [RandyKnapp/ValheimMods#94]
Hey, I'm relatively new to C#, and certainly new to Unity. I'm attempting to generate a prefab bundle for the Jam plugin. What I'm doing is going into ValheimUnity, creating a prefab and then building the project. 

I'm pulling the ValheimUnityBuild\ValheimUnity_Data\sharedassets0.assets and renaming it to jamassets for the plugin, but I'm getting an error that the header can't be read. 

Wondering if you may be able to share your process for asset bundle generation?

**Comment by RandyKnapp** [comment]
So what I do is assign an asset to an asset bundle using the little asset bundle selector in the bottom right corner of Unity. Then I put a little script in Assets/Scripts/Editor to make building easy: https://github.com/RandyKnapp/ValheimMods/blob/main/ValheimUnity/Assets/Scripts/Editor/EditorUtils.cs

Then I just build in unity. When I build in Visual Studio, I copy the asset bundle to the plugins dir along with my mod dll.

**Comment by BKorenek** [comment]
Just saw that Mod menu, if only i was a little sooner i coulda saved you a few minutes, really appreciate your time
