### ISSUE TITLE
[ImprovedBuildHud] Misnamed setting "Can Build Amount Color = ({0})"

### ISSUE THREAD

**Issue by DesertDwarf** [RandyKnapp/ValheimMods#95]
I don't think you meant to include the word 'color' at the end of this setting name.

`Can Build Amount Color = ({0})`

It looks like instead of having "Can Build Amount" and "Can Build Amount Color," you had a brain-fart and accidentally combined two setting names into one.

I looked at your current source, which seems to be at version 1.0.3, and it looks it creates the config file correctly with four settings, not three (in the awake() function). However, Thunderstore has 1.0.2. In fact,  the zip file here on GitHub is also 1.0.2. Maybe 1.0.3 is ready for release and you were just so busy cranking out awesome mods that you forgot to compile and upload the 1.0.3 update? :-)

**Comment by RandyKnapp** [comment]
I honestly can't remember, but thanks for pointing this out.
