### ISSUE TITLE
[EquipmentAndQuickSlots v2.0.4] Lost all items in equipment slots on death

### ISSUE THREAD

**Issue by evulray** [RandyKnapp/ValheimMods#96]
I fell down from a huge rock in Plains with full inventory. My mate looted portal mats from my corpse, and when I came back, I could only recover items that was in my regular inventory. Armor, belt and food (extra action buttons) was gone.

It may be possible that the items were lost when my mate (who does not have the mod) opened my tomb stone to retrieve portal mats.

**Comment by rdepalma2120** [comment]
Same happened to me...
On death, with full inventory, tombstone does not have items that were equipped in the extra slots. (ie armor and utility item)

**Comment by thearn** [comment]
Same happened to me (playing solo). Full armor set and meads in my item slots were gone forever.

Oddly enough, when I try to add back potions using an item spawning mod, they don't show up until I add like 100 of them. Which makes me think the "lost" items are somehow existing in a hidden stack somewhere in my now-bugged inventory?

**Comment by Larkenx** [comment]
I've found that this bug is directly caused by the Gravekeeper mod. It actually deletes items from your gravestone, but fails to push them back into your inventory if you have EquipmentAndQuickSlots enabled. I lost all my gear twice over

**Comment by rdepalma2120** [comment]
I dont have the gravekeeper mod.
It seems to be caused when your inventory is full, anything in the new quick slots have no place to go.

**Comment by sutex** [comment]
Has this bug loosing stuff on death, on the need to fix list?

**Comment by Denthamos** [comment]
My friend and me had the same issue but discovered something.  The items are still in your inventory per say, you just cannot access them.  When we used the sacrifice/recycle tab from another mod on the crafting stations, we could see the items there.  Just not access them in any way.

**Comment by thearn** [comment]
Yeah, if I use the "more slots" mod which adds extra inventory space, I can find them down a couple of rows in the inventory. But if I use the mod to always have a large inventory, they still end up being lost in even more additional row space. Odd.
