### ISSUE TITLE
EquipmentAndQuickSlots - Gamepad Bug in version 2.0.4

### ISSUE THREAD

**Issue by chathamdl** [RandyKnapp/ValheimMods#98]
I cannot move up and down in the crafting menu with my ps4 gamepad when this awesome mod is installed.  It affects Inventory and all Crafting Stations.  It appears that your mod only accepts left and right controls from my joystick which I think is the cause of the issue, because left and right moves crafting to upgrade tabs and vica versa while up and down would allow me to scroll down the list. 

Any help with this would be awesome. Killer Mod by the way.

**Comment by chathamdl** [comment]
Same issue as #79 - Basically up and down dont work.

**Comment by Firsto** [comment]
Same here in the last verson, any solution?
