### ISSUE TITLE
[DvergerColor] NullReferenceException on load (minor)

### ISSUE THREAD

**Issue by Barril** [RandyKnapp/ValheimMods#99]
I'm getting a NullReferenceException on load in [`ShowStatusMessage`](https://github.com/RandyKnapp/ValheimMods/blob/main/DvergerColor/VisEquipment_Patch.cs#L127) due to something (possibly another mod) causing `VisEquipment.AttachItem` to be called at load time.  I suspect MessageHub is null when there's no UI yet, but I've not tested it to be sure.

This doesn't appear to effect anything negatively except a block of red text on my console. 

I can take a look at fixing it if you'd like.

```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
DvergerColor.LightChanger.ShowStatusMessage () (at <6c1386359fb74ae08e08838392af46c2>:0)
DvergerColor.LightChanger.SetLight (UnityEngine.Light light) (at <6c1386359fb74ae08e08838392af46c2>:0)
DvergerColor.VisEquipment_AttachItem_Patch.Postfix (VisEquipment __instance, UnityEngine.GameObject __result, System.Int32 itemHash) (at <6c1386359fb74ae08e08838392af46c2>:0)
(wrapper dynamic-method) VisEquipment.DMD<VisEquipment::AttachItem>(VisEquipment,int,int,UnityEngine.Transform,bool)
VisEquipment.SetHelmetEquiped (System.Int32 hash, System.Int32 hairHash) (at <6fd2223d69c147d18c77057ce0dedd7b>:0)
VisEquipment.UpdateEquipmentVisuals () (at <6fd2223d69c147d18c77057ce0dedd7b>:0)
VisEquipment.UpdateVisuals () (at <6fd2223d69c147d18c77057ce0dedd7b>:0)
VisEquipment.Start () (at <6fd2223d69c147d18c77057ce0dedd7b>:0)
```

**Comment by tueman** [comment]
What other mods did you have installed?

**Comment by Barril** [comment]
I have quite a pile of them.  I think it's ValheimBrawler that fires it when it adds new weapons.  I can narrow it down, but there's really only one line that does something that could throw a null check with that call stack and it makes sense for that to be null at the loading screen:

https://github.com/RandyKnapp/ValheimMods/blob/f3c489b42b6a449fac4924f5f5d9797b17a62c68/DvergerColor/VisEquipment_Patch.cs#L129

I'll probably take a look in a few days, just wanted to toss a bug up for when I have time to debug & fix it locally and submit a PR
